Updating Title to match the tutorial
SharePoint/sp-dev-docs pull request #6642
Opened 2021-01-27 18:16 UTC by bcameron1231

The tutorial is for sending emails when adding an item to a SharePoint List. However,  the title says it's when an Item is Created or Modified. This is not correct. I have updated to reflect this. Fixed #6634

## Category

- [x] Content fix

## Related issues

- fixes #6634 

## What's in this Pull Request?
Updating text to better reflect the tutorial which is adding a new item to a list. Not for modifying an item in a list.

2021-01-27 18:17 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8cdfd10](https://github.com/bcameron1231/sp-dev-docs/commits/8cdfd10c31225e2e1277701f2e75fc3cd74460e8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/get-started/create-your-first-flow.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-13/docs/business-apps/power-automate/get-started/create-your-first-flow.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/get-started/create-your-first-flow?branch=pr-en-us-6642) | [Details](#user-content-347d9457-7e2e3c17)

<a id="347d9457-7e2e3c17"></a>
### [docs/business-apps/power-automate/get-started/create-your-first-flow.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-13/docs/business-apps/power-automate/get-started/create-your-first-flow.md)
 - **Line 64, Column 5**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Flow designer - send email when an item is added in a list' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 68, Column 5**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Flow designer - send email when an item is added in a list' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 121, Column 5**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Flow designer - add owner dynamic content' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````
 - **Line 127, Column 5**: **[Suggestion-duplicate-alt-text]** `````Alt text 'Flow designer - add owner dynamic content' is duplicated. Within an article, alt text must be unique. NOTE: This Suggestion will become a Warning on 1/29/21.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C1%5C27%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202101271816151484-6642%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=XHIebS9wIsla%2F%2BQlZ2ioZBOlX5zk6WUzgaMtFElI8gA%3D&st=2021-01-27T18%3A12%3A33Z&se=2021-02-27T18%3A17%3A33Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-01-27 20:58 UTC, andrewconnell requested changes
Thanks for the submission @bcameron1231 - could you take a look at the build report suggestions and update the alt text on those image so the unique as part of the fix?

Also, please update the `ms.date` property to reflect the timestamp change of the do (MM/DD/YYYY)

2021-02-05 12:04 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b5eb56d](https://github.com/bcameron1231/sp-dev-docs/commits/b5eb56d592c9a5569bd3c93a546cf52c4a66df69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/get-started/create-your-first-flow.md](https://github.com/bcameron1231/sp-dev-docs/blob/patch-13/docs/business-apps/power-automate/get-started/create-your-first-flow.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/get-started/create-your-first-flow?branch=pr-en-us-6642) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C5%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102051203193175-6642%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=voEAVnXFc%2BWHQ5Tg%2FhHPO6eESXFDZd9QocYTO6qn0GU%3D&st=2021-02-05T11%3A59%3A23Z&se=2021-03-08T12%3A04%3A23Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 12:04 UTC, andrewconnell approved these changes

2021-02-05 12:05 UTC, merged