Update migration-isv-guidance.md
SharePoint/sp-dev-docs pull request #6667
Opened 2021-02-01 20:41 UTC by JoanneHendrickson

minor edit

- [X] Content fix

2021-02-01 20:43 UTC, VesaJuvonen commented
Docs Build status updates of commit _[41fbe9a](https://github.com/JoanneHendrickson/sp-dev-docs/commits/41fbe9a6d91c0d74910eae0535bc05d3bd8263ab)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6667) | [Details](#user-content-b5de0ac2-faf9a3e7)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6667) | [Details](#user-content-046f9c66-faf9a3e7)
[docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance?branch=pr-en-us-6667) | [Details](#user-content-7daaab27-faf9a3e7)

<a id="b5de0ac2-faf9a3e7"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-faf9a3e7"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="7daaab27-faf9a3e7"></a>
### [docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````
 - **Line 81, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102012042021252-6667%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=uPIQugXzfMwgOqIyqpKh20g7%2BpGYUxeGNHQZYkzLBHA%3D&st=2021-02-01T20%3A38%3A16Z&se=2021-03-04T20%3A43%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 20:49 UTC, VesaJuvonen commented
Docs Build status updates of commit _[af10993](https://github.com/JoanneHendrickson/sp-dev-docs/commits/af109935c1f3326a410e159739d9821e3a237e79)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-perm-guidance?branch=pr-en-us-6667) | [Details](#user-content-de2091c1-d1a73121)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6667) | [Details](#user-content-b5de0ac2-d1a73121)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6667) | [Details](#user-content-046f9c66-d1a73121)
[docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance?branch=pr-en-us-6667) | [Details](#user-content-7daaab27-d1a73121)

<a id="de2091c1-d1a73121"></a>
### [docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-and-service](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b5de0ac2-d1a73121"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-d1a73121"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="7daaab27-d1a73121"></a>
### [docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````
 - **Line 81, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102012048107489-6667%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W%2BjXE81ZuNn8dkfN5tMbgYOYcGkIlxS8bKeKkGkw02A%3D&st=2021-02-01T20%3A44%3A16Z&se=2021-03-04T20%3A49%3A16Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 20:59 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a78ce3a](https://github.com/JoanneHendrickson/sp-dev-docs/commits/a78ce3a8dc89a1d2544d23e43b34bd506c794a6d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-perm-guidance?branch=pr-en-us-6667) | [Details](#user-content-de2091c1-01fd2bc2)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6667) | [Details](#user-content-b5de0ac2-01fd2bc2)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6667) | [Details](#user-content-046f9c66-01fd2bc2)
[docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance?branch=pr-en-us-6667) | [Details](#user-content-7daaab27-01fd2bc2)
[docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/sp-migration-api-and-sensitivity-labels?branch=pr-en-us-6667) | [Details](#user-content-d4d0709c-01fd2bc2)

<a id="de2091c1-01fd2bc2"></a>
### [docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md)
 - **Line 2, Column 1**: **[Warning-[ms-prod-and-service](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b5de0ac2-01fd2bc2"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-01fd2bc2"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="7daaab27-01fd2bc2"></a>
### [docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````
 - **Line 81, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="d4d0709c-01fd2bc2"></a>
### [docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md)
 - **Line 20, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com//microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102012058503877-6667%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=9HNtuLX7pvyj2XID%2FoATc25uWXiv7IpLy9D3mW9s3m0%3D&st=2021-02-01T20%3A54%3A47Z&se=2021-03-04T20%3A59%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecff [...]

2021-02-01 21:02 UTC, VesaJuvonen commented
Docs Build status updates of commit _[872efa7](https://github.com/JoanneHendrickson/sp-dev-docs/commits/872efa752b78b7eb94acc42060f6b7aaa433f561)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6667) | [Details](#user-content-b5de0ac2-fdd5b25b)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6667) | [Details](#user-content-046f9c66-fdd5b25b)
[docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance?branch=pr-en-us-6667) | [Details](#user-content-7daaab27-fdd5b25b)
[docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/sp-migration-api-and-sensitivity-labels?branch=pr-en-us-6667) | [Details](#user-content-d4d0709c-fdd5b25b)
[docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-perm-guidance?branch=pr-en-us-6667) |

<a id="b5de0ac2-fdd5b25b"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-fdd5b25b"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="7daaab27-fdd5b25b"></a>
### [docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````
 - **Line 81, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/onedrive/developer/rest-api/concepts/scan-guidance?view=odsp-graph-online. Otherwise, remove the view parameter.`````

<a id="d4d0709c-fdd5b25b"></a>
### [docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md)
 - **Line 20, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com//microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102012100511471-6667%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=O0e%2BeKyarz%2FT%2BSqfeCQfTF%2FULIMEHAhgvQHjmTU8vBs%3D&st=2021-02-01T20%3A57%3A00Z&se=2021-03-04T21%3A02%3A00Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-01 21:15 UTC, VesaJuvonen commented
Docs Build status updates of commit _[370fb8e](https://github.com/JoanneHendrickson/sp-dev-docs/commits/370fb8e56df295dc2fdd4b280a05628b785ff6e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6667) | [Details](#user-content-b5de0ac2-b269d30c)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6667) | [Details](#user-content-046f9c66-b269d30c)
[docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance?branch=pr-en-us-6667) | [Details](#user-content-7daaab27-b269d30c)
[docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/sp-migration-api-and-sensitivity-labels?branch=pr-en-us-6667) | [Details](#user-content-d4d0709c-b269d30c)
[docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-perm-guidance?branch=pr-en-us-6667) |

<a id="b5de0ac2-b269d30c"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-b269d30c"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="7daaab27-b269d30c"></a>
### [docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="d4d0709c-b269d30c"></a>
### [docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md)
 - **Line 20, Column 3**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com//microsoft-365/compliance/sensitivity-labels-sharepoint-onedrive-files?view=o365-worldwide. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102012114112339-6667%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BjGtnT3PezQdy5nkcQzcLBgHntkol8bG71PgQJ5ZtxM%3D&st=2021-02-01T21%3A10%3A25Z&se=2021-03-04T21%3A15%3A25Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 16:33 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0aa3814](https://github.com/JoanneHendrickson/sp-dev-docs/commits/0aa3814be7e905907ef55f75f20731d7f72e7f17)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6667) | [Details](#user-content-b5de0ac2-6dae139d)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6667) | [Details](#user-content-046f9c66-6dae139d)
[docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance?branch=pr-en-us-6667) | [Details](#user-content-7daaab27-6dae139d)
[docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-perm-guidance?branch=pr-en-us-6667) |
[docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/sp-migration-api-and-sensitivity-labels?branch=pr-en-us-6667) |

<a id="b5de0ac2-6dae139d"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-6dae139d"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="7daaab27-6dae139d"></a>
### [docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102041632404215-6667%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2Fzs2zbERZFXwYFy%2FK2EOuRXRu8BTSeQOzSoqZrhIPrE%3D&st=2021-02-04T16%3A28%3A47Z&se=2021-03-07T16%3A33%3A47Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-04 16:37 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a889dc0](https://github.com/JoanneHendrickson/sp-dev-docs/commits/a889dc03899ad02868c4840e8a94d333dc6d84ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6667) | [Details](#user-content-b5de0ac2-64f3a7cb)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6667) | [Details](#user-content-046f9c66-64f3a7cb)
[docs/apis/migration-isv-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-isv-guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-isv-guidance?branch=pr-en-us-6667) |
[docs/apis/migration-perm-guidance.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/migration-perm-guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-perm-guidance?branch=pr-en-us-6667) |
[docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/apis/sp-migration-api-and-sensitivity-labels.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/sp-migration-api-and-sensitivity-labels?branch=pr-en-us-6667) |

<a id="b5de0ac2-64f3a7cb"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-64f3a7cb"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-54/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C4%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102041636301110-6667%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=p0kplg0hFnq9jEiASVLnIiLJ48GPFaaWxFgz4VdCLSU%3D&st=2021-02-04T16%3A32%3A31Z&se=2021-03-07T16%3A37%3A31Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 11:31 UTC, andrewconnell commented
The build report is highlighting a few issues that need to be resolved before we can merge this:
- HTTP links need to be updated... they should point to HTTPS links & redirect to the correct URLs

Can you include the TOC update as part of this PR? The TOC change won't go live until this doc is live when they're part of the same PR.

2021-02-05 11:31 UTC, andrewconnell requested changes
The build report is highlighting a few issues that need to be resolved before we can merge this:
- HTTP links need to be updated... they should point to HTTPS links & redirect to the correct URLs

Can you include the TOC update as part of this PR? The TOC change won't go live until this doc is live when they're part of the same PR.

2021-02-05 11:34 UTC, andrewconnell commented
Nevermind my comment about the two insecure links... I see those are unrelated to this PR. I'll get those fixed in another PR.

2021-02-17 12:32 UTC, andrewconnell commented
Bump... @JoanneHendrickson can you take a look at the feedback above?

2021-02-24 01:29 UTC, JoanneHendrickson commented
@andrewconnell I have added the TOC to this PR.

2021-02-26 13:47 UTC, andrewconnell approved these changes

2021-02-26 13:47 UTC, merged