Configuration file needs to be specified as .json file
SharePoint/sp-dev-docs pull request #6674
Opened 2021-02-03 19:40 UTC by Markus-Hanisch

## Category

- [x] Content fix
- [ ] New article

## Related issues

- mentioned in #1838

## What's in this Pull Request?
Fixed the PowerShell example
- Configuration file needs to be specified as .json file. See parameter specification of `-Configuration` in [Get-PnPProvisioningTemplate - Parameters](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps#parameters)
- changed the file names in example to better distinguish configuration file and template file based on [Get-PnPProvisioningTemplate - Examples](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps#examples)

2021-02-03 19:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[40d77c8](https://github.com/Markus-Hanisch/sp-dev-docs/commits/40d77c8d1cc47fc1ca4f98a40f19aa6cd61e4024)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/Markus-Hanisch/sp-dev-docs/blob/patch-1/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-6674) | [Details](#user-content-b5de0ac2-747a7432)
[docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/Markus-Hanisch/sp-dev-docs/blob/patch-1/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in?branch=pr-en-us-6674) | [Details](#user-content-046f9c66-747a7432)
[docs/solution-guidance/configuring-the-pnp-provisioning-engine.md](https://github.com/Markus-Hanisch/sp-dev-docs/blob/patch-1/docs/solution-guidance/configuring-the-pnp-provisioning-engine.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configuring-the-pnp-provisioning-engine?branch=pr-en-us-6674) | [Details](#user-content-06620848-747a7432)

<a id="b5de0ac2-747a7432"></a>
### [docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/Markus-Hanisch/sp-dev-docs/blob/patch-1/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md)
 - **Line 171, Column 79**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 179, Column 551**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/pricing/member-offers/msdn-benefits/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````

<a id="046f9c66-747a7432"></a>
### [docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md](https://github.com/Markus-Hanisch/sp-dev-docs/blob/patch-1/docs/sp-add-ins/choose-patterns-for-developing-and-hosting-your-sharepoint-add-in.md)
 - **Line 139, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/manage/services/cloud-services/what-is-a-cloud-service/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````
 - **Line 140, Column 4**: **[Warning-[insecure-link](https://review.docs.microsoft.com/help/contribute/validation-ref/insecure-link?branch=main)]** `````Link 'http://www.windowsazure.com/develop/net/fundamentals/intro-to-windows-azure/' is insecure. Links to Microsoft sites must use 'https' instead of 'http'.`````

<a id="06620848-747a7432"></a>
### [docs/solution-guidance/configuring-the-pnp-provisioning-engine.md](https://github.com/Markus-Hanisch/sp-dev-docs/blob/patch-1/docs/solution-guidance/configuring-the-pnp-provisioning-engine.md)
 - **Line 2, Column 1**: **[Suggestion-description-missing]** `````Missing required attribute: 'description'.`````
 - **Line 61, Column 108**: **[Suggestion-preserve-view-not-set]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/powershell/module/sharepoint-pnp/get-pnpprovisioningtemplate?view=sharepoint-ps#parameters. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C3%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102031940410505-6674%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=yWnQ9CGZEqveujYHXFvxtCG9U9NdkLwSRxyOAKLjg9Q%3D&st=2021-02-03T19%3A36%3A38Z&se=2021-03-06T19%3A41%3A38Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://teams.microsoft.com/l/message/19:7ecffca1166a4a3986fed528cf0870ee@thread.skype/1590030602688?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&parentMessageId=1590030602688&teamName=Docs%20Support&channelName=General&createdTime=1590030602688) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-05 11:53 UTC, andrewconnell requested changes
Thanks for the submission. We do need a few edits before we can merge this in...

- Please look at the automated build report added in the comments. There are suggestions for the file you're editing. We need to get these entries resolved before we can merge this in. Ignore any build warnings for files that aren't part of this PR.
- Please update the `ms.date` metadata property in the doc's front matter to indicate the timestamp when the file is updated in the format of MM/DD/YYYY.

Thanks!

2021-02-15 11:02 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1351bda](https://github.com/Markus-Hanisch/sp-dev-docs/commits/1351bda9b16852ae871f36cb1db75b03f220e8c1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/configuring-the-pnp-provisioning-engine.md](https://github.com/Markus-Hanisch/sp-dev-docs/blob/patch-1/docs/solution-guidance/configuring-the-pnp-provisioning-engine.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/configuring-the-pnp-provisioning-engine?branch=pr-en-us-6674) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2021%5C2%5C15%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202102151101243672-6674%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=ngqMfjeV%2B03eCE%2FiwGHB0CCpcWB%2B%2Bf7meL8GFEPjJyE%3D&st=2021-02-15T10%3A57%3A34Z&se=2021-03-18T11%3A02%3A34Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-02-15 11:04 UTC, andrewconnell approved these changes

2021-02-15 11:04 UTC, merged