Add info about how to create Taxonomy fields programmatically (SSOM a…
SharePoint/sp-dev-docs pull request #6950
Opened 2021-04-23 13:38 UTC by PiotrekKrakowiak

…nd CSOM)

We had a customer escalation at CSS during which the customer asked what the right way is to create Taxonomy fields programmatically. This article mentions that we do not support creating them through XML, but actually the only way to do it, is by running APIs that contain a partial schema XML of the field. This addition should clarify this point so that the customer sees these ways as supported.

## Category

- [x ] Content fix
- [ ] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

Additional 2 lines describing the right ways of creating Taxonomy fields programmatically

## Submission guidelines

2021-04-23 13:39 UTC, VesaJuvonen commented
Docs Build status updates of commit _[ee87028](https://github.com/PiotrekKrakowiak/sp-dev-docs/commits/ee87028c2bfc8f0c88d537528ba44029ac00f4ca)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/managed-metadata-and-navigation-in-sharepoint.md](https://github.com/PiotrekKrakowiak/sp-dev-docs/blob/patch-13/docs/general-development/managed-metadata-and-navigation-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/managed-metadata-and-navigation-in-sharepoint?branch=pr-en-us-6950) | [Details](#user-content-74be8cb66121396c5e407e4840c75380-6121a97d)

<a id="74be8cb66121396c5e407e4840c75380-6121a97d"></a>
### [docs/general-development/managed-metadata-and-navigation-in-sharepoint.md](https://github.com/PiotrekKrakowiak/sp-dev-docs/blob/patch-13/docs/general-development/managed-metadata-and-navigation-in-sharepoint.md)
 - **Line 219, Column 117**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.taxonomyfield?view=sharepoint-server' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 221, Column 188**: **[Warning-[hard-coded-locale](https://review.docs.microsoft.com/help/contribute/validation-ref/hard-coded-locale?branch=main)]** `````Link 'https://docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/complete-basic-operations-using-sharepoint-client-library-code#add-a-field-to-a-sharepoint-list' contains locale code 'en-us'. For localizability, remove 'en-us' from links to most Microsoft sites.`````
 - **Line 219, Column 117**: **[Suggestion-[preserve-view-not-set](https://review.docs.microsoft.com/help/contribute/validation-ref/preserve-view-not-set?branch=main)]** `````Did you mean to link to a specific version? It's usually better not to specify a version, so the link always goes to the canonical version. If you really need to link to a specific version, add &preserve-view=true to the URL: https://docs.microsoft.com/en-us/dotnet/api/microsoft.sharepoint.taxonomy.taxonomyfield?view=sharepoint-server. Otherwise, remove the view parameter.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C4%5C23%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202104231338495481-6950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DZy8SkD7ZLCNcqdYScQDG1NuTbUx4hyDDF6Xe%2Fdvsvs%3D&st=2021-04-23T13%3A34%3A57Z&se=2021-05-24T13%3A39%3A57Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-04-27 14:19 UTC, andrewconnell requested changes
Thanks for the submission... can you please remove the locale from the URLs as MSDocs will redirect the user to their appropriate locale?

2021-05-18 11:16 UTC, VesaJuvonen commented
Docs Build status updates of commit _[6f956e8](https://github.com/PiotrekKrakowiak/sp-dev-docs/commits/6f956e8ec49f07190602c866842caecd66ab455e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/managed-metadata-and-navigation-in-sharepoint.md](https://github.com/PiotrekKrakowiak/sp-dev-docs/blob/patch-13/docs/general-development/managed-metadata-and-navigation-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/managed-metadata-and-navigation-in-sharepoint?branch=pr-en-us-6950) | [Details](#user-content-74be8cb66121396c5e407e4840c75380-d649904c)

<a id="74be8cb66121396c5e407e4840c75380-d649904c"></a>
### [docs/general-development/managed-metadata-and-navigation-in-sharepoint.md](https://github.com/PiotrekKrakowiak/sp-dev-docs/blob/patch-13/docs/general-development/managed-metadata-and-navigation-in-sharepoint.md)
 - **Line 135, Column 117**: **[Warning-[link-text-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/link-text-missing?branch=main	)]** `````Missing link text for link '/dotnet/api/microsoft.sharepoint.taxonomy.taxonomyfield'. Add appropriate text.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202105181115358998-6950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2FXv62mae%2FsiVjIg8aeEMvsCrJX7aOrVCeFgtn5HHmvw%3D&st=2021-05-18T11%3A11%3A37Z&se=2021-06-18T11%3A16%3A37Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 11:19 UTC, VesaJuvonen commented
Docs Build status updates of commit _[9e678be](https://github.com/PiotrekKrakowiak/sp-dev-docs/commits/9e678be7f85b3fa1a80076eb5712d077aabf87d0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/managed-metadata-and-navigation-in-sharepoint.md](https://github.com/PiotrekKrakowiak/sp-dev-docs/blob/patch-13/docs/general-development/managed-metadata-and-navigation-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/managed-metadata-and-navigation-in-sharepoint?branch=pr-en-us-6950) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C5%5C18%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202105181118227915-6950%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2F0g3sGgDJmwbazHqW7sFtmIfYKD5zkn8Ql%2FKU%2BAQed8%3D&st=2021-05-18T11%3A14%3A02Z&se=2021-06-18T11%3A19%3A02Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-05-18 11:19 UTC, andrewconnell approved these changes

2021-05-18 11:23 UTC, merged