FAQ converted into yml
SharePoint/sp-dev-docs pull request #7064
Opened 2021-06-01 23:04 UTC by v-hearya

known-issues-and-common-questions.md
modernize-scanner-faq.md
publish-to-marketplace-faq.md
frequently-asked-questions-about-excel-services-udfs.md
converted into yml

2021-06-01 23:20 UTC, VesaJuvonen commented
Docs Build status updates of commit _[d8aa43c](https://github.com/v-hearya/sp-dev-docs/commits/d8aa43c2775df9232cdddf087eda26d525f52fee)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :x:Error | | [Details](#user-content-47daf7aef6728882d56ab9eb568676f8-3828a783)
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :bulb:Suggestion | | [Details](#user-content-2b6a5552173c0c51533e5f39b8470c6c-3828a783)
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :bulb:Suggestion | | [Details](#user-content-7b18854a8e58fbb74b699b3d10b524d9-3828a783)
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :bulb:Suggestion | | [Details](#user-content-a106d610415596cd69ea9f1fcf29c809-3828a783)
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :bulb:Suggestion | | [Details](#user-content-5f5eee8941dbde00b1877c7ded12e7e1-3828a783)
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :bulb:Suggestion | | [Details](#user-content-9e7cd1668b52680146c3810a9e472e35-3828a783)
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :bulb:Suggestion | | [Details](#user-content-c225fce210c5dbafef1e3d242183a635-3828a783)

<a id="47daf7aef6728882d56ab9eb568676f8-3828a783"></a>
### [docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml)
 - **Line 191, Column 3**: **[Error-yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="2b6a5552173c0c51533e5f39b8470c6c-3828a783"></a>
### [docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="7b18854a8e58fbb74b699b3d10b524d9-3828a783"></a>
### [docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="a106d610415596cd69ea9f1fcf29c809-3828a783"></a>
### [docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="5f5eee8941dbde00b1877c7ded12e7e1-3828a783"></a>
### [docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="9e7cd1668b52680146c3810a9e472e35-3828a783"></a>
### [docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="c225fce210c5dbafef1e3d242183a635-3828a783"></a>
### [docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C1%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106012319103128-7064%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UdYo835BagNpL0nYEPNfwC%2BnTCTbIEicQXe0gB3CFnM%3D&st=2021-06-01T23%3A15%3A15Z&se=2021-07-02T23%3A20%3A15Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-01 23:33 UTC, VesaJuvonen commented
Docs Build status updates of commit _[554144e](https://github.com/v-hearya/sp-dev-docs/commits/554144e39ffd9e1d405e78a5d1db7c98cd9ce3c2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :warning:Warning | | [Details](#user-content-8de8c8b6)
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) | [Details](#user-content-2b6a5552173c0c51533e5f39b8470c6c-8de8c8b6)
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-user-defined-functions?branch=pr-en-us-7064) | [Details](#user-content-7b18854a8e58fbb74b699b3d10b524d9-8de8c8b6)
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-an-external-data-source-from-a-udf?branch=pr-en-us-7064) | [Details](#user-content-a106d610415596cd69ea9f1fcf29c809-8de8c8b6)
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-enable-udfs?branch=pr-en-us-7064) | [Details](#user-content-5f5eee8941dbde00b1877c7ded12e7e1-8de8c8b6)
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-restrict-udf-code-access-security-permissions?branch=pr-en-us-7064) | [Details](#user-content-9e7cd1668b52680146c3810a9e472e35-8de8c8b6)
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-excel-services-udfs?branch=pr-en-us-7064) | [Details](#user-content-c225fce210c5dbafef1e3d242183a635-8de8c8b6)
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions?branch=pr-en-us-7064) |
[docs/spfx/known-issues-and-common-questions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.md) | :white_check_mark:Succeeded | |
[docs/spfx/known-issues-and-common-questions.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.md) | :white_check_mark:Succeeded | |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview?branch=pr-en-us-7064) |
[docs/spfx/release-1.11.0.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/release-1.11.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0?branch=pr-en-us-7064) |
[docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part?branch=pr-en-us-7064) |
[docs/toc.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/transform/modernize-scanner-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.md) | :white_check_mark:Succeeded | |
[docs/transform/modernize-scanner-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq?branch=pr-en-us-7064) |

<a id="8de8c8b6"></a>
###
 - **Line 0, Column 0**: **[Warning-output-path-conflict]** `````Two or more files output to the same path 'sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs.raw.page.json': 'general-development/frequently-asked-questions-about-excel-services-udfs.md', 'general-development/frequently-asked-questions-about-excel-services-udfs.yml'.`````

<a id="2b6a5552173c0c51533e5f39b8470c6c-8de8c8b6"></a>
### [docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="7b18854a8e58fbb74b699b3d10b524d9-8de8c8b6"></a>
### [docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="a106d610415596cd69ea9f1fcf29c809-8de8c8b6"></a>
### [docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.c [...]

2021-06-02 00:06 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b256f65](https://github.com/v-hearya/sp-dev-docs/commits/b256f656c0bf4a2fb03572b1d7af213a17f2ae98)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) | [Details](#user-content-2b6a5552173c0c51533e5f39b8470c6c-4f92b3c3)
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-user-defined-functions?branch=pr-en-us-7064) | [Details](#user-content-7b18854a8e58fbb74b699b3d10b524d9-4f92b3c3)
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-an-external-data-source-from-a-udf?branch=pr-en-us-7064) | [Details](#user-content-a106d610415596cd69ea9f1fcf29c809-4f92b3c3)
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-enable-udfs?branch=pr-en-us-7064) | [Details](#user-content-5f5eee8941dbde00b1877c7ded12e7e1-4f92b3c3)
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-restrict-udf-code-access-security-permissions?branch=pr-en-us-7064) | [Details](#user-content-9e7cd1668b52680146c3810a9e472e35-4f92b3c3)
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-excel-services-udfs?branch=pr-en-us-7064) | [Details](#user-content-c225fce210c5dbafef1e3d242183a635-4f92b3c3)
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.md) | :white_check_mark:Succeeded | |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions?branch=pr-en-us-7064) |
[docs/spfx/known-issues-and-common-questions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.md) | :white_check_mark:Succeeded | |
[docs/spfx/known-issues-and-common-questions.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.md) | :white_check_mark:Succeeded | |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview?branch=pr-en-us-7064) |
[docs/spfx/release-1.11.0.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/release-1.11.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0?branch=pr-en-us-7064) |
[docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part?branch=pr-en-us-7064) |
[docs/toc.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/transform/modernize-scanner-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.md) | :white_check_mark:Succeeded | |
[docs/transform/modernize-scanner-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq?branch=pr-en-us-7064) |

<a id="2b6a5552173c0c51533e5f39b8470c6c-4f92b3c3"></a>
### [docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="7b18854a8e58fbb74b699b3d10b524d9-4f92b3c3"></a>
### [docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="a106d610415596cd69ea9f1fcf29c809-4f92b3c3"></a>
### [docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missi [...]

2021-06-02 00:08 UTC, v-hearya commented
@VesaJuvonen - Could you please review the .yml converted page and let me know if it's good to sign-off.

cc: @khairunj

2021-06-14 10:27 UTC, andrewconnell requested changes
There are numerous msdocs suggestions that will eventually be flagged as errors. can you please ensure all the files missing a `description` property in the doc's metadata are addressed?

2021-06-17 00:06 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1bc1110](https://github.com/v-hearya/sp-dev-docs/commits/1bc1110f21fb845ec0cffe1bea3d1a3884017b2f)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) | [Details](#user-content-2b6a5552173c0c51533e5f39b8470c6c-c2137954)
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-user-defined-functions?branch=pr-en-us-7064) | [Details](#user-content-7b18854a8e58fbb74b699b3d10b524d9-c2137954)
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-an-external-data-source-from-a-udf?branch=pr-en-us-7064) | [Details](#user-content-a106d610415596cd69ea9f1fcf29c809-c2137954)
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-enable-udfs?branch=pr-en-us-7064) | [Details](#user-content-5f5eee8941dbde00b1877c7ded12e7e1-c2137954)
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-restrict-udf-code-access-security-permissions?branch=pr-en-us-7064) | [Details](#user-content-9e7cd1668b52680146c3810a9e472e35-c2137954)
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-excel-services-udfs?branch=pr-en-us-7064) | [Details](#user-content-c225fce210c5dbafef1e3d242183a635-c2137954)
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.md) | :white_check_mark:Succeeded | |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions?branch=pr-en-us-7064) |
[docs/spfx/known-issues-and-common-questions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.md) | :white_check_mark:Succeeded | |
[docs/spfx/known-issues-and-common-questions.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.md) | :white_check_mark:Succeeded | |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview?branch=pr-en-us-7064) |
[docs/spfx/release-1.11.0.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/release-1.11.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0?branch=pr-en-us-7064) |
[docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part?branch=pr-en-us-7064) |
[docs/toc.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/transform/modernize-scanner-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.md) | :white_check_mark:Succeeded | |
[docs/transform/modernize-scanner-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq?branch=pr-en-us-7064) |

<a id="2b6a5552173c0c51533e5f39b8470c6c-c2137954"></a>
### [docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="7b18854a8e58fbb74b699b3d10b524d9-c2137954"></a>
### [docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="a106d610415596cd69ea9f1fcf29c809-c2137954"></a>
### [docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missi [...]

2021-06-17 00:12 UTC, v-hearya commented
> There are numerous msdocs suggestions that will eventually be flagged as errors. can you please ensure all the files missing a `description` property in the doc's metadata are addressed?

@andrewconnell @VesaJuvonen - Could you please provide the description text for reported files.


@khairunjamal

2021-06-17 12:29 UTC, andrewconnell commented
The metadata `description` property is used for SEO... usually docs contain a description at the beginning of the doc you can use as the description. That's all I'd do, or review the content of the article and create something that explains what the page is about. Thanks for addressing these issues.

2021-06-21 20:13 UTC, VesaJuvonen commented
Docs Build status updates of commit _[6e1add3](https://github.com/v-hearya/sp-dev-docs/commits/6e1add3bba4dfc48325f39971d45a28ddf8a72fc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer?branch=pr-en-us-7064) | [Details](#user-content-aac35c6357cf087f23b4956e6c05b8f1-eaef482a)
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) | [Details](#user-content-2b6a5552173c0c51533e5f39b8470c6c-eaef482a)
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-user-defined-functions?branch=pr-en-us-7064) | [Details](#user-content-7b18854a8e58fbb74b699b3d10b524d9-eaef482a)
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-an-external-data-source-from-a-udf?branch=pr-en-us-7064) | [Details](#user-content-a106d610415596cd69ea9f1fcf29c809-eaef482a)
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-enable-udfs?branch=pr-en-us-7064) | [Details](#user-content-5f5eee8941dbde00b1877c7ded12e7e1-eaef482a)
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-restrict-udf-code-access-security-permissions?branch=pr-en-us-7064) | [Details](#user-content-9e7cd1668b52680146c3810a9e472e35-eaef482a)
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-excel-services-udfs?branch=pr-en-us-7064) | [Details](#user-content-c225fce210c5dbafef1e3d242183a635-eaef482a)
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.md) | :white_check_mark:Succeeded | |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions?branch=pr-en-us-7064) |
[docs/spfx/known-issues-and-common-questions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.md) | :white_check_mark:Succeeded | |
[docs/spfx/known-issues-and-common-questions.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.md) | :white_check_mark:Succeeded | |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview?branch=pr-en-us-7064) |
[docs/spfx/release-1.11.0.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/release-1.11.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0?branch=pr-en-us-7064) |
[docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part?branch=pr-en-us-7064) |
[docs/toc.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/transform/modernize-scanner-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.md) | :white_check_mark:Succeeded | |
[docs/transform/modernize-scanner-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq?branch=pr-en-us-7064) |

<a id="aac35c6357cf087f23b4956e6c05b8f1-eaef482a"></a>
### [docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/extensions/get-started/building-simple-field-customizer.md)
 - **Line 373, Column 108**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../../declarative-customization/column-formatting'.`````

<a id="2b6a5552173c0c51533e5f39b8470c6c-eaef482a"></a>
### [docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md)
 - **Line 2, Column 1**: **[Suggestion-[description-missing](https://review.docs.microsoft. [...]

2021-06-21 20:29 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1b3b124](https://github.com/v-hearya/sp-dev-docs/commits/1b3b1245c9f26b1d8e6cd3cc959544632f89c612)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer?branch=pr-en-us-7064) | [Details](#user-content-aac35c6357cf087f23b4956e6c05b8f1-d411a6ea)
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-user-defined-functions?branch=pr-en-us-7064) |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.md) | :white_check_mark:Succeeded | |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-an-external-data-source-from-a-udf?branch=pr-en-us-7064) |
[docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions?branch=pr-en-us-7064) |
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-enable-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-restrict-udf-code-access-security-permissions?branch=pr-en-us-7064) |
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-excel-services-udfs?branch=pr-en-us-7064) |
[docs/spfx/known-issues-and-common-questions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.md) | :white_check_mark:Succeeded | |
[docs/spfx/known-issues-and-common-questions.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.md) | :white_check_mark:Succeeded | |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview?branch=pr-en-us-7064) |
[docs/spfx/release-1.11.0.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/release-1.11.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0?branch=pr-en-us-7064) |
[docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part?branch=pr-en-us-7064) |
[docs/toc.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/transform/modernize-scanner-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.md) | :white_check_mark:Succeeded | |
[docs/transform/modernize-scanner-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq?branch=pr-en-us-7064) |

<a id="aac35c6357cf087f23b4956e6c05b8f1-d411a6ea"></a>
### [docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/extensions/get-started/building-simple-field-customizer.md)
 - **Line 373, Column 108**: **[Warning-[file-not-found](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: '../../../declarative-customization/column-formatting'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106212027565273-7064%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=eJ3KlMXADPHB0tNFdp97AaxWInQz5PSKo61giDiua2o%3D&st=2021-06-21T20%3A24%3A53Z&se=2021-07-22T20%3A29%3A53Z&sp=r).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=master) to re-authorize your GitHub accoun [...]

2021-06-21 20:36 UTC, VesaJuvonen commented
Docs Build status updates of commit _[dbd2b76](https://github.com/v-hearya/sp-dev-docs/commits/dbd2b76dc232f7a35cc877df0029ee4755d37897)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-user-defined-functions?branch=pr-en-us-7064) |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.md) | :white_check_mark:Succeeded | |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-an-external-data-source-from-a-udf?branch=pr-en-us-7064) |
[docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions?branch=pr-en-us-7064) |
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-enable-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-restrict-udf-code-access-security-permissions?branch=pr-en-us-7064) |
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-excel-services-udfs?branch=pr-en-us-7064) |
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field-customizer?branch=pr-en-us-7064) |
[docs/spfx/known-issues-and-common-questions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.md) | :white_check_mark:Succeeded | |
[docs/spfx/known-issues-and-common-questions.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.md) | :white_check_mark:Succeeded | |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview?branch=pr-en-us-7064) |
[docs/spfx/release-1.11.0.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/release-1.11.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0?branch=pr-en-us-7064) |
[docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part?branch=pr-en-us-7064) |
[docs/toc.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/transform/modernize-scanner-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.md) | :white_check_mark:Succeeded | |
[docs/transform/modernize-scanner-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq?branch=pr-en-us-7064) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C21%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106212034187714-7064%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=b5WNBQ3pkGNw7DytwMOthHqsb3m%2BDALzhP1i4LEnhHI%3D&st=2021-06-21T20%3A31%3A05Z&se=2021-07-22T20%3A36%3A05Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-21 20:37 UTC, v-hearya commented
> The metadata `description` property is used for SEO... usually docs contain a description at the beginning of the doc you can use as the description. That's all I'd do, or review the content of the article and create something that explains what the page is about. Thanks for addressing these issues.

@andrewconnell - Description warning solved.

2021-06-29 22:44 UTC, VesaJuvonen commented
Docs Build status updates of commit _[35f08ad](https://github.com/v-hearya/sp-dev-docs/commits/35f08ad31209f7ab13b005e8efaf1e3be2ed9997)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/excel-services-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/general-development/excel-services-user-defined-functions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/excel-services-user-defined-functions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-user-defined-functions?branch=pr-en-us-7064) |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.md) | :white_check_mark:Succeeded | |
[docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/frequently-asked-questions-about-excel-services-udfs.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/frequently-asked-questions-about-excel-services-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-access-an-external-data-source-from-a-udf.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-access-an-external-data-source-from-a-udf.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-an-external-data-source-from-a-udf?branch=pr-en-us-7064) |
[docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-deploy-udfs-using-sharepoint-foundation-solutions?branch=pr-en-us-7064) |
[docs/general-development/how-to-enable-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-enable-udfs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-enable-udfs?branch=pr-en-us-7064) |
[docs/general-development/how-to-restrict-udf-code-access-security-permissions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/how-to-restrict-udf-code-access-security-permissions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-restrict-udf-code-access-security-permissions?branch=pr-en-us-7064) |
[docs/general-development/understanding-excel-services-udfs.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/general-development/understanding-excel-services-udfs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/understanding-excel-services-udfs?branch=pr-en-us-7064) |
[docs/spfx/known-issues-and-common-questions.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.md) | :white_check_mark:Succeeded | |
[docs/spfx/known-issues-and-common-questions.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/known-issues-and-common-questions.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/known-issues-and-common-questions?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.md) | :white_check_mark:Succeeded | |
[docs/spfx/publish-to-marketplace-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-faq?branch=pr-en-us-7064) |
[docs/spfx/publish-to-marketplace-overview.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/publish-to-marketplace-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-overview?branch=pr-en-us-7064) |
[docs/spfx/release-1.11.0.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/release-1.11.0.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/release-1.11.0?branch=pr-en-us-7064) |
[docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/spfx/web-parts/get-started/build-a-hello-world-web-part.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/get-started/build-a-hello-world-web-part?branch=pr-en-us-7064) |
[docs/toc.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/toc.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-overview?branch=pr-en-us-7064) |
[docs/transform/modernize-scanner-faq.md](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.md) | :white_check_mark:Succeeded | |
[docs/transform/modernize-scanner-faq.yml](https://github.com/v-hearya/sp-dev-docs/blob/FAQ-YML-Conversion-vesaj/docs/transform/modernize-scanner-faq.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq?branch=pr-en-us-7064) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C6%5C29%5C8c4da01d-e430-7fe7-0bea-2c4100cce9e8%5CPullRequest%5C202106292244182202-7064%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VukZulEka9bsOtgPc4zmoUDCWC04UqEHoFfa0Tl71qA%3D&st=2021-06-29T22%3A39%3A55Z&se=2021-07-30T22%3A44%3A55Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-06-29 22:49 UTC, v-hearya commented
@andrewconnell - Could you please review the .yml converted page and let me know if it's good to sign-off.

2021-06-30 09:44 UTC, andrewconnell approved these changes

2021-06-30 09:45 UTC, andrewconnell commented
Thanks for addressing the MSDOCS warning.

This is a big change to the docs and not one I can merge into the repo... I need to let @VesaJuvonen do that.

2021-07-12 11:46 UTC, merged