Validation: Description-missing and disallowed-html-tag fixes.
SharePoint/sp-dev-docs pull request #8019
Opened 2022-06-04 16:30 UTC by brittmsantos

## Category

- [x] Content fix
- [ ] New article

## Related issues

no issue number - part of the Validation cleanup efforts.

## What's in this Pull Request?

This PR fixes 33 issues in 30 files.

2022-06-04 16:32 UTC, VesaJuvonen commented
Docs Build status updates of commit _[e738792](https://github.com/brittmsantos/sp-dev-docs/commits/e738792beee8fc4b23ce708ca2ca69cf5f119db0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-security-trimming-for-search-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-02050feb7ff94e8524ea62ad926aca63-2e2ce3d9)
[docs/general-development/custom-word-breakers-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-word-breakers-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-word-breakers-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-3c8597167fa4f0e1f2272e2d16cfe8fc-2e2ce3d9)
[docs/general-development/customizing-search-results-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/customizing-search-results-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/customizing-search-results-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-5cf813f17460fd8e0a7a4df3a05dee9b-2e2ce3d9)
[docs/general-development/debugging-sharepoint-server-workflows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/debugging-sharepoint-server-workflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/debugging-sharepoint-server-workflows?branch=pr-en-us-8019) | [Details](#user-content-96ffc8bd5a75a8b244f7872363b74455-2e2ce3d9)
[docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions?branch=pr-en-us-8019) | [Details](#user-content-379d3619bb07a36bc4f4c584c090bdef-2e2ce3d9)
[docs/general-development/develop-access-web-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-access-web-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-access-web-apps?branch=pr-en-us-8019) | [Details](#user-content-64461401f599671e475b9b97d6e9edf2-2e2ce3d9)
[docs/general-development/develop-the-site-design-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-the-site-design-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-the-site-design-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-a004d97bcf780578e842891c6c2cd816-2e2ce3d9)
[docs/general-development/developing-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/developing-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/developing-with-duet-enterprise-2-0?branch=pr-en-us-8019) | [Details](#user-content-aa4383bb9c28c317259084f3004433aa-2e2ce3d9)
[docs/general-development/discovery-in-excel-services-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/discovery-in-excel-services-rest-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/discovery-in-excel-services-rest-api?branch=pr-en-us-8019) | [Details](#user-content-7bff773da3f210276314936b2d170d77-2e2ce3d9)
[docs/general-development/ediscovery-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/ediscovery-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/ediscovery-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-275d56f5d41a2471b55779ab15a87c13-2e2ce3d9)
[docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-b96c1287c541f4809f84bc3841a0df59-2e2ce3d9)
[docs/general-development/excel-services-alerts.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-alerts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-alerts?branch=pr-en-us-8019) | [Details](#user-content-e6cb9d2fccf86e3e8955c09ae2b5a4ef-2e2ce3d9)
[docs/general-development/excel-services-architecture.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-architecture.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-architecture?branch=pr-en-us-8019) | [Details](#user-content-61203108cbe069b45aec040041bedc3f-2e2ce3d9)
[docs/general-development/excel-services-best-practices.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-best-practices?branch=pr-en-us-8019) | [Details](#user-content-354f0fb298421eb5c71a6441c2b6454a-2e2ce3d9)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8019) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-2e2ce3d9)
[docs/general-development/excel-services-development-roadmap.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-development-roadmap.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-development-roadmap?branch=pr-en-us-8019) | [Details](#user-content-d085527ad02e03a00778d1d96f269a59-2e2ce3d9)
[docs/general-development/excel-services-ecmascript-javascript-jscript.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-javascript-jscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-javascript-jscript?branch=pr-en-us-8019) | [Details](#user-content-d89c6d2162bb834977ee264d5f588fb2-2e2ce3d9)
[docs/general-development/excel-services-ecmascript-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-overview?branch=pr-en-us-8019) | [Details](#user-content-b87142ae843e0d8934366bf588d3d889-2e2ce3d9)
[docs/general-development/excel-services-known-issues-and-tips.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-known-issues-and [...]

2022-06-04 20:20 UTC, brittmsantos commented
@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-07 11:50 UTC, andrewconnell requested changes
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

2022-06-07 15:23 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8265553](https://github.com/brittmsantos/sp-dev-docs/commits/8265553b6869cc4972d82effe0ec296e6337a18e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-security-trimming-for-search-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-02050feb7ff94e8524ea62ad926aca63-f215c90c)
[docs/general-development/custom-word-breakers-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-word-breakers-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-word-breakers-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-3c8597167fa4f0e1f2272e2d16cfe8fc-f215c90c)
[docs/general-development/customizing-search-results-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/customizing-search-results-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/customizing-search-results-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-5cf813f17460fd8e0a7a4df3a05dee9b-f215c90c)
[docs/general-development/debugging-sharepoint-server-workflows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/debugging-sharepoint-server-workflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/debugging-sharepoint-server-workflows?branch=pr-en-us-8019) | [Details](#user-content-96ffc8bd5a75a8b244f7872363b74455-f215c90c)
[docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions?branch=pr-en-us-8019) | [Details](#user-content-379d3619bb07a36bc4f4c584c090bdef-f215c90c)
[docs/general-development/develop-access-web-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-access-web-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-access-web-apps?branch=pr-en-us-8019) | [Details](#user-content-64461401f599671e475b9b97d6e9edf2-f215c90c)
[docs/general-development/develop-the-site-design-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-the-site-design-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-the-site-design-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-a004d97bcf780578e842891c6c2cd816-f215c90c)
[docs/general-development/developing-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/developing-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/developing-with-duet-enterprise-2-0?branch=pr-en-us-8019) | [Details](#user-content-aa4383bb9c28c317259084f3004433aa-f215c90c)
[docs/general-development/discovery-in-excel-services-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/discovery-in-excel-services-rest-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/discovery-in-excel-services-rest-api?branch=pr-en-us-8019) | [Details](#user-content-7bff773da3f210276314936b2d170d77-f215c90c)
[docs/general-development/ediscovery-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/ediscovery-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/ediscovery-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-275d56f5d41a2471b55779ab15a87c13-f215c90c)
[docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-b96c1287c541f4809f84bc3841a0df59-f215c90c)
[docs/general-development/excel-services-alerts.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-alerts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-alerts?branch=pr-en-us-8019) | [Details](#user-content-e6cb9d2fccf86e3e8955c09ae2b5a4ef-f215c90c)
[docs/general-development/excel-services-architecture.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-architecture.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-architecture?branch=pr-en-us-8019) | [Details](#user-content-61203108cbe069b45aec040041bedc3f-f215c90c)
[docs/general-development/excel-services-best-practices.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-best-practices?branch=pr-en-us-8019) | [Details](#user-content-354f0fb298421eb5c71a6441c2b6454a-f215c90c)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8019) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-f215c90c)
[docs/general-development/excel-services-development-roadmap.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-development-roadmap.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-development-roadmap?branch=pr-en-us-8019) | [Details](#user-content-d085527ad02e03a00778d1d96f269a59-f215c90c)
[docs/general-development/excel-services-ecmascript-javascript-jscript.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-javascript-jscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-javascript-jscript?branch=pr-en-us-8019) | [Details](#user-content-d89c6d2162bb834977ee264d5f588fb2-f215c90c)
[docs/general-development/excel-services-ecmascript-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-overview?branch=pr-en-us-8019) | [Details](#user-content-b87142ae843e0d8934366bf588d3d889-f215c90c)
[docs/general-development/excel-services-known-issues-and-tips.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-known-issues-and [...]

2022-06-09 10:31 UTC, andrewconnell requested changes

2022-06-09 10:31 UTC, andrewconnell commented on docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md
> +The **ISecurityTrimmerPost** interface contains two methods that you must implement: [Initialize(NameValueCollection, SearchServiceApplication)](https://msdn.microsoft.com/library/Microsoft.Office.Se
Correct markdown escaping of angled brackets should be prefixed with\; don't change to the HTML encoding.

2022-06-09 10:31 UTC, andrewconnell commented on docs/general-development/debugging-sharepoint-server-workflows.md
> +Next, add the following markup to the bottom of each file, just before the closing **&lt;configuration&gt;** element:
Correct markdown escaping of angled brackets should be prefixed with\; don't change to the HTML encoding.

2022-06-09 10:31 UTC, andrewconnell commented on docs/general-development/excel-services-known-issues-and-tips.md
> + **System.InvalidOperationException: Client found response content type of 'text/html; charset=utf-8', but expected 'text/xml'. The request failed with the error message: -- &lt;html&gt; &lt;head&gt;
Correct markdown escaping of angled brackets should be prefixed with\; don't change to the HTML encoding.

2022-06-09 10:52 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

Sets the date of these files not to the current date when they were changed (June 2022), rather backdated them, defeating the purposes of this property.

2022-06-09 18:40 UTC, VesaJuvonen commented
Docs Build status updates of commit _[2e9e3e3](https://github.com/brittmsantos/sp-dev-docs/commits/2e9e3e3e72b558df8de8a73af038a308d538b994)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-security-trimming-for-search-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-02050feb7ff94e8524ea62ad926aca63-8bbaecbe)
[docs/general-development/custom-word-breakers-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-word-breakers-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-word-breakers-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-3c8597167fa4f0e1f2272e2d16cfe8fc-8bbaecbe)
[docs/general-development/customizing-search-results-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/customizing-search-results-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/customizing-search-results-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-5cf813f17460fd8e0a7a4df3a05dee9b-8bbaecbe)
[docs/general-development/debugging-sharepoint-server-workflows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/debugging-sharepoint-server-workflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/debugging-sharepoint-server-workflows?branch=pr-en-us-8019) | [Details](#user-content-96ffc8bd5a75a8b244f7872363b74455-8bbaecbe)
[docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions?branch=pr-en-us-8019) | [Details](#user-content-379d3619bb07a36bc4f4c584c090bdef-8bbaecbe)
[docs/general-development/develop-access-web-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-access-web-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-access-web-apps?branch=pr-en-us-8019) | [Details](#user-content-64461401f599671e475b9b97d6e9edf2-8bbaecbe)
[docs/general-development/develop-the-site-design-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-the-site-design-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-the-site-design-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-a004d97bcf780578e842891c6c2cd816-8bbaecbe)
[docs/general-development/developing-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/developing-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/developing-with-duet-enterprise-2-0?branch=pr-en-us-8019) | [Details](#user-content-aa4383bb9c28c317259084f3004433aa-8bbaecbe)
[docs/general-development/discovery-in-excel-services-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/discovery-in-excel-services-rest-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/discovery-in-excel-services-rest-api?branch=pr-en-us-8019) | [Details](#user-content-7bff773da3f210276314936b2d170d77-8bbaecbe)
[docs/general-development/ediscovery-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/ediscovery-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/ediscovery-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-275d56f5d41a2471b55779ab15a87c13-8bbaecbe)
[docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-b96c1287c541f4809f84bc3841a0df59-8bbaecbe)
[docs/general-development/excel-services-alerts.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-alerts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-alerts?branch=pr-en-us-8019) | [Details](#user-content-e6cb9d2fccf86e3e8955c09ae2b5a4ef-8bbaecbe)
[docs/general-development/excel-services-architecture.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-architecture.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-architecture?branch=pr-en-us-8019) | [Details](#user-content-61203108cbe069b45aec040041bedc3f-8bbaecbe)
[docs/general-development/excel-services-best-practices.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-best-practices?branch=pr-en-us-8019) | [Details](#user-content-354f0fb298421eb5c71a6441c2b6454a-8bbaecbe)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8019) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-8bbaecbe)
[docs/general-development/excel-services-development-roadmap.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-development-roadmap.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-development-roadmap?branch=pr-en-us-8019) | [Details](#user-content-d085527ad02e03a00778d1d96f269a59-8bbaecbe)
[docs/general-development/excel-services-ecmascript-javascript-jscript.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-javascript-jscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-javascript-jscript?branch=pr-en-us-8019) | [Details](#user-content-d89c6d2162bb834977ee264d5f588fb2-8bbaecbe)
[docs/general-development/excel-services-ecmascript-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-overview?branch=pr-en-us-8019) | [Details](#user-content-b87142ae843e0d8934366bf588d3d889-8bbaecbe)
[docs/general-development/excel-services-known-issues-and-tips.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-known-issues-and [...]

2022-06-09 18:49 UTC, brittmsantos commented
@andrewconnell 

My sincere apologies about the confusion. I've gone and set the property properly in addition to your other requested changes, and I'll be going back through all of my PRs in this repo and updating them accordingly. 

Please let me know if there are any other issues in this PR that prevent approval and merge. Thank you very much, and have a great day!

2022-06-13 19:59 UTC, RedZephyr13 commented on docs/general-development/fast-query-language-fql-syntax-reference.md
> +| Parameter |        Value        |     &nbsp;     |  Description |
Since HTML is frowned upon, let's replace "&nbsp;" with "Value."

2022-06-13 20:18 UTC, VesaJuvonen commented
Docs Build status updates of commit _[4ec2a43](https://github.com/brittmsantos/sp-dev-docs/commits/4ec2a43d366113530dcfe2d99849a6804829a502)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-security-trimming-for-search-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-02050feb7ff94e8524ea62ad926aca63-6bf396da)
[docs/general-development/custom-word-breakers-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-word-breakers-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-word-breakers-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-3c8597167fa4f0e1f2272e2d16cfe8fc-6bf396da)
[docs/general-development/customizing-search-results-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/customizing-search-results-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/customizing-search-results-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-5cf813f17460fd8e0a7a4df3a05dee9b-6bf396da)
[docs/general-development/debugging-sharepoint-server-workflows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/debugging-sharepoint-server-workflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/debugging-sharepoint-server-workflows?branch=pr-en-us-8019) | [Details](#user-content-96ffc8bd5a75a8b244f7872363b74455-6bf396da)
[docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions?branch=pr-en-us-8019) | [Details](#user-content-379d3619bb07a36bc4f4c584c090bdef-6bf396da)
[docs/general-development/develop-access-web-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-access-web-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-access-web-apps?branch=pr-en-us-8019) | [Details](#user-content-64461401f599671e475b9b97d6e9edf2-6bf396da)
[docs/general-development/develop-the-site-design-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-the-site-design-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-the-site-design-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-a004d97bcf780578e842891c6c2cd816-6bf396da)
[docs/general-development/developing-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/developing-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/developing-with-duet-enterprise-2-0?branch=pr-en-us-8019) | [Details](#user-content-aa4383bb9c28c317259084f3004433aa-6bf396da)
[docs/general-development/discovery-in-excel-services-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/discovery-in-excel-services-rest-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/discovery-in-excel-services-rest-api?branch=pr-en-us-8019) | [Details](#user-content-7bff773da3f210276314936b2d170d77-6bf396da)
[docs/general-development/ediscovery-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/ediscovery-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/ediscovery-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-275d56f5d41a2471b55779ab15a87c13-6bf396da)
[docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-b96c1287c541f4809f84bc3841a0df59-6bf396da)
[docs/general-development/excel-services-alerts.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-alerts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-alerts?branch=pr-en-us-8019) | [Details](#user-content-e6cb9d2fccf86e3e8955c09ae2b5a4ef-6bf396da)
[docs/general-development/excel-services-architecture.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-architecture.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-architecture?branch=pr-en-us-8019) | [Details](#user-content-61203108cbe069b45aec040041bedc3f-6bf396da)
[docs/general-development/excel-services-best-practices.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-best-practices?branch=pr-en-us-8019) | [Details](#user-content-354f0fb298421eb5c71a6441c2b6454a-6bf396da)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8019) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-6bf396da)
[docs/general-development/excel-services-development-roadmap.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-development-roadmap.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-development-roadmap?branch=pr-en-us-8019) | [Details](#user-content-d085527ad02e03a00778d1d96f269a59-6bf396da)
[docs/general-development/excel-services-ecmascript-javascript-jscript.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-javascript-jscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-javascript-jscript?branch=pr-en-us-8019) | [Details](#user-content-d89c6d2162bb834977ee264d5f588fb2-6bf396da)
[docs/general-development/excel-services-ecmascript-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-overview?branch=pr-en-us-8019) | [Details](#user-content-b87142ae843e0d8934366bf588d3d889-6bf396da)
[docs/general-development/excel-services-known-issues-and-tips.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-known-issues-and [...]

2022-06-13 21:13 UTC, brittmsantos commented
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-20 09:49 UTC, andrewconnell approved these changes

2022-06-20 09:49 UTC, VesaJuvonen commented
Docs Build status updates of commit _[f0a0803](https://github.com/brittmsantos/sp-dev-docs/commits/f0a080392e50d1ba8f44342d91b1f579e37f8d36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-security-trimming-for-search-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-security-trimming-for-search-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-02050feb7ff94e8524ea62ad926aca63-96fb9dce)
[docs/general-development/custom-word-breakers-in-sharepoint-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/custom-word-breakers-in-sharepoint-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/custom-word-breakers-in-sharepoint-server?branch=pr-en-us-8019) | [Details](#user-content-3c8597167fa4f0e1f2272e2d16cfe8fc-96fb9dce)
[docs/general-development/customizing-search-results-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/customizing-search-results-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/customizing-search-results-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-5cf813f17460fd8e0a7a4df3a05dee9b-96fb9dce)
[docs/general-development/debugging-sharepoint-server-workflows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/debugging-sharepoint-server-workflows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/debugging-sharepoint-server-workflows?branch=pr-en-us-8019) | [Details](#user-content-96ffc8bd5a75a8b244f7872363b74455-96fb9dce)
[docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/deciding-between-sharepoint-add-ins-and-sharepoint-solutions?branch=pr-en-us-8019) | [Details](#user-content-379d3619bb07a36bc4f4c584c090bdef-96fb9dce)
[docs/general-development/develop-access-web-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-access-web-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-access-web-apps?branch=pr-en-us-8019) | [Details](#user-content-64461401f599671e475b9b97d6e9edf2-96fb9dce)
[docs/general-development/develop-the-site-design-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-the-site-design-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-the-site-design-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-a004d97bcf780578e842891c6c2cd816-96fb9dce)
[docs/general-development/developing-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/developing-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/developing-with-duet-enterprise-2-0?branch=pr-en-us-8019) | [Details](#user-content-aa4383bb9c28c317259084f3004433aa-96fb9dce)
[docs/general-development/discovery-in-excel-services-rest-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/discovery-in-excel-services-rest-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/discovery-in-excel-services-rest-api?branch=pr-en-us-8019) | [Details](#user-content-7bff773da3f210276314936b2d170d77-96fb9dce)
[docs/general-development/ediscovery-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/ediscovery-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/ediscovery-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-275d56f5d41a2471b55779ab15a87c13-96fb9dce)
[docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/enhancing-the-bdc-model-file-for-search-in-sharepoint?branch=pr-en-us-8019) | [Details](#user-content-b96c1287c541f4809f84bc3841a0df59-96fb9dce)
[docs/general-development/excel-services-alerts.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-alerts.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-alerts?branch=pr-en-us-8019) | [Details](#user-content-e6cb9d2fccf86e3e8955c09ae2b5a4ef-96fb9dce)
[docs/general-development/excel-services-architecture.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-architecture.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-architecture?branch=pr-en-us-8019) | [Details](#user-content-61203108cbe069b45aec040041bedc3f-96fb9dce)
[docs/general-development/excel-services-best-practices.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-best-practices.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-best-practices?branch=pr-en-us-8019) | [Details](#user-content-354f0fb298421eb5c71a6441c2b6454a-96fb9dce)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8019) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-96fb9dce)
[docs/general-development/excel-services-development-roadmap.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-development-roadmap.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-development-roadmap?branch=pr-en-us-8019) | [Details](#user-content-d085527ad02e03a00778d1d96f269a59-96fb9dce)
[docs/general-development/excel-services-ecmascript-javascript-jscript.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-javascript-jscript.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-javascript-jscript?branch=pr-en-us-8019) | [Details](#user-content-d89c6d2162bb834977ee264d5f588fb2-96fb9dce)
[docs/general-development/excel-services-ecmascript-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-ecmascript-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-ecmascript-overview?branch=pr-en-us-8019) | [Details](#user-content-b87142ae843e0d8934366bf588d3d889-96fb9dce)
[docs/general-development/excel-services-known-issues-and-tips.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-known-issues-and [...]

2022-06-20 10:10 UTC, merged