Validation: description-missing, disallowed-html-tag, docs-link-absolute, and image-alt-text-duplicated fixes.
SharePoint/sp-dev-docs pull request #8020
Opened 2022-06-04 18:11 UTC by brittmsantos

## Category

- [x] Content fix
- [ ] New article

## Related issues

no issue number - part of the Validation cleanup efforts.

## What's in this Pull Request?

This PR fixes 42 issues in 30 files.

2022-06-04 18:13 UTC, VesaJuvonen commented
Docs Build status updates of commit _[ec2c234](https://github.com/brittmsantos/sp-dev-docs/commits/ec2c2349b612bf6d053510b3f1fb6bcc4392637a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/get-started-with-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/get-started-with-business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/get-started-with-business-connectivity-services-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-8160a8ec7c2bf084f9643d3ac0f18fa3-fa5aaf76)
[docs/general-development/get-started-with-workflows-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/get-started-with-workflows-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/get-started-with-workflows-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-60abbb2264fe1f8d68b05fa35b266af4-fa5aaf76)
[docs/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer?branch=pr-en-us-8020) | [Details](#user-content-8360c32d8ae29febbe84abd6bf60f508-fa5aaf76)
[docs/general-development/getting-ranges-using-atom-feed-and-html-fragment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-ranges-using-atom-feed-and-html-fragment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-ranges-using-atom-feed-and-html-fragment?branch=pr-en-us-8020) | [Details](#user-content-67790238e43c519758f1254e6faffccc-fa5aaf76)
[docs/general-development/getting-started-with-excel-services.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-started-with-excel-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-started-with-excel-services?branch=pr-en-us-8020) | [Details](#user-content-c4c7e09e840055680367d279f378be02-fa5aaf76)
[docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-external-data-with-rest-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-c151225151aa9d9ec6ef5c86fd52d531-fa5aaf76)
[docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-ecc0742a0268ab172e450a3d6b210094-fa5aaf76)
[docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-security-trim-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-88b2f78ed8b1db2c3a3b82d67d8bdaa0-fa5aaf76)
[docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-c26380131bb79a7a6f7b9f573b0881a6-fa5aaf76)
[docs/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-7ef97907b4c472dafeb08130bb867658-fa5aaf76)
[docs/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-28bc607826f278b9d13560001dcefdff-fa5aaf76)
[docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using?branch=pr-en-us-8020) | [Details](#user-content-87cc15899fec1e53f919d7acae5fd734-fa5aaf76)
[docs/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor?branch=pr-en-us-8020) | [Details](#user-content-8adb80d2803723fdf0c200bd7837351f-fa5aaf76)
[docs/general-development/how-to-brand-snippets-by-using-css-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-brand-snippets-by-using-css-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-brand-snippets-by-using-css-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-e2495ddf52d193582058affbcf981577-fa5aaf76)
[docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-build-and-deploy-workflow-custom-actions?branch=pr-en-us-8020) | [Details](#user-content-1b82e1ed12a6dca0b9354e133dd160bc-fa5aaf76)
[docs/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res?branch=pr-en-us-8020) | [Details](#user-content-5b385b4489b60ef56cceec3538613f44-fa5aaf76)
[docs/general-development/how-to-change-the-preview-page-in-sharepoint-design-manager.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-change-the-preview-page-in [...]

2022-06-04 20:20 UTC, brittmsantos commented
@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-07 14:07 UTC, andrewconnell requested changes
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

2022-06-07 14:07 UTC, andrewconnell commented on docs/general-development/how-to-create-sharepoint-workflows-using-visual-studio.md
> +6. On the next page of the wizard, check the box to create an association, then select the **Announcements** list that we just created; select **&lt;Create New&gt;** for the required workflow history
Correct markdown escaping of angled brackets should be prefixed with`\`; don't change to the HTML encoding.

2022-06-07 17:28 UTC, VesaJuvonen commented
Docs Build status updates of commit _[46fd638](https://github.com/brittmsantos/sp-dev-docs/commits/46fd6386db5cb17936087360c6d826d92b7c397c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/get-started-with-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/get-started-with-business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/get-started-with-business-connectivity-services-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-8160a8ec7c2bf084f9643d3ac0f18fa3-c8ce0b40)
[docs/general-development/get-started-with-workflows-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/get-started-with-workflows-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/get-started-with-workflows-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-60abbb2264fe1f8d68b05fa35b266af4-c8ce0b40)
[docs/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer?branch=pr-en-us-8020) | [Details](#user-content-8360c32d8ae29febbe84abd6bf60f508-c8ce0b40)
[docs/general-development/getting-ranges-using-atom-feed-and-html-fragment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-ranges-using-atom-feed-and-html-fragment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-ranges-using-atom-feed-and-html-fragment?branch=pr-en-us-8020) | [Details](#user-content-67790238e43c519758f1254e6faffccc-c8ce0b40)
[docs/general-development/getting-started-with-excel-services.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-started-with-excel-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-started-with-excel-services?branch=pr-en-us-8020) | [Details](#user-content-c4c7e09e840055680367d279f378be02-c8ce0b40)
[docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-external-data-with-rest-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-c151225151aa9d9ec6ef5c86fd52d531-c8ce0b40)
[docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-ecc0742a0268ab172e450a3d6b210094-c8ce0b40)
[docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-security-trim-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-88b2f78ed8b1db2c3a3b82d67d8bdaa0-c8ce0b40)
[docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-c26380131bb79a7a6f7b9f573b0881a6-c8ce0b40)
[docs/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-7ef97907b4c472dafeb08130bb867658-c8ce0b40)
[docs/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-28bc607826f278b9d13560001dcefdff-c8ce0b40)
[docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using?branch=pr-en-us-8020) | [Details](#user-content-87cc15899fec1e53f919d7acae5fd734-c8ce0b40)
[docs/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor?branch=pr-en-us-8020) | [Details](#user-content-8adb80d2803723fdf0c200bd7837351f-c8ce0b40)
[docs/general-development/how-to-brand-snippets-by-using-css-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-brand-snippets-by-using-css-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-brand-snippets-by-using-css-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-e2495ddf52d193582058affbcf981577-c8ce0b40)
[docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-build-and-deploy-workflow-custom-actions?branch=pr-en-us-8020) | [Details](#user-content-1b82e1ed12a6dca0b9354e133dd160bc-c8ce0b40)
[docs/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res?branch=pr-en-us-8020) | [Details](#user-content-5b385b4489b60ef56cceec3538613f44-c8ce0b40)
[docs/general-development/how-to-change-the-preview-page-in-sharepoint-design-manager.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-change-the-preview-page-in [...]

2022-06-09 10:48 UTC, andrewconnell requested changes
None of the `ms.date` values reflect when the docs were updated... they all show September 2021 when the changes were this month. 

Thanks for the submission. In the future, when you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 10:53 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

Sets the date of these files not to the current date when they were changed (June 2022), rather backdated them, defeating the purposes of this property.

2022-06-09 20:25 UTC, VesaJuvonen commented
Docs Build status updates of commit _[d4530a4](https://github.com/brittmsantos/sp-dev-docs/commits/d4530a418bbe8b71ae258fc1db739fafddecb629)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/get-started-with-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/get-started-with-business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/get-started-with-business-connectivity-services-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-8160a8ec7c2bf084f9643d3ac0f18fa3-9a813bc8)
[docs/general-development/get-started-with-workflows-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/get-started-with-workflows-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/get-started-with-workflows-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-60abbb2264fe1f8d68b05fa35b266af4-9a813bc8)
[docs/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-familiar-with-visual-designer-for-workflow-in-sharepoint-designer?branch=pr-en-us-8020) | [Details](#user-content-8360c32d8ae29febbe84abd6bf60f508-9a813bc8)
[docs/general-development/getting-ranges-using-atom-feed-and-html-fragment.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-ranges-using-atom-feed-and-html-fragment.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-ranges-using-atom-feed-and-html-fragment?branch=pr-en-us-8020) | [Details](#user-content-67790238e43c519758f1254e6faffccc-9a813bc8)
[docs/general-development/getting-started-with-excel-services.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/getting-started-with-excel-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/getting-started-with-excel-services?branch=pr-en-us-8020) | [Details](#user-content-c4c7e09e840055680367d279f378be02-9a813bc8)
[docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-access-external-data-with-rest-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-access-external-data-with-rest-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-c151225151aa9d9ec6ef5c86fd52d531-9a813bc8)
[docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-device-channel-panel-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-ecc0742a0268ab172e450a3d6b210094-9a813bc8)
[docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-security-trim-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-security-trim-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-88b2f78ed8b1db2c3a3b82d67d8bdaa0-9a813bc8)
[docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-web-part-zone-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-c26380131bb79a7a6f7b9f573b0881a6-9a813bc8)
[docs/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-an-edit-mode-panel-snippet-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-7ef97907b4c472dafeb08130bb867658-9a813bc8)
[docs/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-apply-a-master-page-to-a-site-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-28bc607826f278b9d13560001dcefdff-9a813bc8)
[docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-back-up-and-restore-a-search-service-application-in-sharepoint-using?branch=pr-en-us-8020) | [Details](#user-content-87cc15899fec1e53f919d7acae5fd734-9a813bc8)
[docs/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-back-up-and-restore-sharepoint-using-a-vss-requestor?branch=pr-en-us-8020) | [Details](#user-content-8adb80d2803723fdf0c200bd7837351f-9a813bc8)
[docs/general-development/how-to-brand-snippets-by-using-css-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-brand-snippets-by-using-css-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-brand-snippets-by-using-css-in-sharepoint?branch=pr-en-us-8020) | [Details](#user-content-e2495ddf52d193582058affbcf981577-9a813bc8)
[docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-build-and-deploy-workflow-custom-actions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-build-and-deploy-workflow-custom-actions?branch=pr-en-us-8020) | [Details](#user-content-1b82e1ed12a6dca0b9354e133dd160bc-9a813bc8)
[docs/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-build-search-driven-mobile-apps-with-the-navigation-and-event-logging-res?branch=pr-en-us-8020) | [Details](#user-content-5b385b4489b60ef56cceec3538613f44-9a813bc8)
[docs/general-development/how-to-change-the-preview-page-in-sharepoint-design-manager.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-change-the-preview-page-in [...]

2022-06-09 20:59 UTC, brittmsantos commented
@andrewconnell 

I've implemented the requested changes regarding ms.date. Please let me know if there are any other issues preventing approval and merge. Thanks!

2022-06-09 20:59 UTC, brittmsantos commented
@andrewconnell 

I've implemented the requested changes regarding ms.date. Please let me know if there are any other issues preventing approval and merge. Thanks!

2022-06-13 21:13 UTC, brittmsantos commented
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-20 10:10 UTC, merged