Validation: description-missing, disallowed-html-tag, docs-links-absolute, and image-alt-text-duplicated fixes.
SharePoint/sp-dev-docs pull request #8021
Opened 2022-06-04 20:14 UTC by brittmsantos

## Category

- [x] Content fix
- [ ] New article

## Related issues

no issue number - part of the Validation cleanup efforts.

## What's in this Pull Request?

This PR fixes 33 issues in 30 files.

2022-06-04 20:15 UTC, VesaJuvonen commented
Docs Build status updates of commit _[6898b14](https://github.com/brittmsantos/sp-dev-docs/commits/6898b143bc73db0e70cfb42444066510726a4ddb)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8021) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-3c2567e8)
[docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s?branch=pr-en-us-8021) | [Details](#user-content-b9c8091b1008dbe75d33f31a6ec0035d-3c2567e8)
[docs/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery?branch=pr-en-us-8021) | [Details](#user-content-578fc4884b6faef82877c9998eae1536-3c2567e8)
[docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in?branch=pr-en-us-8021) | [Details](#user-content-257bd799c748f9f8e9b83770bbcab44a-3c2567e8)
[docs/general-development/how-to-save-from-excel-client-to-the-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-save-from-excel-client-to-the-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-save-from-excel-client-to-the-server?branch=pr-en-us-8021) | [Details](#user-content-f040158dcd4a70b03153cf17911d771a-3c2567e8)
[docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-ad521aa17c9db371c19e35c51dbf707b-3c2567e8)
[docs/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-70f06371d2e5eac201be9bbaa601695f-3c2567e8)
[docs/general-development/how-to-trust-a-location.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-trust-a-location.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-trust-a-location?branch=pr-en-us-8021) | [Details](#user-content-fc4c592134c213bae189cafbe4a6c36c-3c2567e8)
[docs/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0?branch=pr-en-us-8021) | [Details](#user-content-e3918fc2183e97a57650e87b0a977d82-3c2567e8)
[docs/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0?branch=pr-en-us-8021) | [Details](#user-content-3b4b8167fd2f6c133416da36e3040bc2-3c2567e8)
[docs/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-09a4af70379acad3c4221d7563fe1d3c-3c2567e8)
[docs/general-development/incoming-claims-signing-into-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/incoming-claims-signing-into-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/incoming-claims-signing-into-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-eb2f685d63aac9b95e45808f5f2948ec-3c2567e8)
[docs/general-development/integrating-location-and-map-functionality-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/integrating-location-and-map-functionality-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/integrating-location-and-map-functionality-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-c719cb85e6f24bb3c32cc75cac2cd423-3c2567e8)
[docs/general-development/javascript-user-defined-functions-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/javascript-user-defined-functions-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/javascript-user-defined-functions-overview?branch=pr-en-us-8021) | [Details](#user-content-b377c461a834506c8eb2d228d1c734fa-3c2567e8)
[docs/general-development/keyword-query-language-kql-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/keyword-query-language-kql-syntax-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference?branch=pr-en-us-8021) | [Details](#user-content-51543f2c52ce877de128dcdc6d947713-3c2567e8)
[docs/general-development/language-support-for-windows-phone-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/language-support-for-windows-phone-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/language-support-for-windows-phone-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-eb6144449def4779afb7395b4fc08897-3c2567e8)
[docs/general-development/loop-back-soap-calls-and-direct-linking.md](https://github.com/ShareP [...]

2022-06-04 20:20 UTC, brittmsantos commented
@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-06 14:43 UTC, dereklh7 commented on docs/general-development/office-documentation-copyright-notice.md
> +description: Provides a copyright notice for Office 2013 documentation.
Too short per https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-seo-meta-description?branch=main. I understand there isn't too much content in the file, but I think there's enough to get to 100 characters here.

2022-06-06 15:00 UTC, VesaJuvonen commented
Docs Build status updates of commit _[788e732](https://github.com/brittmsantos/sp-dev-docs/commits/788e73208010f16b7b20bdcf0be463be8e983024)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8021) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-c562bceb)
[docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s?branch=pr-en-us-8021) | [Details](#user-content-b9c8091b1008dbe75d33f31a6ec0035d-c562bceb)
[docs/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery?branch=pr-en-us-8021) | [Details](#user-content-578fc4884b6faef82877c9998eae1536-c562bceb)
[docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in?branch=pr-en-us-8021) | [Details](#user-content-257bd799c748f9f8e9b83770bbcab44a-c562bceb)
[docs/general-development/how-to-save-from-excel-client-to-the-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-save-from-excel-client-to-the-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-save-from-excel-client-to-the-server?branch=pr-en-us-8021) | [Details](#user-content-f040158dcd4a70b03153cf17911d771a-c562bceb)
[docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-ad521aa17c9db371c19e35c51dbf707b-c562bceb)
[docs/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-70f06371d2e5eac201be9bbaa601695f-c562bceb)
[docs/general-development/how-to-trust-a-location.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-trust-a-location.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-trust-a-location?branch=pr-en-us-8021) | [Details](#user-content-fc4c592134c213bae189cafbe4a6c36c-c562bceb)
[docs/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0?branch=pr-en-us-8021) | [Details](#user-content-e3918fc2183e97a57650e87b0a977d82-c562bceb)
[docs/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0?branch=pr-en-us-8021) | [Details](#user-content-3b4b8167fd2f6c133416da36e3040bc2-c562bceb)
[docs/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-09a4af70379acad3c4221d7563fe1d3c-c562bceb)
[docs/general-development/incoming-claims-signing-into-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/incoming-claims-signing-into-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/incoming-claims-signing-into-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-eb2f685d63aac9b95e45808f5f2948ec-c562bceb)
[docs/general-development/integrating-location-and-map-functionality-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/integrating-location-and-map-functionality-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/integrating-location-and-map-functionality-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-c719cb85e6f24bb3c32cc75cac2cd423-c562bceb)
[docs/general-development/javascript-user-defined-functions-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/javascript-user-defined-functions-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/javascript-user-defined-functions-overview?branch=pr-en-us-8021) | [Details](#user-content-b377c461a834506c8eb2d228d1c734fa-c562bceb)
[docs/general-development/keyword-query-language-kql-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/keyword-query-language-kql-syntax-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference?branch=pr-en-us-8021) | [Details](#user-content-51543f2c52ce877de128dcdc6d947713-c562bceb)
[docs/general-development/language-support-for-windows-phone-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/language-support-for-windows-phone-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/language-support-for-windows-phone-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-eb6144449def4779afb7395b4fc08897-c562bceb)
[docs/general-development/loop-back-soap-calls-and-direct-linking.md](https://github.com/ShareP [...]

2022-06-07 16:17 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8bdef8d](https://github.com/brittmsantos/sp-dev-docs/commits/8bdef8dfb0bfc6a4bb58b53bcbcc557956c3e3f1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8021) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-7ab283d3)
[docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-learn-to-read-and-write-to-the-social-feed-by-using-the-rest-service-in-s?branch=pr-en-us-8021) | [Details](#user-content-b9c8091b1008dbe75d33f31a6ec0035d-7ab283d3)
[docs/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-map-a-network-drive-to-the-sharepoint-master-page-gallery?branch=pr-en-us-8021) | [Details](#user-content-578fc4884b6faef82877c9998eae1536-7ab283d3)
[docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-retrieve-user-profile-properties-by-using-the-net-client-object-model-in?branch=pr-en-us-8021) | [Details](#user-content-257bd799c748f9f8e9b83770bbcab44a-7ab283d3)
[docs/general-development/how-to-save-from-excel-client-to-the-server.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-save-from-excel-client-to-the-server.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-save-from-excel-client-to-the-server?branch=pr-en-us-8021) | [Details](#user-content-f040158dcd4a70b03153cf17911d771a-7ab283d3)
[docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-the-bing-maps-key-at-the-web-and-farm-level-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-ad521aa17c9db371c19e35c51dbf707b-7ab283d3)
[docs/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-set-up-an-environment-for-developing-mobile-apps-for-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-70f06371d2e5eac201be9bbaa601695f-7ab283d3)
[docs/general-development/how-to-trust-a-location.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-trust-a-location.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-trust-a-location?branch=pr-en-us-8021) | [Details](#user-content-fc4c592134c213bae189cafbe4a6c36c-7ab283d3)
[docs/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-sap-reporting-with-duet-enterprise-2-0?branch=pr-en-us-8021) | [Details](#user-content-e3918fc2183e97a57650e87b0a977d82-7ab283d3)
[docs/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-sap-workflow-with-duet-enterprise-2-0?branch=pr-en-us-8021) | [Details](#user-content-3b4b8167fd2f6c133416da36e3040bc2-7ab283d3)
[docs/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-use-the-client-code-library-to-access-external-data-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-09a4af70379acad3c4221d7563fe1d3c-7ab283d3)
[docs/general-development/incoming-claims-signing-into-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/incoming-claims-signing-into-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/incoming-claims-signing-into-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-eb2f685d63aac9b95e45808f5f2948ec-7ab283d3)
[docs/general-development/integrating-location-and-map-functionality-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/integrating-location-and-map-functionality-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/integrating-location-and-map-functionality-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-c719cb85e6f24bb3c32cc75cac2cd423-7ab283d3)
[docs/general-development/javascript-user-defined-functions-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/javascript-user-defined-functions-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/javascript-user-defined-functions-overview?branch=pr-en-us-8021) | [Details](#user-content-b377c461a834506c8eb2d228d1c734fa-7ab283d3)
[docs/general-development/keyword-query-language-kql-syntax-reference.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/keyword-query-language-kql-syntax-reference.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/keyword-query-language-kql-syntax-reference?branch=pr-en-us-8021) | [Details](#user-content-51543f2c52ce877de128dcdc6d947713-7ab283d3)
[docs/general-development/language-support-for-windows-phone-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/language-support-for-windows-phone-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/language-support-for-windows-phone-in-sharepoint?branch=pr-en-us-8021) | [Details](#user-content-eb6144449def4779afb7395b4fc08897-7ab283d3)
[docs/general-development/loop-back-soap-calls-and-direct-linking.md](https://github.com/ShareP [...]

2022-06-09 10:46 UTC, andrewconnell requested changes
None of the `ms.date` changes are correct... they all refer to September 2021, not the date the files are being changed (June 2022).

Thanks for the submission. In the future, when you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-14 18:27 UTC, brittmsantos commented
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-20 10:10 UTC, merged