Validation: Fix multiple issues
SharePoint/sp-dev-docs pull request #8034
Opened 2022-06-06 17:40 UTC by annmariehitchcock

## Category

- [ ] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

> **DELETE THIS LINE BEFORE SUBMITTING** | *For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.*

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?

> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in this PR. Sample description or details around bugs which are being fixed.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `master` branch of this repo. Released documents are in `live` branch.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

2022-06-06 17:42 UTC, VesaJuvonen commented
Docs Build status updates of commit _[7971dbd](https://github.com/annmariehitchcock/sp-dev-docs/commits/7971dbd14331b5b7b5ea8895e2b2f2d04c0b660e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/basic-uri-structure-and-path?branch=pr-en-us-8034) | [Details](#user-content-95a5aceb9ba91367322012b2b24efd39-8eab0de5)
[docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-client-object-model-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-c4db1b1ab76ddf71d76c9542bdcc273e-8eab0de5)
[docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-rest-api-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-8c1642d0b73e0d90c8dfcee65105846d-8eab0de5)
[docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-farm-solutions-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d0bcc56c8bf9b560bbba5bfd7c2c0d8f-8eab0de5)

<a id="95a5aceb9ba91367322012b2b24efd39-8eab0de5"></a>
### [docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 63, Column 93**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'ServerName' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 72, Column 40**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'ServerName' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 120, Column 90**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'ServerName' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="c4db1b1ab76ddf71d76c9542bdcc273e-8eab0de5"></a>
### [docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 484, Column 15**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'Method' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="8c1642d0b73e0d90c8dfcee65105846d-8eab0de5"></a>
### [docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="d0bcc56c8bf9b560bbba5bfd7c2c0d8f-8eab0de5"></a>
### [docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206061740553631-8034/BuildReport?accessString=6697dd6dd06859e4eff6b659f137a4913e0c7a3147d47b975e550610b2dea294).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 18:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[86b0d2f](https://github.com/annmariehitchcock/sp-dev-docs/commits/86b0d2fe7cdd78cc9356676025d06a6a0beae09f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/basic-uri-structure-and-path?branch=pr-en-us-8034) | [Details](#user-content-95a5aceb9ba91367322012b2b24efd39-fbf82deb)
[docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-client-object-model-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-c4db1b1ab76ddf71d76c9542bdcc273e-fbf82deb)
[docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-rest-api-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-8c1642d0b73e0d90c8dfcee65105846d-fbf82deb)
[docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-farm-solutions-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d0bcc56c8bf9b560bbba5bfd7c2c0d8f-fbf82deb)
[docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates?branch=pr-en-us-8034) | [Details](#user-content-4b67576b6628d4d1187c9a194ab1ffb8-fbf82deb)
[docs/general-development/build-reusable-components-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-reusable-components-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-reusable-components-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-a798c55d175fb22b64e051b77fe31926-fbf82deb)
[docs/general-development/building-search-queries-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/building-search-queries-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/building-search-queries-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-f3fe17398f1f6f6e73efd18b655bd87a-fbf82deb)

<a id="95a5aceb9ba91367322012b2b24efd39-fbf82deb"></a>
### [docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="c4db1b1ab76ddf71d76c9542bdcc273e-fbf82deb"></a>
### [docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="8c1642d0b73e0d90c8dfcee65105846d-fbf82deb"></a>
### [docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="d0bcc56c8bf9b560bbba5bfd7c2c0d8f-fbf82deb"></a>
### [docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="4b67576b6628d4d1187c9a194ab1ffb8-fbf82deb"></a>
### [docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a798c55d175fb22b64e051b77fe31926-fbf82deb"></a>
### [docs/general-development/build-reusable-components-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-reusable-components-for-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="f3fe17398f1f6f6e73efd18b655bd87a-fbf82deb"></a>
### [docs/general-development/building-search-queries-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/building-search-queries-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206061840194663-8034/BuildReport?accessString=eb1bd412b4b03ed95f2a5fcdda674a1aca84a93e62b0ed44078db5f8c72f2580).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troublesh [...]

2022-06-06 19:25 UTC, VesaJuvonen commented
Docs Build status updates of commit _[48dfb79](https://github.com/annmariehitchcock/sp-dev-docs/commits/48dfb797b4b4fea73eca418f0371b754a49e5ba2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/basic-uri-structure-and-path?branch=pr-en-us-8034) | [Details](#user-content-95a5aceb9ba91367322012b2b24efd39-6f76b65d)
[docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-client-object-model-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-c4db1b1ab76ddf71d76c9542bdcc273e-6f76b65d)
[docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-rest-api-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-8c1642d0b73e0d90c8dfcee65105846d-6f76b65d)
[docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-farm-solutions-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d0bcc56c8bf9b560bbba5bfd7c2c0d8f-6f76b65d)
[docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates?branch=pr-en-us-8034) | [Details](#user-content-4b67576b6628d4d1187c9a194ab1ffb8-6f76b65d)
[docs/general-development/build-reusable-components-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-reusable-components-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-reusable-components-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-a798c55d175fb22b64e051b77fe31926-6f76b65d)
[docs/general-development/build-sites-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-sites-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-sites-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-fbed1b6fa2f2dc30890a71b6b7123228-6f76b65d)
[docs/general-development/building-search-queries-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/building-search-queries-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/building-search-queries-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-f3fe17398f1f6f6e73efd18b655bd87a-6f76b65d)
[docs/general-development/business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-9e9fba951cec5b1d1ed1b0afbbf85f13-6f76b65d)
[docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-programmers-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-54780469cc65715b48c2aa1b96a9fbad-6f76b65d)
[docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/choose-the-right-api-set-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-0e65f22883585a8896c44dce051dc71e-6f76b65d)
[docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-and-concepts-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-0c33ae566a62cfe10618bcd0889e479c-6f76b65d)
[docs/general-development/claims-based-identity-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d6a709306162a93350d42264d4c0e37c-6f76b65d)
[docs/general-development/claims-based-identity-term-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-term-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-term-definitions?branch=pr-en-us-8034) | [Details](#user-content-9ec33dea4fc32a77fd5f256a505a3cd9-6f76b65d)
[docs/general-development/claims-provider-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-provider-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-provider-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-57749caa294f66a6f6752c28a1f3dd8d-6f76b65d)
[docs/general-development/configuration-administration-and-resources-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configuration-administration-and-resources-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configuration-administration-and-resources-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-232b2d39215826132479cf6fe987f0cb-6f76b65d)
[docs/general-development/configure-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configure-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configure-search-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-e79ef0fe9536ce916d1d7c78a36b4501-6f76b65d)

<a id="95a5aceb9ba91367322012b2b24efd39-6f76b65d"></a>
### [docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/co [...]

2022-06-06 19:57 UTC, VesaJuvonen commented
Docs Build status updates of commit _[4f4dfc4](https://github.com/annmariehitchcock/sp-dev-docs/commits/4f4dfc4e6e64ffe44b3ee3bd39db33fb664b9c56)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/basic-uri-structure-and-path?branch=pr-en-us-8034) | [Details](#user-content-95a5aceb9ba91367322012b2b24efd39-01a327f2)
[docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-client-object-model-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-c4db1b1ab76ddf71d76c9542bdcc273e-01a327f2)
[docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-rest-api-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-8c1642d0b73e0d90c8dfcee65105846d-01a327f2)
[docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-farm-solutions-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d0bcc56c8bf9b560bbba5bfd7c2c0d8f-01a327f2)
[docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates?branch=pr-en-us-8034) | [Details](#user-content-4b67576b6628d4d1187c9a194ab1ffb8-01a327f2)
[docs/general-development/build-reusable-components-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-reusable-components-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-reusable-components-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-a798c55d175fb22b64e051b77fe31926-01a327f2)
[docs/general-development/build-sites-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-sites-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-sites-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-fbed1b6fa2f2dc30890a71b6b7123228-01a327f2)
[docs/general-development/building-search-queries-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/building-search-queries-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/building-search-queries-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-f3fe17398f1f6f6e73efd18b655bd87a-01a327f2)
[docs/general-development/business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-9e9fba951cec5b1d1ed1b0afbbf85f13-01a327f2)
[docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-programmers-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-54780469cc65715b48c2aa1b96a9fbad-01a327f2)
[docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/choose-the-right-api-set-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-0e65f22883585a8896c44dce051dc71e-01a327f2)
[docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-and-concepts-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-0c33ae566a62cfe10618bcd0889e479c-01a327f2)
[docs/general-development/claims-based-identity-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d6a709306162a93350d42264d4c0e37c-01a327f2)
[docs/general-development/claims-based-identity-term-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-term-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-term-definitions?branch=pr-en-us-8034) | [Details](#user-content-9ec33dea4fc32a77fd5f256a505a3cd9-01a327f2)
[docs/general-development/claims-provider-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-provider-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-provider-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-57749caa294f66a6f6752c28a1f3dd8d-01a327f2)
[docs/general-development/configuration-administration-and-resources-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configuration-administration-and-resources-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configuration-administration-and-resources-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-232b2d39215826132479cf6fe987f0cb-01a327f2)
[docs/general-development/configure-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configure-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configure-search-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-e79ef0fe9536ce916d1d7c78a36b4501-01a327f2)
[docs/general-development/content-management-interoperability-services-cmis-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/content-management-interoperability-services-cmis-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/content [...]

2022-06-06 20:13 UTC, MeeraDi commented on docs/general-development/bcs-rest-api-reference-for-sharepoint.md
> +description: Reference for constructing Representational State Transfer (REST) URLs using Business Connectivity SErvices (BCS) in SharePoint.
Business Connectivity Services

2022-06-06 20:18 UTC, MeeraDi commented on docs/general-development/custom-content-processing-with-the-content-enrichment-web-service-callout.md
> +description: This is an article to learn about custom content processing with the Content Enrichment web service callout
service callout.

2022-06-06 20:34 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a268a2e](https://github.com/annmariehitchcock/sp-dev-docs/commits/a268a2e258e46a1dc2368637464385a23bd9f609)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/basic-uri-structure-and-path?branch=pr-en-us-8034) | [Details](#user-content-95a5aceb9ba91367322012b2b24efd39-796fd110)
[docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-client-object-model-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-c4db1b1ab76ddf71d76c9542bdcc273e-796fd110)
[docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-rest-api-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-8c1642d0b73e0d90c8dfcee65105846d-796fd110)
[docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-farm-solutions-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d0bcc56c8bf9b560bbba5bfd7c2c0d8f-796fd110)
[docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates?branch=pr-en-us-8034) | [Details](#user-content-4b67576b6628d4d1187c9a194ab1ffb8-796fd110)
[docs/general-development/build-reusable-components-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-reusable-components-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-reusable-components-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-a798c55d175fb22b64e051b77fe31926-796fd110)
[docs/general-development/build-sites-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-sites-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-sites-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-fbed1b6fa2f2dc30890a71b6b7123228-796fd110)
[docs/general-development/building-search-queries-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/building-search-queries-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/building-search-queries-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-f3fe17398f1f6f6e73efd18b655bd87a-796fd110)
[docs/general-development/business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-9e9fba951cec5b1d1ed1b0afbbf85f13-796fd110)
[docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-programmers-reference-for-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-54780469cc65715b48c2aa1b96a9fbad-796fd110)
[docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/choose-the-right-api-set-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-0e65f22883585a8896c44dce051dc71e-796fd110)
[docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-and-concepts-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-0c33ae566a62cfe10618bcd0889e479c-796fd110)
[docs/general-development/claims-based-identity-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-d6a709306162a93350d42264d4c0e37c-796fd110)
[docs/general-development/claims-based-identity-term-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-term-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-term-definitions?branch=pr-en-us-8034) | [Details](#user-content-9ec33dea4fc32a77fd5f256a505a3cd9-796fd110)
[docs/general-development/claims-provider-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-provider-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-provider-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-57749caa294f66a6f6752c28a1f3dd8d-796fd110)
[docs/general-development/configuration-administration-and-resources-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configuration-administration-and-resources-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configuration-administration-and-resources-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-232b2d39215826132479cf6fe987f0cb-796fd110)
[docs/general-development/configure-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configure-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configure-search-in-sharepoint?branch=pr-en-us-8034) | [Details](#user-content-e79ef0fe9536ce916d1d7c78a36b4501-796fd110)
[docs/general-development/content-management-interoperability-services-cmis-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/content-management-interoperability-services-cmis-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/content [...]

2022-06-06 20:39 UTC, annmariehitchcock commented
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-06 20:41 UTC, annmariehitchcock commented
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-07 14:00 UTC, andrewconnell requested changes
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

2022-06-07 16:08 UTC, annmariehitchcock commented
Updated ms.date as requested. Thank you.

2022-06-09 10:41 UTC, andrewconnell approved these changes

2022-06-09 10:43 UTC, andrewconnell commented
Thank you... in the future, please follow the instructions in PR template, explaining what the PR addresses.

2022-06-09 10:54 UTC, merged