BULK VALIDATION missing description, alt text, etc
SharePoint/sp-dev-docs pull request #8037
Opened 2022-06-06 19:59 UTC by mSarts

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

BULK Validation updates.

2022-06-06 20:12 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a5e5f68](https://github.com/mSarts/sp-dev-docs/commits/a5e5f6895f37962ff336211f44ddfb6c4230befd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/upgrade-site-customizations-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/upgrade-site-customizations-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/upgrade-site-customizations-for-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-71e954576587a0e11a2e0d5109a151d8-80508e99)
[docs/general-development/upgrade-web-templates-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/upgrade-web-templates-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/upgrade-web-templates-for-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-8c7fad8a57dac948c2b6e3d88943722c-80508e99)
[docs/general-development/urls-and-tokens-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/urls-and-tokens-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/urls-and-tokens-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-0695a62e5f338e575435f730e9601688-80508e99)
[docs/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-52a8f4c795b7a86a7e66e832d49c0c55-80508e99)
[docs/general-development/using-odata-with-excel-services-rest-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/using-odata-with-excel-services-rest-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/using-odata-with-excel-services-rest-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-b93a0ef5238cb98bdb247c6139b892a0-80508e99)
[docs/general-development/using-the-pairing-cmdlet-register-spworkflowservice.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/using-the-pairing-cmdlet-register-spworkflowservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/using-the-pairing-cmdlet-register-spworkflowservice?branch=pr-en-us-8037) | [Details](#user-content-8b825e817146f4474802d39208374b59-80508e99)
[docs/general-development/validation-issues-in-visio-sharepoint-2010-workflow-platform.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/validation-issues-in-visio-sharepoint-2010-workflow-platform.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/validation-issues-in-visio-sharepoint-2010-workflow-platform?branch=pr-en-us-8037) | [Details](#user-content-782937a2b4f0ff1f60950aaaa16c9018-80508e99)
[docs/general-development/visio-shapes-in-sharepoint-designer-a-quick-reference-guide-sharepoint-2010.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/visio-shapes-in-sharepoint-designer-a-quick-reference-guide-sharepoint-2010.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/visio-shapes-in-sharepoint-designer-a-quick-reference-guide-sharepoint-2010?branch=pr-en-us-8037) | [Details](#user-content-640f21d0f350540b6adfcb07a166537d-80508e99)
[docs/general-development/vss-requestors-and-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/vss-requestors-and-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/vss-requestors-and-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-abf8c2c5aaed303f7432c257bb52da97-80508e99)
[docs/general-development/walkthrough-developing-a-custom-application-using-excel-web-services.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/walkthrough-developing-a-custom-application-using-excel-web-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/walkthrough-developing-a-custom-application-using-excel-web-services?branch=pr-en-us-8037) | [Details](#user-content-40508deef55eca206de36a2a6dcc3fd2-80508e99)
[docs/general-development/walkthrough-developing-a-managed-code-udf.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/walkthrough-developing-a-managed-code-udf.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/walkthrough-developing-a-managed-code-udf?branch=pr-en-us-8037) | [Details](#user-content-00db38684e9db8638fae73d2b7f2ca84-80508e99)
[docs/general-development/walkthrough-developing-using-the-content-editor-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/walkthrough-developing-using-the-content-editor-web-part.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/walkthrough-developing-using-the-content-editor-web-part?branch=pr-en-us-8037) | [Details](#user-content-84430f04f0bf70d80b4dc498452963c9-80508e99)
[docs/general-development/what-s-changed-in-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-changed-in-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-changed-in-sharepoint-designer?branch=pr-en-us-8037) | [Details](#user-content-b29ebd6be1a9658e97ad5abf49491077-80508e99)
[docs/general-development/what-s-new-in-access.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-access.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-access?branch=pr-en-us-8037) | [Details](#user-content-63b1f4da8b93312cd940731a123ab6b5-80508e99)
[docs/general-development/what-s-new-in-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-business-connectivity-services-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-7c86fc21a832a821d9d0724881466e7b-80508e99)
[docs/general-development/what-s-new-in-excel-web-services.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-excel-web-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-excel-web-services?branch=pr-en-us-8037) | [Details](#user-content-a1d42941f856f6ec4cb228b92f33b600-80508e99)
[docs/general-development/what-s-new-in-sharepoint-ediscovery-and-compliance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-sharepoint-ediscovery-and-compliance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-sharepoint-ediscovery-and-compliance?branch=pr-en-us-8037) | [Details](#user-content-6df7499143360399e8a9cbfef73bdc12-80508e99)
[docs/general-development/what-s-new-in-sharepoint-search-for-developers.md](https://github.com/ [...]

2022-06-06 20:21 UTC, mSarts commented
**Global effort to fix build validation errors**

@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-07 14:01 UTC, andrewconnell requested changes
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

2022-06-07 15:48 UTC, VesaJuvonen commented
Docs Build status updates of commit _[9dcccd8](https://github.com/mSarts/sp-dev-docs/commits/9dcccd85e12809511bca6914110d27ffde063610)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/upgrade-site-customizations-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/upgrade-site-customizations-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/upgrade-site-customizations-for-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-71e954576587a0e11a2e0d5109a151d8-1fb92005)
[docs/general-development/upgrade-web-templates-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/upgrade-web-templates-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/upgrade-web-templates-for-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-8c7fad8a57dac948c2b6e3d88943722c-1fb92005)
[docs/general-development/urls-and-tokens-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/urls-and-tokens-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/urls-and-tokens-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-0695a62e5f338e575435f730e9601688-1fb92005)
[docs/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/using-odata-sources-with-business-connectivity-services-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-52a8f4c795b7a86a7e66e832d49c0c55-1fb92005)
[docs/general-development/using-odata-with-excel-services-rest-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/using-odata-with-excel-services-rest-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/using-odata-with-excel-services-rest-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-b93a0ef5238cb98bdb247c6139b892a0-1fb92005)
[docs/general-development/using-the-pairing-cmdlet-register-spworkflowservice.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/using-the-pairing-cmdlet-register-spworkflowservice.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/using-the-pairing-cmdlet-register-spworkflowservice?branch=pr-en-us-8037) | [Details](#user-content-8b825e817146f4474802d39208374b59-1fb92005)
[docs/general-development/validation-issues-in-visio-sharepoint-2010-workflow-platform.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/validation-issues-in-visio-sharepoint-2010-workflow-platform.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/validation-issues-in-visio-sharepoint-2010-workflow-platform?branch=pr-en-us-8037) | [Details](#user-content-782937a2b4f0ff1f60950aaaa16c9018-1fb92005)
[docs/general-development/visio-shapes-in-sharepoint-designer-a-quick-reference-guide-sharepoint-2010.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/visio-shapes-in-sharepoint-designer-a-quick-reference-guide-sharepoint-2010.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/visio-shapes-in-sharepoint-designer-a-quick-reference-guide-sharepoint-2010?branch=pr-en-us-8037) | [Details](#user-content-640f21d0f350540b6adfcb07a166537d-1fb92005)
[docs/general-development/vss-requestors-and-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/vss-requestors-and-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/vss-requestors-and-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-abf8c2c5aaed303f7432c257bb52da97-1fb92005)
[docs/general-development/walkthrough-developing-a-custom-application-using-excel-web-services.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/walkthrough-developing-a-custom-application-using-excel-web-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/walkthrough-developing-a-custom-application-using-excel-web-services?branch=pr-en-us-8037) | [Details](#user-content-40508deef55eca206de36a2a6dcc3fd2-1fb92005)
[docs/general-development/walkthrough-developing-a-managed-code-udf.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/walkthrough-developing-a-managed-code-udf.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/walkthrough-developing-a-managed-code-udf?branch=pr-en-us-8037) | [Details](#user-content-00db38684e9db8638fae73d2b7f2ca84-1fb92005)
[docs/general-development/walkthrough-developing-using-the-content-editor-web-part.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/walkthrough-developing-using-the-content-editor-web-part.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/walkthrough-developing-using-the-content-editor-web-part?branch=pr-en-us-8037) | [Details](#user-content-84430f04f0bf70d80b4dc498452963c9-1fb92005)
[docs/general-development/what-s-changed-in-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-changed-in-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-changed-in-sharepoint-designer?branch=pr-en-us-8037) | [Details](#user-content-b29ebd6be1a9658e97ad5abf49491077-1fb92005)
[docs/general-development/what-s-new-in-access.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-access.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-access?branch=pr-en-us-8037) | [Details](#user-content-63b1f4da8b93312cd940731a123ab6b5-1fb92005)
[docs/general-development/what-s-new-in-business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-business-connectivity-services-in-sharepoint?branch=pr-en-us-8037) | [Details](#user-content-7c86fc21a832a821d9d0724881466e7b-1fb92005)
[docs/general-development/what-s-new-in-excel-web-services.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-excel-web-services.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-excel-web-services?branch=pr-en-us-8037) | [Details](#user-content-a1d42941f856f6ec4cb228b92f33b600-1fb92005)
[docs/general-development/what-s-new-in-sharepoint-ediscovery-and-compliance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/what-s-new-in-sharepoint-ediscovery-and-compliance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/what-s-new-in-sharepoint-ediscovery-and-compliance?branch=pr-en-us-8037) | [Details](#user-content-6df7499143360399e8a9cbfef73bdc12-1fb92005)
[docs/general-development/what-s-new-in-sharepoint-search-for-developers.md](https://github.com/ [...]

2022-06-09 10:39 UTC, andrewconnell approved these changes

2022-06-09 10:54 UTC, merged