BULK VALIDATION various fixes
SharePoint/sp-dev-docs pull request #8038
Opened 2022-06-06 20:46 UTC by mSarts

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

BULK Validation issues.

2022-06-06 20:47 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1e31ea6](https://github.com/mSarts/sp-dev-docs/commits/1e31ea675e35e0b165ac2604e7fefe82c2d66dce)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-social-feeds-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-19955eca3d87d5509b51c0be0c7d4376-d76dea69)
[docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-user-profiles-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-14ccbdaf2ccd4e7d91bcc26a083c3597-d76dea69)
[docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012?branch=pr-en-us-8038) | [Details](#user-content-568c86bf3f59c993d21b509ded663185-d76dea69)
[docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-excel-services-javascript-object-model?branch=pr-en-us-8038) | [Details](#user-content-149e8834b2baaabfd16cb7f16c4e89ed-d76dea69)
[docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model?branch=pr-en-us-8038) | [Details](#user-content-6c339a76ce97c049716ea01ce55e7e7a-d76dea69)
[docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer?branch=pr-en-us-8038) | [Details](#user-content-a9aa200d258e141b0c30fbdc1a65fe1b-d76dea69)

<a id="19955eca3d87d5509b51c0be0c7d4376-d76dea69"></a>
### [docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ccbdaf2ccd4e7d91bcc26a083c3597-d76dea69"></a>
### [docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="568c86bf3f59c993d21b509ded663185-d76dea69"></a>
### [docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="149e8834b2baaabfd16cb7f16c4e89ed-d76dea69"></a>
### [docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6c339a76ce97c049716ea01ce55e7e7a-d76dea69"></a>
### [docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a9aa200d258e141b0c30fbdc1a65fe1b-d76dea69"></a>
### [docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206062046172553-8038/BuildReport?accessString=cf9d582924c27eeb80df4bf630f3b47f16bbccbd093555b1bbe60aa933fb30c5).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-v [...]

2022-06-06 21:55 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0d07ac3](https://github.com/mSarts/sp-dev-docs/commits/0d07ac396ea30d827b9c8c4e7df50eeef4c0c7da)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-social-feeds-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-19955eca3d87d5509b51c0be0c7d4376-747d801a)
[docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-user-profiles-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-14ccbdaf2ccd4e7d91bcc26a083c3597-747d801a)
[docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012?branch=pr-en-us-8038) | [Details](#user-content-568c86bf3f59c993d21b509ded663185-747d801a)
[docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-excel-services-javascript-object-model?branch=pr-en-us-8038) | [Details](#user-content-149e8834b2baaabfd16cb7f16c4e89ed-747d801a)
[docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model?branch=pr-en-us-8038) | [Details](#user-content-6c339a76ce97c049716ea01ce55e7e7a-747d801a)
[docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer?branch=pr-en-us-8038) | [Details](#user-content-a9aa200d258e141b0c30fbdc1a65fe1b-747d801a)

<a id="19955eca3d87d5509b51c0be0c7d4376-747d801a"></a>
### [docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ccbdaf2ccd4e7d91bcc26a083c3597-747d801a"></a>
### [docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="568c86bf3f59c993d21b509ded663185-747d801a"></a>
### [docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="149e8834b2baaabfd16cb7f16c4e89ed-747d801a"></a>
### [docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6c339a76ce97c049716ea01ce55e7e7a-747d801a"></a>
### [docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a9aa200d258e141b0c30fbdc1a65fe1b-747d801a"></a>
### [docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206062153510102-8038/BuildReport?accessString=2e124e7a65032ab4d7f81e593265ccf4bec70969234ac7dc71011ab4d197534f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-v [...]

2022-06-06 21:58 UTC, VesaJuvonen commented
Docs Build status updates of commit _[ac0e99d](https://github.com/mSarts/sp-dev-docs/commits/ac0e99dafbd81029319ab872e21761a5a828e9ba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-social-feeds-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-19955eca3d87d5509b51c0be0c7d4376-0961fa1f)
[docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-user-profiles-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-14ccbdaf2ccd4e7d91bcc26a083c3597-0961fa1f)
[docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012?branch=pr-en-us-8038) | [Details](#user-content-568c86bf3f59c993d21b509ded663185-0961fa1f)
[docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-excel-services-javascript-object-model?branch=pr-en-us-8038) | [Details](#user-content-149e8834b2baaabfd16cb7f16c4e89ed-0961fa1f)
[docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model?branch=pr-en-us-8038) | [Details](#user-content-6c339a76ce97c049716ea01ce55e7e7a-0961fa1f)
[docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer?branch=pr-en-us-8038) | [Details](#user-content-a9aa200d258e141b0c30fbdc1a65fe1b-0961fa1f)

<a id="19955eca3d87d5509b51c0be0c7d4376-0961fa1f"></a>
### [docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ccbdaf2ccd4e7d91bcc26a083c3597-0961fa1f"></a>
### [docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="568c86bf3f59c993d21b509ded663185-0961fa1f"></a>
### [docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="149e8834b2baaabfd16cb7f16c4e89ed-0961fa1f"></a>
### [docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6c339a76ce97c049716ea01ce55e7e7a-0961fa1f"></a>
### [docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a9aa200d258e141b0c30fbdc1a65fe1b-0961fa1f"></a>
### [docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206062157210094-8038/BuildReport?accessString=a07a8d4ec576d882acd4e7dcdbc1010837bef5f4c2064b57eafaeaac58400326).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-v [...]

2022-06-06 22:07 UTC, mSarts commented
**Global effort to fix build validation errors**

@VesaJuvonen  

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-07 14:02 UTC, andrewconnell requested changes
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

2022-06-07 15:28 UTC, VesaJuvonen commented
Docs Build status updates of commit _[afcf4b8](https://github.com/mSarts/sp-dev-docs/commits/afcf4b8b9a46a512c010681ce4c41ffae32d33aa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-social-feeds-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-19955eca3d87d5509b51c0be0c7d4376-0853fa6d)
[docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/work-with-user-profiles-in-sharepoint?branch=pr-en-us-8038) | [Details](#user-content-14ccbdaf2ccd4e7d91bcc26a083c3597-0853fa6d)
[docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012?branch=pr-en-us-8038) | [Details](#user-content-568c86bf3f59c993d21b509ded663185-0853fa6d)
[docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-excel-services-javascript-object-model?branch=pr-en-us-8038) | [Details](#user-content-149e8834b2baaabfd16cb7f16c4e89ed-0853fa6d)
[docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model?branch=pr-en-us-8038) | [Details](#user-content-6c339a76ce97c049716ea01ce55e7e7a-0853fa6d)
[docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer?branch=pr-en-us-8038) | [Details](#user-content-a9aa200d258e141b0c30fbdc1a65fe1b-0853fa6d)
[docs/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012?branch=pr-en-us-8038) | [Details](#user-content-6a0f0f7d0e1918ee2c84892c2fe5863f-0853fa6d)

<a id="19955eca3d87d5509b51c0be0c7d4376-0853fa6d"></a>
### [docs/general-development/work-with-social-feeds-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-social-feeds-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="14ccbdaf2ccd4e7d91bcc26a083c3597-0853fa6d"></a>
### [docs/general-development/work-with-user-profiles-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/work-with-user-profiles-in-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="568c86bf3f59c993d21b509ded663185-0853fa6d"></a>
### [docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-tasks-in-sharepoint-workflows-using-visual-studio-2012.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="149e8834b2baaabfd16cb7f16c4e89ed-0853fa6d"></a>
### [docs/general-development/working-with-the-excel-services-javascript-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-excel-services-javascript-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6c339a76ce97c049716ea01ce55e7e7a-0853fa6d"></a>
### [docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-the-sharepoint-workflow-services-client-side-object-model.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="a9aa200d258e141b0c30fbdc1a65fe1b-0853fa6d"></a>
### [docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-sharepoint-designer.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6a0f0f7d0e1918ee2c84892c2fe5863f-0853fa6d"></a>
### [docs/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/working-with-web-services-in-sharepoint-workflows-using-visual-studio-2012.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms [...]

2022-06-09 10:32 UTC, andrewconnell approved these changes

2022-06-09 10:54 UTC, merged