Validation: Removed Absolute Links and Updated Descriptions.
SharePoint/sp-dev-docs pull request #8039
Opened 2022-06-06 22:05 UTC by dereklh7

## Category

- [ ] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

Removed absolute links,  added missing metadata descriptions, updated duplicate alt text descriptions, and adjusted disallowed HTML.

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?

> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in this PR. Sample description or details around bugs which are being fixed.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `master` branch of this repo. Released documents are in `live` branch.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

2022-06-06 22:08 UTC, VesaJuvonen commented
Docs Build status updates of commit _[572c09d](https://github.com/dereklh7/sp-dev-docs/commits/572c09d2ee7361732935920cfd077d96bb237324)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint?branch=pr-en-us-8039) | [Details](#user-content-9348ff2a45e287784cec447d4656d599-2946cc42)
[docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-4a215dbacf2a6d38ec15ef1060ca2f30-2946cc42)
[docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-7843eab5840aa35c82280b8bd5f505a6-2946cc42)
[docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-a2f7d51c031975ee691ebc9938100183-2946cc42)
[docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-783b22fdd1a6ad24cce5c3ebe842bf57-2946cc42)
[docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-558abcb03c492093e0022f25eb2e0492-2946cc42)
[docs/spfx/publish-to-marketplace-after-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/publish-to-marketplace-after-publishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-after-publishing?branch=pr-en-us-8039) | [Details](#user-content-3595a6840e3d6c4f051122128d68d2b1-2946cc42)
[docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops?branch=pr-en-us-8039) | [Details](#user-content-81bcd17809b752ca12b1f5db5f957c47-2946cc42)
[docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-aadhttpclient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient?branch=pr-en-us-8039) | [Details](#user-content-38dcf3b52fdcdc8ec41d348a773a9911-2946cc42)
[docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-theme-colors-in-your-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations?branch=pr-en-us-8039) | [Details](#user-content-d673714d2bccd161432f37861698a99c-2946cc42)
[docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro?branch=pr-en-us-8039) | [Details](#user-content-6fa2ea48da572fec7d8c15ecdb08333f-2946cc42)
[docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-card?branch=pr-en-us-8039) | [Details](#user-content-dff02a73e61a58202eeeaf51ce8eda1b-2946cc42)
[docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-quick-view?branch=pr-en-us-8039) | [Details](#user-content-ce7bd3af60e4cd71861b789c56646b40-2946cc42)
[docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/quick-view-samples?branch=pr-en-us-8039) | [Details](#user-content-e9260ca9032a44cdc7f3e9d50f50ac09-2946cc42)
[docs/spfx/web-parts/guidance/supporting-section-backgrounds.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/supporting-section-backgrounds.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds?branch=pr-en-us-8039) | [Details](#user-content-a5d8ee8c559927f78fa433eda7d1b3b0-2946cc42)
[docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries?branch=pr-en-us-8039) | [Details](#user-content-4b4d6b14cc37f874f295fbc752313339-2946cc42)
[docs/support-feedback.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/support-feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/support-feedback?branch=pr-en-us-8039) | [Details](#user-content-425b5e98775e9abf71d8939ec006ef30-2946cc42)
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations?branch=pr-en-us-8039) | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-2946cc42)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-guidance-support?branch=pr-en-us-8039) | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-2946cc42)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal-scanner?branch=pr-en-us-8039) | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-2946cc42)
[docs/tran [...]

2022-06-06 22:17 UTC, VesaJuvonen commented
Docs Build status updates of commit _[4b210f2](https://github.com/dereklh7/sp-dev-docs/commits/4b210f2a795c21a9ce765e44e685db1c0bb74344)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint?branch=pr-en-us-8039) | [Details](#user-content-9348ff2a45e287784cec447d4656d599-1110fed2)
[docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-4a215dbacf2a6d38ec15ef1060ca2f30-1110fed2)
[docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-7843eab5840aa35c82280b8bd5f505a6-1110fed2)
[docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-a2f7d51c031975ee691ebc9938100183-1110fed2)
[docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-783b22fdd1a6ad24cce5c3ebe842bf57-1110fed2)
[docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-558abcb03c492093e0022f25eb2e0492-1110fed2)
[docs/spfx/publish-to-marketplace-after-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/publish-to-marketplace-after-publishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-after-publishing?branch=pr-en-us-8039) | [Details](#user-content-3595a6840e3d6c4f051122128d68d2b1-1110fed2)
[docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops?branch=pr-en-us-8039) | [Details](#user-content-81bcd17809b752ca12b1f5db5f957c47-1110fed2)
[docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-aadhttpclient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient?branch=pr-en-us-8039) | [Details](#user-content-38dcf3b52fdcdc8ec41d348a773a9911-1110fed2)
[docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-theme-colors-in-your-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations?branch=pr-en-us-8039) | [Details](#user-content-d673714d2bccd161432f37861698a99c-1110fed2)
[docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro?branch=pr-en-us-8039) | [Details](#user-content-6fa2ea48da572fec7d8c15ecdb08333f-1110fed2)
[docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-card?branch=pr-en-us-8039) | [Details](#user-content-dff02a73e61a58202eeeaf51ce8eda1b-1110fed2)
[docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-quick-view?branch=pr-en-us-8039) | [Details](#user-content-ce7bd3af60e4cd71861b789c56646b40-1110fed2)
[docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/quick-view-samples?branch=pr-en-us-8039) | [Details](#user-content-e9260ca9032a44cdc7f3e9d50f50ac09-1110fed2)
[docs/spfx/web-parts/guidance/supporting-section-backgrounds.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/supporting-section-backgrounds.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds?branch=pr-en-us-8039) | [Details](#user-content-a5d8ee8c559927f78fa433eda7d1b3b0-1110fed2)
[docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries?branch=pr-en-us-8039) | [Details](#user-content-4b4d6b14cc37f874f295fbc752313339-1110fed2)
[docs/support-feedback.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/support-feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/support-feedback?branch=pr-en-us-8039) | [Details](#user-content-425b5e98775e9abf71d8939ec006ef30-1110fed2)
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations?branch=pr-en-us-8039) | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-1110fed2)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-guidance-support?branch=pr-en-us-8039) | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-1110fed2)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal-scanner?branch=pr-en-us-8039) | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-1110fed2)
[docs/tran [...]

2022-06-06 22:23 UTC, dereklh7 commented
@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-07 14:05 UTC, andrewconnell requested changes
Please update the `ms.date` with the current date of the change to correctly reflect the last time this doc was updated.

2022-06-07 14:05 UTC, andrewconnell commented on docs/spfx/use-aadhttpclient.md
> +- To *approve the specific permission request*, use the **Approve-SPOTenantServicePrincipalPermissionRequest -RequestId &lt;Guid&gt;** cmdlet, specifying the ID of the permission request that you wan
Correct markdown escaping of angled brackets should be prefixed with`\`; don't change to the HTML encoding.

2022-06-07 14:05 UTC, andrewconnell commented on docs/spfx/use-aadhttpclient.md
> +- To *deny a permission request* (if the requested permission has already been granted, or the request is against your organizational policies), use the **Deny-SPOTenantServicePrincipalPermissionRequ
Correct markdown escaping of angled brackets should be prefixed with`\`; don't change to the HTML encoding.

2022-06-07 14:05 UTC, andrewconnell commented on docs/spfx/use-aadhttpclient.md
> +- To *revoke a previously granted permission*, use the **Revoke-SPOTenantServicePrincipalPermission -ObjectId &lt;String&gt;** cmdlet. In the **ObjectId** parameter, you should specify the objectId o
Correct markdown escaping of angled brackets should be prefixed with`\`; don't change to the HTML encoding.

2022-06-07 17:46 UTC, VesaJuvonen commented
Docs Build status updates of commit _[ece4d55](https://github.com/dereklh7/sp-dev-docs/commits/ece4d555d32da034ba4c337d2733bcf269b31ea6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint?branch=pr-en-us-8039) | [Details](#user-content-9348ff2a45e287784cec447d4656d599-63c1fcdf)
[docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-4a215dbacf2a6d38ec15ef1060ca2f30-63c1fcdf)
[docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-7843eab5840aa35c82280b8bd5f505a6-63c1fcdf)
[docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-a2f7d51c031975ee691ebc9938100183-63c1fcdf)
[docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-783b22fdd1a6ad24cce5c3ebe842bf57-63c1fcdf)
[docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-558abcb03c492093e0022f25eb2e0492-63c1fcdf)
[docs/spfx/publish-to-marketplace-after-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/publish-to-marketplace-after-publishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-after-publishing?branch=pr-en-us-8039) | [Details](#user-content-3595a6840e3d6c4f051122128d68d2b1-63c1fcdf)
[docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops?branch=pr-en-us-8039) | [Details](#user-content-81bcd17809b752ca12b1f5db5f957c47-63c1fcdf)
[docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-aadhttpclient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient?branch=pr-en-us-8039) | [Details](#user-content-38dcf3b52fdcdc8ec41d348a773a9911-63c1fcdf)
[docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-theme-colors-in-your-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations?branch=pr-en-us-8039) | [Details](#user-content-d673714d2bccd161432f37861698a99c-63c1fcdf)
[docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro?branch=pr-en-us-8039) | [Details](#user-content-6fa2ea48da572fec7d8c15ecdb08333f-63c1fcdf)
[docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-card?branch=pr-en-us-8039) | [Details](#user-content-dff02a73e61a58202eeeaf51ce8eda1b-63c1fcdf)
[docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-quick-view?branch=pr-en-us-8039) | [Details](#user-content-ce7bd3af60e4cd71861b789c56646b40-63c1fcdf)
[docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/quick-view-samples?branch=pr-en-us-8039) | [Details](#user-content-e9260ca9032a44cdc7f3e9d50f50ac09-63c1fcdf)
[docs/spfx/web-parts/guidance/supporting-section-backgrounds.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/supporting-section-backgrounds.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds?branch=pr-en-us-8039) | [Details](#user-content-a5d8ee8c559927f78fa433eda7d1b3b0-63c1fcdf)
[docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries?branch=pr-en-us-8039) | [Details](#user-content-4b4d6b14cc37f874f295fbc752313339-63c1fcdf)
[docs/support-feedback.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/support-feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/support-feedback?branch=pr-en-us-8039) | [Details](#user-content-425b5e98775e9abf71d8939ec006ef30-63c1fcdf)
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations?branch=pr-en-us-8039) | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-63c1fcdf)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-guidance-support?branch=pr-en-us-8039) | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-63c1fcdf)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal-scanner?branch=pr-en-us-8039) | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-63c1fcdf)
[docs/tran [...]

2022-06-07 17:47 UTC, dereklh7 commented
@andrewconnell I've implemented requested changes. Please let me know if there are any other issues preventing approval and merge. Thanks!

2022-06-09 10:51 UTC, andrewconnell requested changes
The date changed in `ms.date` isn't accurate to the current date when these files were updated. 

When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 15:54 UTC, VesaJuvonen commented
Docs Build status updates of commit _[60bdf0a](https://github.com/dereklh7/sp-dev-docs/commits/60bdf0a7238d16739a93498ec1f4eb728e32d1dc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/serving-your-extension-from-sharepoint?branch=pr-en-us-8039) | [Details](#user-content-9348ff2a45e287784cec447d4656d599-acd04ed5)
[docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-ecb-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-4a215dbacf2a6d38ec15ef1060ca2f30-acd04ed5)
[docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-7843eab5840aa35c82280b8bd5f505a6-acd04ed5)
[docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-from-usercustomactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-a2f7d51c031975ee691ebc9938100183-acd04ed5)
[docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-jslink-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-783b22fdd1a6ad24cce5c3ebe842bf57-acd04ed5)
[docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/guidance/migrate-user-customactions-to-spfx-extensions?branch=pr-en-us-8039) | [Details](#user-content-558abcb03c492093e0022f25eb2e0492-acd04ed5)
[docs/spfx/publish-to-marketplace-after-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/publish-to-marketplace-after-publishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/publish-to-marketplace-after-publishing?branch=pr-en-us-8039) | [Details](#user-content-3595a6840e3d6c4f051122128d68d2b1-acd04ed5)
[docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops?branch=pr-en-us-8039) | [Details](#user-content-81bcd17809b752ca12b1f5db5f957c47-acd04ed5)
[docs/spfx/use-aadhttpclient.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-aadhttpclient.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-aadhttpclient?branch=pr-en-us-8039) | [Details](#user-content-38dcf3b52fdcdc8ec41d348a773a9911-acd04ed5)
[docs/spfx/use-theme-colors-in-your-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/use-theme-colors-in-your-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/use-theme-colors-in-your-customizations?branch=pr-en-us-8039) | [Details](#user-content-d673714d2bccd161432f37861698a99c-acd04ed5)
[docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro?branch=pr-en-us-8039) | [Details](#user-content-6fa2ea48da572fec7d8c15ecdb08333f-acd04ed5)
[docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-card?branch=pr-en-us-8039) | [Details](#user-content-dff02a73e61a58202eeeaf51ce8eda1b-acd04ed5)
[docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-quick-view?branch=pr-en-us-8039) | [Details](#user-content-ce7bd3af60e4cd71861b789c56646b40-acd04ed5)
[docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/quick-view-samples?branch=pr-en-us-8039) | [Details](#user-content-e9260ca9032a44cdc7f3e9d50f50ac09-acd04ed5)
[docs/spfx/web-parts/guidance/supporting-section-backgrounds.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/supporting-section-backgrounds.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/supporting-section-backgrounds?branch=pr-en-us-8039) | [Details](#user-content-a5d8ee8c559927f78fa433eda7d1b3b0-acd04ed5)
[docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/web-parts/guidance/use-existing-javascript-libraries.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/web-parts/guidance/use-existing-javascript-libraries?branch=pr-en-us-8039) | [Details](#user-content-4b4d6b14cc37f874f295fbc752313339-acd04ed5)
[docs/support-feedback.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/support-feedback.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/support-feedback?branch=pr-en-us-8039) | [Details](#user-content-425b5e98775e9abf71d8939ec006ef30-acd04ed5)
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations?branch=pr-en-us-8039) | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-acd04ed5)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-guidance-support?branch=pr-en-us-8039) | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-acd04ed5)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal-scanner?branch=pr-en-us-8039) | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-acd04ed5)
[docs/tran [...]

2022-06-13 21:38 UTC, VesaJuvonen commented
Docs Build status updates of commit _[cd69422](https://github.com/dereklh7/sp-dev-docs/commits/cd694221ba4b590dbfbc740e8f0fa77df639cf38)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/toc.yml) | :x:Error | | [Details](#user-content-5f90628710a9c97451a7b405c32efd6a-1fb94e63)
[docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md) | :warning:Warning | | [Details](#user-content-9348ff2a45e287784cec447d4656d599-1fb94e63)
[docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md) | :warning:Warning | | [Details](#user-content-e9260ca9032a44cdc7f3e9d50f50ac09-1fb94e63)
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-1fb94e63)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-1fb94e63)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-1fb94e63)
[docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md) | :warning:Warning | | [Details](#user-content-05b65326b837ed1c9104467f83b77ac3-1fb94e63)
[docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md) | :warning:Warning | | [Details](#user-content-19f75bf4a8830df544ed46ddc9acd795-1fb94e63)
[docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md) | :warning:Warning | | [Details](#user-content-15c07ec35d21277d2841549e1f8cf0fb-1fb94e63)
[docs/transform/modernize-scanner-reports.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports.md) | :warning:Warning | | [Details](#user-content-2f81f037df01ee5464cc49818a657dc6-1fb94e63)
[docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner.md) | :warning:Warning | | [Details](#user-content-6bb67aac8e2a9ee9afdb7f2a70b1d263-1fb94e63)
[docs/transform/modernize-userinterface-lists-and-libraries-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-lists-and-libraries-scanner.md) | :warning:Warning | | [Details](#user-content-078163789756551685e22fcc48f5c87f-1fb94e63)
[docs/transform/modernize-userinterface-site-pages-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-api.md) | :warning:Warning | | [Details](#user-content-37f99a2b67214acc81c6fea8dbd3dfe1-1fb94e63)
[docs/transform/modernize-userinterface-site-pages-layout.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-layout.md) | :warning:Warning | | [Details](#user-content-cbcaa0875a0e6a22cebfc9d51e0fd6a4-1fb94e63)
[docs/transform/modernize-userinterface-site-pages-model-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-model-publishing.md) | :warning:Warning | | [Details](#user-content-01837e5980bdb9dd7eb94c2086309230-1fb94e63)

<a id="5f90628710a9c97451a7b405c32efd6a-1fb94e63"></a>
### [docs/toc.yml](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/toc.yml)
 - **Line 2060, Column 5**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="9348ff2a45e287784cec447d4656d599-1fb94e63"></a>
### [docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/serving-your-extension-from-sharepoint.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 25, Column 167**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/toolchain/provision-sharepoint-assets' will be broken in isolated environments. Replace with a relative link.`````
 - **Line 26, Column 11**: **[Suggestion: docs-link-absolute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/docs-link-absolute?branch=main)]** `````Absolute link 'https://docs.microsoft.com/sharepoint/dev/spfx/tenant-scoped-deployment' will be broken in isolated environments. Replace with a relative link.`````

<a id="e9260ca9032a44cdc7f3e9d50f50ac09-1fb94e63"></a>
### [docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 53, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Inventory' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 61, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Payslip' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 69, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Praise' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````
 - **Line 69, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Praise' is duplicated. Within an article, alt text must be unique.`````
 - **Line 77, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'Praise' is duplicated. Within an article, alt text must be unique.`````
 - **Line 85, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````A [...]

2022-06-13 21:58 UTC, VesaJuvonen commented
Docs Build status updates of commit _[61efdf4](https://github.com/dereklh7/sp-dev-docs/commits/61efdf4f3c62d95db6dafee94e0b926d877f72f1)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/toc.yml](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/toc.yml) | :x:Error | | [Details](#user-content-5f90628710a9c97451a7b405c32efd6a-6cecd493)
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-6cecd493)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-6cecd493)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-6cecd493)
[docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md) | :warning:Warning | | [Details](#user-content-05b65326b837ed1c9104467f83b77ac3-6cecd493)
[docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md) | :warning:Warning | | [Details](#user-content-19f75bf4a8830df544ed46ddc9acd795-6cecd493)
[docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md) | :warning:Warning | | [Details](#user-content-15c07ec35d21277d2841549e1f8cf0fb-6cecd493)
[docs/transform/modernize-scanner-reports.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports.md) | :warning:Warning | | [Details](#user-content-2f81f037df01ee5464cc49818a657dc6-6cecd493)
[docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner.md) | :warning:Warning | | [Details](#user-content-6bb67aac8e2a9ee9afdb7f2a70b1d263-6cecd493)
[docs/transform/modernize-userinterface-lists-and-libraries-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-lists-and-libraries-scanner.md) | :warning:Warning | | [Details](#user-content-078163789756551685e22fcc48f5c87f-6cecd493)
[docs/transform/modernize-userinterface-site-pages-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-api.md) | :warning:Warning | | [Details](#user-content-37f99a2b67214acc81c6fea8dbd3dfe1-6cecd493)
[docs/transform/modernize-userinterface-site-pages-layout.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-layout.md) | :warning:Warning | | [Details](#user-content-cbcaa0875a0e6a22cebfc9d51e0fd6a4-6cecd493)
[docs/transform/modernize-userinterface-site-pages-model-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-model-publishing.md) | :warning:Warning | | [Details](#user-content-01837e5980bdb9dd7eb94c2086309230-6cecd493)

<a id="5f90628710a9c97451a7b405c32efd6a-6cecd493"></a>
### [docs/toc.yml](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/toc.yml)
 - **Line 2060, Column 5**: **[Error: yaml-syntax-error]** `````While parsing a block mapping, did not find expected key.`````

<a id="79e6dad785e6fc52bd0a7fc08e92dfc0-6cecd493"></a>
### [docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6da8602410c4e4cbc4e652127c0bcd61-6cecd493"></a>
### [docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="60aabefc704ab121a005ea5c57d0c512-6cecd493"></a>
### [docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="05b65326b837ed1c9104467f83b77ac3-6cecd493"></a>
### [docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19f75bf4a8830df544ed46ddc9acd795-6cecd493"></a>
### [docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="15c07ec35d21277d2841549e1f8cf0fb-6cecd493"></a>
### [docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2f81f037df01ee5464cc49818a657dc6-6cecd493"></a>
### [docs/transform/modernize-scanner-reports.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6bb67aac8e2a9ee9afdb7f2a70b1d263-6cecd493"></a>
### [docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod [...]

2022-06-13 21:59 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0f5d4dd](https://github.com/dereklh7/sp-dev-docs/commits/0f5d4dda3175ac3e1d47a26a19e84e0eb7d8aee8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations?branch=pr-en-us-8039) | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-c3ca3450)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-guidance-support?branch=pr-en-us-8039) | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-c3ca3450)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal-scanner?branch=pr-en-us-8039) | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-c3ca3450)
[docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal?branch=pr-en-us-8039) | [Details](#user-content-05b65326b837ed1c9104467f83b77ac3-c3ca3450)
[docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-groupconnect?branch=pr-en-us-8039) | [Details](#user-content-19f75bf4a8830df544ed46ddc9acd795-c3ca3450)
[docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-lists?branch=pr-en-us-8039) | [Details](#user-content-15c07ec35d21277d2841549e1f8cf0fb-c3ca3450)
[docs/transform/modernize-scanner-reports.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports?branch=pr-en-us-8039) | [Details](#user-content-2f81f037df01ee5464cc49818a657dc6-c3ca3450)
[docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner?branch=pr-en-us-8039) | [Details](#user-content-6bb67aac8e2a9ee9afdb7f2a70b1d263-c3ca3450)
[docs/transform/modernize-userinterface-lists-and-libraries-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-lists-and-libraries-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries-scanner?branch=pr-en-us-8039) | [Details](#user-content-078163789756551685e22fcc48f5c87f-c3ca3450)
[docs/transform/modernize-userinterface-site-pages-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-api?branch=pr-en-us-8039) | [Details](#user-content-37f99a2b67214acc81c6fea8dbd3dfe1-c3ca3450)
[docs/transform/modernize-userinterface-site-pages-layout.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-layout.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-layout?branch=pr-en-us-8039) | [Details](#user-content-cbcaa0875a0e6a22cebfc9d51e0fd6a4-c3ca3450)
[docs/transform/modernize-userinterface-site-pages-model-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-model-publishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing?branch=pr-en-us-8039) | [Details](#user-content-01837e5980bdb9dd7eb94c2086309230-c3ca3450)

<a id="79e6dad785e6fc52bd0a7fc08e92dfc0-c3ca3450"></a>
### [docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6da8602410c4e4cbc4e652127c0bcd61-c3ca3450"></a>
### [docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="60aabefc704ab121a005ea5c57d0c512-c3ca3450"></a>
### [docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="05b65326b837ed1c9104467f83b77ac3-c3ca3450"></a>
### [docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19f75bf4a8830df544ed46ddc9acd795-c3ca3450"></a>
### [docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="15c07ec35d21277d2841549e1f8cf0fb-c3ca3450"></a>
### [docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod [...]

2022-06-13 22:21 UTC, RedZephyr13 commented on docs/transform/modernize-userinterface-site-pages-api.md
> +Name|Description| Membership
Let's keep this table to two columns, and expose the pipes in cells like this:
|Name|Description|
|:---|:---|
|{ContactLoginName}|User account to lookup (in i:0#.f\|membership\|joe@contoso.onmicrosoft.com format)|

2022-06-13 22:24 UTC, RedZephyr13 commented on docs/transform/modernize-userinterface-site-pages-api.md
> +{'term ids split by &#124;'}|List of term id's to set, multiple values can also be used when the taxonomy field is configured to accept multiple terms
So to expose a pipe, but not be a marker for a separate column, put a slash in front of it, like we do for the angle brackets.  So line 729 should look like:
`|{'term ids split by /|;'}|List of term id's to set, multiple values can also be used when the taxonomy field is configured to accept multiple terms|`

2022-06-13 22:24 UTC, RedZephyr13 commented on docs/transform/modernize-userinterface-site-pages-api.md
>  Name|Description
Beginning and end brackets are missing for this table.

2022-06-13 22:25 UTC, RedZephyr13 commented on docs/transform/modernize-userinterface-site-pages-api.md
> +{'static boolean value'}|Static bool ('true', 'false') to indicate if the default term values have to be set in case the fields already contains terms
Beginning and end brackets are missing for this table.

2022-06-13 22:48 UTC, VesaJuvonen commented
Docs Build status updates of commit _[cef17a7](https://github.com/dereklh7/sp-dev-docs/commits/cef17a7cf9bbe2705033ffb357d5901ff444deb7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations?branch=pr-en-us-8039) | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-653ef272)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-guidance-support?branch=pr-en-us-8039) | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-653ef272)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal-scanner?branch=pr-en-us-8039) | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-653ef272)
[docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal?branch=pr-en-us-8039) | [Details](#user-content-05b65326b837ed1c9104467f83b77ac3-653ef272)
[docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-groupconnect?branch=pr-en-us-8039) | [Details](#user-content-19f75bf4a8830df544ed46ddc9acd795-653ef272)
[docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-lists?branch=pr-en-us-8039) | [Details](#user-content-15c07ec35d21277d2841549e1f8cf0fb-653ef272)
[docs/transform/modernize-scanner-reports.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports?branch=pr-en-us-8039) | [Details](#user-content-2f81f037df01ee5464cc49818a657dc6-653ef272)
[docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner?branch=pr-en-us-8039) | [Details](#user-content-6bb67aac8e2a9ee9afdb7f2a70b1d263-653ef272)
[docs/transform/modernize-userinterface-lists-and-libraries-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-lists-and-libraries-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries-scanner?branch=pr-en-us-8039) | [Details](#user-content-078163789756551685e22fcc48f5c87f-653ef272)
[docs/transform/modernize-userinterface-site-pages-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-api?branch=pr-en-us-8039) | [Details](#user-content-37f99a2b67214acc81c6fea8dbd3dfe1-653ef272)
[docs/transform/modernize-userinterface-site-pages-layout.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-layout.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-layout?branch=pr-en-us-8039) | [Details](#user-content-cbcaa0875a0e6a22cebfc9d51e0fd6a4-653ef272)
[docs/transform/modernize-userinterface-site-pages-model-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-model-publishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing?branch=pr-en-us-8039) | [Details](#user-content-01837e5980bdb9dd7eb94c2086309230-653ef272)

<a id="79e6dad785e6fc52bd0a7fc08e92dfc0-653ef272"></a>
### [docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6da8602410c4e4cbc4e652127c0bcd61-653ef272"></a>
### [docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="60aabefc704ab121a005ea5c57d0c512-653ef272"></a>
### [docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="05b65326b837ed1c9104467f83b77ac3-653ef272"></a>
### [docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19f75bf4a8830df544ed46ddc9acd795-653ef272"></a>
### [docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="15c07ec35d21277d2841549e1f8cf0fb-653ef272"></a>
### [docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod [...]

2022-06-13 22:49 UTC, dereklh7 commented
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-20 09:53 UTC, andrewconnell requested changes

2022-06-20 09:53 UTC, andrewconnell commented on docs/transform/modernize-userinterface-site-pages-api.md
> +|{ContactLoginName}|User account to lookup (in i:0#.f\|membership\|joe@contoso.onmicrosoft.com)
What happened to the word "format"? The way this has been left doesn't make sense

2022-06-20 09:53 UTC, andrewconnell commented on docs/transform/modernize-userinterface-site-pages-api.md
> +{'static boolean value'}|Static bool ('true', 'false') to indicate if the default term values have to be set in case the \<field\> already contains terms
Incorrect... the word was a typo, but it shouldn't be changed to a HTML tag

2022-06-20 20:10 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8c38868](https://github.com/dereklh7/sp-dev-docs/commits/8c38868d3e324accd1ae39af12698cdc9500b40f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-customizations?branch=pr-en-us-8039) | [Details](#user-content-79e6dad785e6fc52bd0a7fc08e92dfc0-1f186367)
[docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-guidance-support?branch=pr-en-us-8039) | [Details](#user-content-6da8602410c4e4cbc4e652127c0bcd61-1f186367)
[docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal-scanner?branch=pr-en-us-8039) | [Details](#user-content-60aabefc704ab121a005ea5c57d0c512-1f186367)
[docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-publishing-portal?branch=pr-en-us-8039) | [Details](#user-content-05b65326b837ed1c9104467f83b77ac3-1f186367)
[docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-groupconnect?branch=pr-en-us-8039) | [Details](#user-content-19f75bf4a8830df544ed46ddc9acd795-1f186367)
[docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-lists?branch=pr-en-us-8039) | [Details](#user-content-15c07ec35d21277d2841549e1f8cf0fb-1f186367)
[docs/transform/modernize-scanner-reports.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports?branch=pr-en-us-8039) | [Details](#user-content-2f81f037df01ee5464cc49818a657dc6-1f186367)
[docs/transform/modernize-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner?branch=pr-en-us-8039) | [Details](#user-content-6bb67aac8e2a9ee9afdb7f2a70b1d263-1f186367)
[docs/transform/modernize-userinterface-lists-and-libraries-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-lists-and-libraries-scanner.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-lists-and-libraries-scanner?branch=pr-en-us-8039) | [Details](#user-content-078163789756551685e22fcc48f5c87f-1f186367)
[docs/transform/modernize-userinterface-site-pages-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-api?branch=pr-en-us-8039) | [Details](#user-content-37f99a2b67214acc81c6fea8dbd3dfe1-1f186367)
[docs/transform/modernize-userinterface-site-pages-layout.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-layout.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-layout?branch=pr-en-us-8039) | [Details](#user-content-cbcaa0875a0e6a22cebfc9d51e0fd6a4-1f186367)
[docs/transform/modernize-userinterface-site-pages-model-publishing.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-userinterface-site-pages-model-publishing.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing?branch=pr-en-us-8039) | [Details](#user-content-01837e5980bdb9dd7eb94c2086309230-1f186367)

<a id="79e6dad785e6fc52bd0a7fc08e92dfc0-1f186367"></a>
### [docs/transform/modernize-customizations.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-customizations.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="6da8602410c4e4cbc4e652127c0bcd61-1f186367"></a>
### [docs/transform/modernize-guidance-support.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-guidance-support.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="60aabefc704ab121a005ea5c57d0c512-1f186367"></a>
### [docs/transform/modernize-publishing-portal-scanner.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal-scanner.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="05b65326b837ed1c9104467f83b77ac3-1f186367"></a>
### [docs/transform/modernize-publishing-portal.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-publishing-portal.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="19f75bf4a8830df544ed46ddc9acd795-1f186367"></a>
### [docs/transform/modernize-scanner-reports-groupconnect.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-groupconnect.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="15c07ec35d21277d2841549e1f8cf0fb-1f186367"></a>
### [docs/transform/modernize-scanner-reports-lists.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/transform/modernize-scanner-reports-lists.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod [...]

2022-06-20 20:12 UTC, dereklh7 commented
@andrewconnell I've implemented the requested fixes. Please let me know if there are any additional issues that need to be resolved for this PR to be approved and merged. Thanks and have a great day!

2022-06-21 09:42 UTC, merged