Validations: Fix multiple issues
SharePoint/sp-dev-docs pull request #8040
Opened 2022-06-06 22:49 UTC by annmariehitchcock

## Category

- [ ] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

> **DELETE THIS LINE BEFORE SUBMITTING** | *For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.*

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?

> **DELETE THIS LINE BEFORE SUBMITTING** | *Please describe the changes in this PR. Sample description or details around bugs which are being fixed.*

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `master` branch of this repo. Released documents are in `live` branch.
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

2022-06-06 22:50 UTC, VesaJuvonen commented
Docs Build status updates of commit _[f59f280](https://github.com/annmariehitchcock/sp-dev-docs/commits/f59f2806ca8675dac63d996bb5291468737eacf8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-72d1efc4)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-72d1efc4)

<a id="bd14762e1ff0230fcf6a857a239ed520-72d1efc4"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 53, Column 68**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute '"T:Microsoft.SharePoint.Deployment.SPExportSettings"' on tag 'a' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="8797b184de887ec2368937d5d350d1a7-72d1efc4"></a>
### [docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206062249244120-8040/BuildReport?accessString=06a327adbd50497f692ab97fc180ad4207131d728f1c6168e1c35b2757c13338).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-06 23:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[59100b6](https://github.com/annmariehitchcock/sp-dev-docs/commits/59100b6b33a971cf0a63994ada63e4da4b43785a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-4b942a94)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-4b942a94)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-4b942a94)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-4b942a94)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-4b942a94)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-4b942a94)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-4b942a94)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-4b942a94)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-4b942a94)

<a id="bd14762e1ff0230fcf6a857a239ed520-4b942a94"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 53, Column 68**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute '"T:Microsoft.SharePoint.Deployment.SPExportSettings"' on tag 'a' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-4b942a94"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-4b942a94"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-4b942a94"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-4b942a94"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 11, Column 1**: **[Warning: yaml-duplicate-key]** `````Key 'description' is already defined, remove the duplicate key.`````
 - **Line 11, Column 14**: **[Suggestion: duplicate-descriptions - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-descriptions?branch=main)]** `````Attribute 'description' with value 'Last modified: March 09, 2015' is duplicated in 'scenario-guidance/Enterprise-Content-Management.md(11,14)', 'schema/_authschemename-element-formsauthcredentials-complextypesps15xsdsearchset2.md(10,14)', 'schema/_authsubmissionmethod-element-formsauthcredentials-complextypesps15xsdsearchset2.md(10,14)', 'schema/_authsubmissionpath-element-formsauthcredentials-complextypesps15xsdsearchset2.md(10,14)', 'schema/_cookies-element-cookieauthdata-complextypesps15xsdsearchset2.md(10,14)'....`````

<a id="9eb77a7b681bccb692c1813dee69bb0a-4b942a94"></a>
### [docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.mic [...]

2022-06-07 00:01 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b4149e2](https://github.com/annmariehitchcock/sp-dev-docs/commits/b4149e20e2cad50ff7c019fe9243bba626086a71)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-2d9d7d10)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-2d9d7d10)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-2d9d7d10)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-2d9d7d10)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-2d9d7d10)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-2d9d7d10)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-2d9d7d10)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-2d9d7d10)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-2d9d7d10)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-2d9d7d10)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-2d9d7d10)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-2d9d7d10)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-2d9d7d10)

<a id="bd14762e1ff0230fcf6a857a239ed520-2d9d7d10"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 53, Column 68**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute '"T:Microsoft.SharePoint.Deployment.SPExportSettings"' on tag 'a' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-2d9d7d10"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-2d9d7d10"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-2d9d7d10"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-2d9d7d10"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schem [...]

2022-06-07 16:54 UTC, VesaJuvonen commented
Docs Build status updates of commit _[7cdf437](https://github.com/annmariehitchcock/sp-dev-docs/commits/7cdf437685bfee6807a34b9ac7a129dec6b073b8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/basic-uri-structure-and-path.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/basic-uri-structure-and-path.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/basic-uri-structure-and-path?branch=pr-en-us-8040) | [Details](#user-content-95a5aceb9ba91367322012b2b24efd39-ad5feafe)
[docs/general-development/bcs-client-object-model-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-client-object-model-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-client-object-model-reference-for-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-c4db1b1ab76ddf71d76c9542bdcc273e-ad5feafe)
[docs/general-development/bcs-rest-api-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/bcs-rest-api-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/bcs-rest-api-reference-for-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-8c1642d0b73e0d90c8dfcee65105846d-ad5feafe)
[docs/general-development/build-farm-solutions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-farm-solutions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-farm-solutions-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-d0bcc56c8bf9b560bbba5bfd7c2c0d8f-ad5feafe)
[docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-localized-applications-for-windows-phone-based-on-the-sharepoint-templates?branch=pr-en-us-8040) | [Details](#user-content-4b67576b6628d4d1187c9a194ab1ffb8-ad5feafe)
[docs/general-development/build-reusable-components-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-reusable-components-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-reusable-components-for-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-a798c55d175fb22b64e051b77fe31926-ad5feafe)
[docs/general-development/build-sites-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-sites-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-sites-for-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-fbed1b6fa2f2dc30890a71b6b7123228-ad5feafe)
[docs/general-development/building-search-queries-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/building-search-queries-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/building-search-queries-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-f3fe17398f1f6f6e73efd18b655bd87a-ad5feafe)
[docs/general-development/business-connectivity-services-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-9e9fba951cec5b1d1ed1b0afbbf85f13-ad5feafe)
[docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/business-connectivity-services-programmers-reference-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/business-connectivity-services-programmers-reference-for-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-54780469cc65715b48c2aa1b96a9fbad-ad5feafe)
[docs/general-development/choose-the-right-api-set-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/choose-the-right-api-set-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/choose-the-right-api-set-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-0e65f22883585a8896c44dce051dc71e-ad5feafe)
[docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-and-concepts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-and-concepts-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-0c33ae566a62cfe10618bcd0889e479c-ad5feafe)
[docs/general-development/claims-based-identity-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-d6a709306162a93350d42264d4c0e37c-ad5feafe)
[docs/general-development/claims-based-identity-term-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-based-identity-term-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-based-identity-term-definitions?branch=pr-en-us-8040) | [Details](#user-content-9ec33dea4fc32a77fd5f256a505a3cd9-ad5feafe)
[docs/general-development/claims-provider-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/claims-provider-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/claims-provider-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-57749caa294f66a6f6752c28a1f3dd8d-ad5feafe)
[docs/general-development/configuration-administration-and-resources-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configuration-administration-and-resources-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configuration-administration-and-resources-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-232b2d39215826132479cf6fe987f0cb-ad5feafe)
[docs/general-development/configure-search-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/configure-search-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/configure-search-in-sharepoint?branch=pr-en-us-8040) | [Details](#user-content-e79ef0fe9536ce916d1d7c78a36b4501-ad5feafe)
[docs/general-development/content-management-interoperability-services-cmis-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/content-management-interoperability-services-cmis-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/content [...]

2022-06-07 17:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5625ab7](https://github.com/annmariehitchcock/sp-dev-docs/commits/5625ab73d7976826594927b2aca61c9d9fa888a5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-725040b2)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-725040b2)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-725040b2)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-725040b2)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-725040b2)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-725040b2)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-725040b2)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-725040b2)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-725040b2)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-725040b2)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-725040b2)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-725040b2)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-725040b2)

<a id="bd14762e1ff0230fcf6a857a239ed520-725040b2"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 53, Column 68**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute '"T:Microsoft.SharePoint.Deployment.SPExportSettings"' on tag 'a' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-725040b2"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-725040b2"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-725040b2"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-725040b2"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schem [...]

2022-06-07 18:11 UTC, VesaJuvonen commented
Docs Build status updates of commit _[184be2c](https://github.com/annmariehitchcock/sp-dev-docs/commits/184be2c7226ad6e13d0b9ef354046f7ee153aa5c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-9f782aef)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-9f782aef)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-9f782aef)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-9f782aef)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-9f782aef)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-9f782aef)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-9f782aef)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-9f782aef)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-9f782aef)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-9f782aef)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-9f782aef)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-9f782aef)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-9f782aef)

<a id="bd14762e1ff0230fcf6a857a239ed520-9f782aef"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 53, Column 66**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'sdata' on tag 'span' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````
 - **Line 53, Column 78**: **[Suggestion: disallowed-html-attribute - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-attribute?branch=main)]** `````HTML attribute 'target' on tag 'span' isn't allowed. Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-9f782aef"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-9f782aef"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-9f782aef"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the follo [...]

2022-06-07 20:21 UTC, VesaJuvonen commented
Docs Build status updates of commit _[4d78d79](https://github.com/annmariehitchcock/sp-dev-docs/commits/4d78d79f2907d0ceecddcb7d4f980410d73293e8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-5d57e445)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-5d57e445)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-5d57e445)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-5d57e445)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-5d57e445)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-5d57e445)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-5d57e445)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-5d57e445)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-5d57e445)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-5d57e445)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-5d57e445)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-5d57e445)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-5d57e445)

<a id="bd14762e1ff0230fcf6a857a239ed520-5d57e445"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 53, Column 61**: **[Suggestion: disallowed-html-tag - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/disallowed-html-tag?branch=main)]** `````HTML tag 'target="T:Microsoft.SharePoint.Deployment.SPExportSettings"' isn't allowed.  Replace it with approved Markdown or escape the brackets if the content is a placeholder.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-5d57e445"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-5d57e445"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-5d57e445"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-5d57e445"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element [...]

2022-06-07 20:45 UTC, VesaJuvonen commented
Docs Build status updates of commit _[551132c](https://github.com/annmariehitchcock/sp-dev-docs/commits/551132cfb331917ec95c133c315cf2d53a0062c1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-c60dcc21)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-c60dcc21)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-c60dcc21)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-c60dcc21)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-c60dcc21)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-c60dcc21)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-c60dcc21)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-c60dcc21)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-c60dcc21)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-c60dcc21)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-c60dcc21)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-c60dcc21)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-c60dcc21)

<a id="bd14762e1ff0230fcf6a857a239ed520-c60dcc21"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-c60dcc21"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-c60dcc21"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-c60dcc21"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-c60dcc21"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9eb77a [...]

2022-06-07 20:52 UTC, annmariehitchcock commented
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-09 15:39 UTC, annmariehitchcock commented
https://github.com/SharePoint/sp-dev-docs/pull/8040

2022-06-10 22:23 UTC, VesaJuvonen commented
Docs Build status updates of commit _[75169ab](https://github.com/annmariehitchcock/sp-dev-docs/commits/75169ab9f477eccac4cf0b15a8cebc8bd8f1290b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-7247387c)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-7247387c)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-7247387c)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-7247387c)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-7247387c)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-7247387c)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-7247387c)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-7247387c)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-7247387c)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-7247387c)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-7247387c)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-7247387c)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-7247387c)

<a id="bd14762e1ff0230fcf6a857a239ed520-7247387c"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-7247387c"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-7247387c"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-7247387c"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-7247387c"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com [...]

2022-06-10 22:32 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5a21c05](https://github.com/annmariehitchcock/sp-dev-docs/commits/5a21c0560df47874db3576b79f79d20fde27eb42)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-515f2b9b)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-515f2b9b)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-515f2b9b)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-515f2b9b)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-515f2b9b)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-515f2b9b)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-515f2b9b)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-515f2b9b)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-515f2b9b)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-515f2b9b)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-515f2b9b)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-515f2b9b)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-515f2b9b)

<a id="bd14762e1ff0230fcf6a857a239ed520-515f2b9b"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 2, Column 1**: **[Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)]** `````Missing required attribute: 'description'.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-515f2b9b"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-515f2b9b"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-515f2b9b"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-515f2b9b"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com [...]

2022-06-10 22:44 UTC, VesaJuvonen commented
Docs Build status updates of commit _[fa2b65a](https://github.com/annmariehitchcock/sp-dev-docs/commits/fa2b65ac463717b50dfad32ce47ff755312d8066)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-507033e0)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-507033e0)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-507033e0)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-507033e0)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-507033e0)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-507033e0)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-507033e0)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-507033e0)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-507033e0)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-507033e0)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-507033e0)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-507033e0)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-507033e0)

<a id="bd14762e1ff0230fcf6a857a239ed520-507033e0"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-507033e0"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-507033e0"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-507033e0"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-507033e0"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9eb77a [...]

2022-06-11 22:49 UTC, annmariehitchcock commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-20 10:08 UTC, andrewconnell requested changes

2022-06-20 10:08 UTC, andrewconnell commented on docs/schema/content-migration-schemas.md
>  ms.date: 3/9/2015
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-20 15:33 UTC, VesaJuvonen commented
Docs Build status updates of commit _[445cceb](https://github.com/annmariehitchcock/sp-dev-docs/commits/445cceb7d54c03ada87de1bb1422f13778605775)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-migration-schemas?branch=pr-en-us-8040) | [Details](#user-content-bd14762e1ff0230fcf6a857a239ed520-2ec4d448)
[docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-bindings?branch=pr-en-us-8040) | [Details](#user-content-ad8f8ffcf908ee9e9db948bd647ac4c8-2ec4d448)
[docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/content-type-definitions?branch=pr-en-us-8040) | [Details](#user-content-bd3fbdd4c40ee0d487c0e89f00169e5b-2ec4d448)
[docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-contenttype?branch=pr-en-us-8040) | [Details](#user-content-9e017316520dd5fb35fb2d2da1b02a66-2ec4d448)
[docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-b8d95f71a959fce2aafe0ed2b96e6d77-2ec4d448)
[docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-schemasource-elementdatasourcetype-complextypeaction4?branch=pr-en-us-8040) | [Details](#user-content-9eb77a7b681bccb692c1813dee69bb0a-2ec4d448)
[docs/schema/contenttype-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowactions?branch=pr-en-us-8040) | [Details](#user-content-a12de8c2830b08011ce02f3aca697dc8-2ec4d448)
[docs/schema/contenttype-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-a4820d421638abffab8a361a4dfb3592-2ec4d448)
[docs/schema/contenttype-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttype-element-workflowinfo?branch=pr-en-us-8040) | [Details](#user-content-c7ba8c8a174787adac7dd0f10b6c6235-2ec4d448)
[docs/schema/contenttypebinding-element-contenttypebinding.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypebinding-element-contenttypebinding.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypebinding-element-contenttypebinding?branch=pr-en-us-8040) | [Details](#user-content-8797b184de887ec2368937d5d350d1a7-2ec4d448)
[docs/schema/contenttypes-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-deploymentmanifest?branch=pr-en-us-8040) | [Details](#user-content-6a2ea3456dd209a912f89db97d69e1cc-2ec4d448)
[docs/schema/contenttypes-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttypes-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contenttypes-element-workflowconfig?branch=pr-en-us-8040) | [Details](#user-content-291b628434b37ca4da6375445d980dd5-2ec4d448)
[docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeexte?branch=pr-en-us-8040) | [Details](#user-content-27a4fbc95217b0676eba4267db8fbac8-2ec4d448)

<a id="bd14762e1ff0230fcf6a857a239ed520-2ec4d448"></a>
### [docs/schema/content-migration-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-migration-schemas.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ad8f8ffcf908ee9e9db948bd647ac4c8-2ec4d448"></a>
### [docs/schema/content-type-bindings.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-bindings.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="bd3fbdd4c40ee0d487c0e89f00169e5b-2ec4d448"></a>
### [docs/schema/content-type-definitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/content-type-definitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9e017316520dd5fb35fb2d2da1b02a66-2ec4d448"></a>
### [docs/schema/contenttype-element-contenttype.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-contenttype.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="b8d95f71a959fce2aafe0ed2b96e6d77-2ec4d448"></a>
### [docs/schema/contenttype-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contenttype-element-deploymentmanifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="9eb77a [...]

2022-06-20 19:33 UTC, andrewconnell approved these changes

2022-06-20 19:33 UTC, merged