Validation: Removed Absolute Links and Added Missing Descriptions
SharePoint/sp-dev-docs pull request #8042
Opened 2022-06-06 23:36 UTC by dereklh7

## Category

- [ ] Content fix
- [ ] New article
- [x] Example checked item (*delete this line*)

> **DELETE THIS LINE BEFORE SUBMITTING** | *For the above list, an empty checkbox is [ ] as in <kbd>[</kbd><kbd>SPACE</kbd><kbd>]</kbd>. A checked checkbox is [x] with no space between the brackets. Use the `PREVIEW` tab at the top right to preview the rendering before submitting your issue.*

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?

Removed absolute Links, added missing metadata descriptions, and adjusted disallowed HTML.

2022-06-06 23:37 UTC, VesaJuvonen commented
Docs Build status updates of commit _[111e741](https://github.com/dereklh7/sp-dev-docs/commits/111e741fac6f6e84cb54b8e931055300938646ef)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online?branch=pr-en-us-8042) | [Details](#user-content-b500e67a9ff961439133406484da4bfe-eb02ce0b)
[docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-and-performance?branch=pr-en-us-8042) | [Details](#user-content-25d66667e3ebde6fbd5415ab2b319152-eb02ce0b)
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/search-api-usage-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-api-usage-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-permissivesetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting?branch=pr-en-us-8042) |
[docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features?branch=pr-en-us-8042) |
[docs/solution-guidance/site-provisioning-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/site-provisioning-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/site-provisioning-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/the-pnp-office-open-xml-file-format.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/the-pnp-office-open-xml-file-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/the-pnp-office-open-xml-file-format?branch=pr-en-us-8042) |

<a id="b500e67a9ff961439133406484da4bfe-eb02ce0b"></a>
### [docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md)
 - **Line 327, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'SharePoint/search/how-to-display-values-from-custom-managed-properties-in-the-hover-panel'.`````

<a id="25d66667e3ebde6fbd5415ab2b319152-eb02ce0b"></a>
### [docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md)
 - **Line 18, Column 158**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md'.`````
 - **Line 11, Column 2**: **[Suggestion: column-header-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/column-header-missing?branch=main)]** `````Column headers are required for tables. Add appropriate header text, or remove any extra table cells that cause an extra column.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206062336062075-8042/BuildReport?accessString=75665cb918cbc37bd8dbc42d077e33994bd251c2c64437f304866a94257254e8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId [...]

2022-06-07 16:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[d65d61e](https://github.com/dereklh7/sp-dev-docs/commits/d65d61ef65936e7fc7eb1574e225882fc8a0fcd2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online?branch=pr-en-us-8042) | [Details](#user-content-b500e67a9ff961439133406484da4bfe-245d926a)
[docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-and-performance?branch=pr-en-us-8042) | [Details](#user-content-25d66667e3ebde6fbd5415ab2b319152-245d926a)
[docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions?branch=pr-en-us-8042) | [Details](#user-content-8d70b7afdd8fc06732fcb14f6dea8f46-245d926a)
[docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-bf06ccacaccf2b7094d27c0f7f0eea9d-245d926a)
[docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in?branch=pr-en-us-8042) | [Details](#user-content-ad8bd035b93c436381d1cb6dee993642-245d926a)
[docs/sp-add-ins/add-in-permissions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-in-permissions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint?branch=pr-en-us-8042) | [Details](#user-content-c939658d258a531894d005872a3eac5c-245d926a)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-245d926a)
[docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in?branch=pr-en-us-8042) | [Details](#user-content-26312a9bb4f27f19c1c6813f2187b6df-245d926a)
[docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte?branch=pr-en-us-8042) | [Details](#user-content-abb4dadafb6be77640a5bfa55f0f0eae-245d926a)
[docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web?branch=pr-en-us-8042) | [Details](#user-content-65635286dfd80f695fdb360e1bd4761c-245d926a)
[docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index?branch=pr-en-us-8042) | [Details](#user-content-ba230203100e92f385ac75b20af22db5-245d926a)
[docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-52e0b6fa6b4d7245645119c57be117fe-245d926a)
[docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest?branch=pr-en-us-8042) | [Details](#user-content-657276220738f24bb18332225061ff2f-245d926a)
[docs/spfx/build-for-teams-me-experience.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/build-for-teams-me-experience.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-me-experience?branch=pr-en-us-8042) | [Details](#user-content-289c4a67d41b9db0281c00e08f231ae8-245d926a)
[docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api?branch=pr-en-us-8042) | [Details](#user-content-a66696c4b6a83fb9acb14a0e1d9ac90c-245d926a)
[docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/query-suggestion-tutorial-building?branch=pr-en-us-8042) | [Details](#user-content-815bd7eb0780cd84322e6af0ff425b13-245d926a)
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solutio [...]

2022-06-07 17:01 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0936ac7](https://github.com/dereklh7/sp-dev-docs/commits/0936ac7b91d28cc6d3fab158fb60e38dbee4346f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in?branch=pr-en-us-8042) | [Details](#user-content-ad8bd035b93c436381d1cb6dee993642-f879777b)
[docs/sp-add-ins/add-in-permissions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-in-permissions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint?branch=pr-en-us-8042) | [Details](#user-content-c939658d258a531894d005872a3eac5c-f879777b)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-f879777b)
[docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in?branch=pr-en-us-8042) | [Details](#user-content-26312a9bb4f27f19c1c6813f2187b6df-f879777b)
[docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte?branch=pr-en-us-8042) | [Details](#user-content-abb4dadafb6be77640a5bfa55f0f0eae-f879777b)
[docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web?branch=pr-en-us-8042) | [Details](#user-content-65635286dfd80f695fdb360e1bd4761c-f879777b)
[docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index?branch=pr-en-us-8042) | [Details](#user-content-ba230203100e92f385ac75b20af22db5-f879777b)
[docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-52e0b6fa6b4d7245645119c57be117fe-f879777b)
[docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest?branch=pr-en-us-8042) | [Details](#user-content-657276220738f24bb18332225061ff2f-f879777b)
[docs/spfx/build-for-teams-me-experience.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/build-for-teams-me-experience.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-me-experience?branch=pr-en-us-8042) | [Details](#user-content-289c4a67d41b9db0281c00e08f231ae8-f879777b)
[docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api?branch=pr-en-us-8042) | [Details](#user-content-a66696c4b6a83fb9acb14a0e1d9ac90c-f879777b)
[docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/query-suggestion-tutorial-building?branch=pr-en-us-8042) | [Details](#user-content-815bd7eb0780cd84322e6af0ff425b13-f879777b)
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/search-api-usage-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-api-usage-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-onlin [...]

2022-06-07 17:09 UTC, dereklh7 commented
@VesaJuvonen

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-09 11:03 UTC, andrewconnell requested changes
Lots of errors in these submissions. Please fix.

Also, when you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 11:03 UTC, andrewconnell commented on docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md
> +|Ribbon|Any of the default master pages. Corresponding CSS: <ul> https://www.w3.org/1999/xlink <br> https://msdn2.microsoft.com/mtps <br> https://msdn.microsoft.com/mshelp <br>https://ddue.schemas.mi
This is true for almost app proposed fixes in this doc. Please fix

2022-06-09 11:03 UTC, andrewconnell commented on docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md
> +|Core.QueueWebJobUsage|Your SharePoint Add-in project. The following permissions are required:<ul> https://www.w3.org/1999/xlink <br> https://msdn2.microsoft.com/mtps <br> https://msdn.microsoft.com/
Invalid, see previous comments.

2022-06-09 11:03 UTC, andrewconnell commented on docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md
> +<!---
Why is this commented out?

2022-06-09 11:03 UTC, andrewconnell commented on docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md
> +--->
Why is this commented out?

2022-06-09 16:54 UTC, dereklh7 commented on docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md
> +|Ribbon|Any of the default master pages. Corresponding CSS: <ul> https://www.w3.org/1999/xlink <br> https://msdn2.microsoft.com/mtps <br> https://msdn.microsoft.com/mshelp <br>https://ddue.schemas.mi
@andrewconnell These links are not present in the live version of the article - would it be best to remove the links for this issue? If not, what do you propose would be the optimal fix in this situation?

2022-06-09 17:05 UTC, dereklh7 commented on docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md
> +|Ribbon|Any of the default master pages. Corresponding CSS: <ul> https://www.w3.org/1999/xlink <br> https://msdn2.microsoft.com/mtps <br> https://msdn.microsoft.com/mshelp <br>https://ddue.schemas.mi
I am reverting this change, but removing the disallowed HTML attributes, as the links are not present on the live content. This should resolve the rendering problem. Let me know if another change would be preferred.

2022-06-09 17:32 UTC, VesaJuvonen commented
Docs Build status updates of commit _[abf6d79](https://github.com/dereklh7/sp-dev-docs/commits/abf6d791d050a00f5200e25a5aa90c91c8a90f8d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-a-web-part-to-a-page-in-a-sharepoint-hosted-sharepoint-add-in?branch=pr-en-us-8042) | [Details](#user-content-ad8bd035b93c436381d1cb6dee993642-9dbcca69)
[docs/sp-add-ins/add-in-permissions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-in-permissions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint?branch=pr-en-us-8042) | [Details](#user-content-c939658d258a531894d005872a3eac5c-9dbcca69)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-9dbcca69)
[docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in?branch=pr-en-us-8042) | [Details](#user-content-26312a9bb4f27f19c1c6813f2187b6df-9dbcca69)
[docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte?branch=pr-en-us-8042) | [Details](#user-content-abb4dadafb6be77640a5bfa55f0f0eae-9dbcca69)
[docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/include-a-web-part-in-a-webpage-on-the-add-in-web?branch=pr-en-us-8042) | [Details](#user-content-65635286dfd80f695fdb360e1bd4761c-9dbcca69)
[docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index?branch=pr-en-us-8042) | [Details](#user-content-ba230203100e92f385ac75b20af22db5-9dbcca69)
[docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-52e0b6fa6b4d7245645119c57be117fe-9dbcca69)
[docs/sp-add-ins/working-with-folders-and-files-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/working-with-folders-and-files-with-rest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-folders-and-files-with-rest?branch=pr-en-us-8042) | [Details](#user-content-dceedff3e83e1aa0cecb3ecb2f4e0444-9dbcca69)
[docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/working-with-lists-and-list-items-with-rest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest?branch=pr-en-us-8042) | [Details](#user-content-657276220738f24bb18332225061ff2f-9dbcca69)
[docs/spfx/build-for-teams-me-experience.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/build-for-teams-me-experience.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-me-experience?branch=pr-en-us-8042) | [Details](#user-content-289c4a67d41b9db0281c00e08f231ae8-9dbcca69)
[docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-cmdset-with-dialog-api?branch=pr-en-us-8042) | [Details](#user-content-a66696c4b6a83fb9acb14a0e1d9ac90c-9dbcca69)
[docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/query-suggestion-tutorial-building.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/query-suggestion-tutorial-building?branch=pr-en-us-8042) | [Details](#user-content-815bd7eb0780cd84322e6af0ff425b13-9dbcca69)
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/sea [...]

2022-06-09 17:36 UTC, dereklh7 commented
@andrewconnell I've implemented the requested changes. Please let me know if there are any remaining issues preventing approval and merge for this PR. Thanks and have a great day!

2022-06-13 18:26 UTC, VesaJuvonen commented
Docs Build status updates of commit _[f46bac9](https://github.com/dereklh7/sp-dev-docs/commits/f46bac919d08d13c649b3227f943e05d4907747c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/add-in-permissions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-in-permissions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint?branch=pr-en-us-8042) | [Details](#user-content-c939658d258a531894d005872a3eac5c-86580aba)
[docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in?branch=pr-en-us-8042) | [Details](#user-content-26312a9bb4f27f19c1c6813f2187b6df-86580aba)
[docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte?branch=pr-en-us-8042) | [Details](#user-content-abb4dadafb6be77640a5bfa55f0f0eae-86580aba)
[docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index?branch=pr-en-us-8042) | [Details](#user-content-ba230203100e92f385ac75b20af22db5-86580aba)
[docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/three-ways-to-think-about-design-options-for-sharepoint-add-ins?branch=pr-en-us-8042) | [Details](#user-content-52e0b6fa6b4d7245645119c57be117fe-86580aba)
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/search-api-usage-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-api-usage-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online?branch=pr-en-us-8042) |
[docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-and-performance?branch=pr-en-us-8042) |
[docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-permissivesetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting?branch=pr-en-us-8042) |
[docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features?branch=pr-en-us-8042) |
[docs/solution-guidance/site-provisioning-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/site-provisioning-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/site-provisioning-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/the-pnp-office-open-xml-file-format.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/the-pnp-office-open-xml-file-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/the-pnp-office-open-xml-file-format?branch=pr-en-us-8042) |
[docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions?branch=pr-en-us-8042) |
[docs/solution-guidance/upload-web-parts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/upload-web-parts-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-web-parts-in-sharepoint?branch=pr-en-us-8042) |
[docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md](https:/ [...]

2022-06-13 18:34 UTC, VesaJuvonen commented
Docs Build status updates of commit _[30ca46d](https://github.com/dereklh7/sp-dev-docs/commits/30ca46d86e4b1d9bf164c055c3cbb03d25d9befe)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/sp-add-ins/add-in-permissions-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/add-in-permissions-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/add-in-permissions-in-sharepoint?branch=pr-en-us-8042) | [Details](#user-content-c939658d258a531894d005872a3eac5c-495d063f)
[docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/convert-an-autohosted-sharepoint-add-in-to-a-provider-hosted-add-in?branch=pr-en-us-8042) | [Details](#user-content-26312a9bb4f27f19c1c6813f2187b6df-495d063f)
[docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/create-a-provider-hosted-add-in-that-includes-a-custom-sharepoint-list-and-conte?branch=pr-en-us-8042) | [Details](#user-content-abb4dadafb6be77640a5bfa55f0f0eae-495d063f)
[docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/sharepoint-net-server-csom-jsom-and-rest-api-index?branch=pr-en-us-8042) | [Details](#user-content-ba230203100e92f385ac75b20af22db5-495d063f)
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/search-api-usage-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-api-usage-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online?branch=pr-en-us-8042) |
[docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-and-performance?branch=pr-en-us-8042) |
[docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-permissivesetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting?branch=pr-en-us-8042) |
[docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features?branch=pr-en-us-8042) |
[docs/solution-guidance/site-provisioning-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/site-provisioning-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/site-provisioning-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/the-pnp-office-open-xml-file-format.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/the-pnp-office-open-xml-file-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/the-pnp-office-open-xml-file-format?branch=pr-en-us-8042) |
[docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions?branch=pr-en-us-8042) |
[docs/solution-guidance/upload-web-parts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/upload-web-parts-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-web-parts-in-sharepoint?branch=pr-en-us-8042) |
[docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins?branch=pr-en-us-8042) |
[docs/solution-guidance/variations-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/variations-sharepoint-add-in.m [...]

2022-06-13 19:06 UTC, VesaJuvonen commented
Docs Build status updates of commit _[926aab3](https://github.com/dereklh7/sp-dev-docs/commits/926aab3a00a64486528327c32806d18918f345c3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/search-api-usage-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-api-usage-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online?branch=pr-en-us-8042) |
[docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-and-performance?branch=pr-en-us-8042) |
[docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-permissivesetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting?branch=pr-en-us-8042) |
[docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features?branch=pr-en-us-8042) |
[docs/solution-guidance/site-provisioning-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/site-provisioning-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/site-provisioning-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/the-pnp-office-open-xml-file-format.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/the-pnp-office-open-xml-file-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/the-pnp-office-open-xml-file-format?branch=pr-en-us-8042) |
[docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions?branch=pr-en-us-8042) |
[docs/solution-guidance/upload-web-parts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/upload-web-parts-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-web-parts-in-sharepoint?branch=pr-en-us-8042) |
[docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins?branch=pr-en-us-8042) |
[docs/solution-guidance/variations-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/variations-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/variations-sharepoint-add-in?branch=pr-en-us-8042) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206131905234655-8042/BuildReport?accessString=76905a7bfa89a6cada84649aae6927e13642be7e1ec53265338ee40e76d4de44).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 09:43 UTC, andrewconnell requested changes

2022-06-20 09:43 UTC, andrewconnell commented on docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md
> +<!--- - [How to display values from custom managed properties in the hover panel in SharePoint Server](SharePoint/search/how-to-display-values-from-custom-managed-properties-in-the-hover-panel) --->
What's the point of this change? If the content shouldn't be the there, remove it... don't comment it out.

2022-06-20 15:39 UTC, VesaJuvonen commented
Docs Build status updates of commit _[3c6015f](https://github.com/dereklh7/sp-dev-docs/commits/3c6015f5c9101d2a59b3c473e5f6cd1e00f87fe0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online?branch=pr-en-us-8042) | [Details](#user-content-b500e67a9ff961439133406484da4bfe-d39f65f7)
[docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-and-performance?branch=pr-en-us-8042) | [Details](#user-content-25d66667e3ebde6fbd5415ab2b319152-d39f65f7)
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/search-api-usage-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-api-usage-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-permissivesetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting?branch=pr-en-us-8042) |
[docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features?branch=pr-en-us-8042) |
[docs/solution-guidance/site-provisioning-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/site-provisioning-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/site-provisioning-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/the-pnp-office-open-xml-file-format.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/the-pnp-office-open-xml-file-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/the-pnp-office-open-xml-file-format?branch=pr-en-us-8042) |
[docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions?branch=pr-en-us-8042) |
[docs/solution-guidance/upload-web-parts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/upload-web-parts-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-web-parts-in-sharepoint?branch=pr-en-us-8042) |
[docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins?branch=pr-en-us-8042) |
[docs/solution-guidance/variations-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/variations-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/variations-sharepoint-add-in?branch=pr-en-us-8042) |

<a id="b500e67a9ff961439133406484da4bfe-d39f65f7"></a>
### [docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md)
 - **Line 327, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'SharePoint/search/how-to-display-values-from-custom-managed-properties-in-the-hover-panel'.`````

<a id="25d66667e3ebde6fbd5415ab2b319152-d39f65f7"></a>
### [docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md)
 - **Line 19, Column 1**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'Handle-SharePoint-Online-throttling-by-using-exponential-back-off.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201537484166-8042/BuildReport?accessString=af6eb2cc90f1d9a12991aff6c7b04cbd9ca2de9dae7ec3b1c84557bacf52260c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.micros [...]

2022-06-20 15:43 UTC, VesaJuvonen commented
Docs Build status updates of commit _[c59cc01](https://github.com/dereklh7/sp-dev-docs/commits/c59cc016befdecb00b76026db1758c65c422a126)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Sandbox-Solution-Transformation-Guidance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sandbox-solution-transformation-guidance?branch=pr-en-us-8042) |
[docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/Set-external-sharing-on-site-collections-in-Office-365.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/set-external-sharing-on-site-collections-in-office-365?branch=pr-en-us-8042) |
[docs/solution-guidance/SharePoint-pages-and-the-page-model.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/SharePoint-pages-and-the-page-model.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-pages-and-the-page-model?branch=pr-en-us-8042) |
[docs/solution-guidance/pnp-remote-timer-job-framework.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/pnp-remote-timer-job-framework.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/pnp-remote-timer-job-framework?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-navigation.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-navigation.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-navigation?branch=pr-en-us-8042) |
[docs/solution-guidance/portal-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/portal-overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/portal-overview?branch=pr-en-us-8042) |
[docs/solution-guidance/search-api-usage-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-api-usage-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-api-usage-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/search-solutions-in-sharepoint-2013-and-sharepoint-online?branch=pr-en-us-8042) |
[docs/solution-guidance/security-and-performance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-and-performance.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-and-performance?branch=pr-en-us-8042) |
[docs/solution-guidance/security-permissivesetting.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-permissivesetting.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-permissivesetting?branch=pr-en-us-8042) |
[docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/sharepoint-metadata-site-navigation-and-publishing-site-features?branch=pr-en-us-8042) |
[docs/solution-guidance/site-provisioning-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/site-provisioning-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/site-provisioning-sharepoint-add-in?branch=pr-en-us-8042) |
[docs/solution-guidance/the-pnp-office-open-xml-file-format.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/the-pnp-office-open-xml-file-format.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/the-pnp-office-open-xml-file-format?branch=pr-en-us-8042) |
[docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/update-the-branding-of-existing-sharepoint-sites-and-page-regions?branch=pr-en-us-8042) |
[docs/solution-guidance/upload-web-parts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/upload-web-parts-in-sharepoint.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/upload-web-parts-in-sharepoint?branch=pr-en-us-8042) |
[docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/use-asynchronous-operations-in-sharepoint-add-ins?branch=pr-en-us-8042) |
[docs/solution-guidance/variations-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/variations-sharepoint-add-in.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/variations-sharepoint-add-in?branch=pr-en-us-8042) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201541549312-8042/BuildReport?accessString=353f99689cdb06fba6a36b107cb6d8b825b573cb66fc67ad91d6e6a7afc081c5).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 15:54 UTC, dereklh7 commented
@andrewconnell I've implemented the requested fixes, in that I've removed the files instead of commenting them out. This change was implemented to resolve invalid file link Validation warnings. Please let me know if any additional issues with this PR are present and preventing approval and merge. Thanks!

2022-06-20 19:34 UTC, andrewconnell approved these changes

2022-06-20 19:34 UTC, merged