[BrokenLinksH2] Fix path in link
SharePoint/sp-dev-docs pull request #8047
Opened 2022-06-07 15:40 UTC by DhurataJ

Fixing broken links

2022-06-07 15:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[77f3b19](https://github.com/DhurataJ/sp-dev-docs/commits/77f3b19d644806809e4775e5e0ff5c2a2b9a0664)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-5679bcdd)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-5679bcdd)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-5679bcdd)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-5679bcdd)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-5679bcdd"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-5679bcdd"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-5679bcdd"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-5679bcdd"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206071540117848-8047/BuildReport?accessString=b088ac8ceb97c1264722b6470409d0566a0d88f872303ca4e98642b4cf4e7f33).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-07 15:49 UTC, DhurataJ commented
**Global effort to fix broken links**

@VesaJuvonen @andrewconnell - The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I'd very much appreciate your timely review and feedback on the link changes I've suggested. Thanks!

2022-06-09 10:35 UTC, andrewconnell commented on docs/community/contribute.md
> +* Provide input on new feature requests within SharePoint Developer UserVoice.
The link shouldn't be removed, but updated to the correct link used in the TOC: https://feedbackportal.microsoft.com/feedback/forum/06735c62-321c-ec11-b6e7-0022481f8472

2022-06-09 10:36 UTC, andrewconnell commented on docs/community/repositories.md
> +| [pnp-js-provisioning](https://github.com/Puzzlepart/pnp-js-provisioning) | Repository for planned JavaScript provisioning library |
Incorrect link... use https://github.com/pnp/sp-js-provisioning

2022-06-09 14:09 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b7d6184](https://github.com/DhurataJ/sp-dev-docs/commits/b7d6184f30ba9b977725015ef8cc608a30c03b0f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-afe9c633)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-afe9c633)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-afe9c633)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-afe9c633)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-afe9c633"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-afe9c633"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-afe9c633"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-afe9c633"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206091408159211-8047/BuildReport?accessString=872157abb9c1c476808f63d726da781fe7e4e4f5d707f16b6156ef1942944945).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-09 14:11 UTC, DhurataJ commented
@andrewconnell - Thanks so much for following up with your feedbacks and suggestions.

2022-06-20 09:19 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-20 09:20 UTC, VesaJuvonen commented
Docs Build status updates of commit _[54200ef](https://github.com/DhurataJ/sp-dev-docs/commits/54200eff805b10449bc1b74d6efc274d568327db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-badba154)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-badba154)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-badba154)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-badba154)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-badba154"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-badba154"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-badba154"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-badba154"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206200919281266-8047/BuildReport?accessString=a90787b50d44cf305d836b996be9d6c636c14256ce9e12469463d3065bde670b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 14:39 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a326a79](https://github.com/DhurataJ/sp-dev-docs/commits/a326a7929c2f85237544e495d6a81a4a2f351f44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-39952e0e)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-39952e0e)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-39952e0e)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-39952e0e)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-39952e0e"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-39952e0e"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-39952e0e"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-39952e0e"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201437524211-8047/BuildReport?accessString=1945cc3e87153adf6b3eead2d62ac81adea86de40dce7c7722a5888c32cc8d7d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 14:43 UTC, VesaJuvonen commented
Docs Build status updates of commit _[402e21e](https://github.com/DhurataJ/sp-dev-docs/commits/402e21e4b17a99a2f781a1dc0a1a0b358bf327e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-d51dd3ca)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-d51dd3ca)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-d51dd3ca)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-d51dd3ca)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-d51dd3ca"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-d51dd3ca"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-d51dd3ca"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-d51dd3ca"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201441299885-8047/BuildReport?accessString=ff763bd033b945c1b95b383da87d0243eac3fa1f2b2a6d2788939350eff51b2a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 14:52 UTC, VesaJuvonen commented
Docs Build status updates of commit _[2ec64c7](https://github.com/DhurataJ/sp-dev-docs/commits/2ec64c743bf97555e775452f8c9e6bc533040cd6)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-ae8bda2a)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-ae8bda2a)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-ae8bda2a)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-ae8bda2a)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-ae8bda2a"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-ae8bda2a"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-ae8bda2a"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/06/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-ae8bda2a"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/07/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201450380067-8047/BuildReport?accessString=012c3af14d235b6af0c598f9922a46d60a6ba2fe87fc43e8d11e48bbf384eea3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 14:53 UTC, VesaJuvonen commented
Docs Build status updates of commit _[3538a1c](https://github.com/DhurataJ/sp-dev-docs/commits/3538a1cffa82635242d9e64a4cf76068dab1ef90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-593af3b9)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-593af3b9)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-593af3b9)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-593af3b9)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-593af3b9"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-593af3b9"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-593af3b9"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/06/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-593af3b9"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/06/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201451085838-8047/BuildReport?accessString=47fdf002756c5cddc75bd6fe6001fabd150c9a760b986a12a2c534adf83f55e2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 14:56 UTC, VesaJuvonen commented
Docs Build status updates of commit _[80d10f8](https://github.com/DhurataJ/sp-dev-docs/commits/80d10f84ccc98d463d548bbf397af3a1b2e4c7b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-1ad4d537)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-1ad4d537)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-1ad4d537)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-1ad4d537)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) | [Details](#user-content-ded6b9be5c84504b873feb7048cbe223-1ad4d537)

<a id="fface3dbc399f5ee27b444b70910097a-1ad4d537"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-1ad4d537"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-1ad4d537"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/06/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-1ad4d537"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/06/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

<a id="ded6b9be5c84504b873feb7048cbe223-1ad4d537"></a>
### [docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md)
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/06/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201454211209-8047/BuildReport?accessString=63f9fa53e87ffbecf3cb4b4556cd06a6c31e20f738481f3e9ecde47b1910998a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 15:02 UTC, VesaJuvonen commented
Docs Build status updates of commit _[671ffdc](https://github.com/DhurataJ/sp-dev-docs/commits/671ffdc53a9db596272003aefef1a4ec839baa1c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-e184bba0)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-e184bba0)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-e184bba0)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-e184bba0)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) | [Details](#user-content-ded6b9be5c84504b873feb7048cbe223-e184bba0)

<a id="fface3dbc399f5ee27b444b70910097a-e184bba0"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-e184bba0"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-e184bba0"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-e184bba0"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ded6b9be5c84504b873feb7048cbe223-e184bba0"></a>
### [docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md)
 - **Line 4, Column 10**: **[Warning: ms-date-invalid - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-date-invalid?branch=main)]** `````Value out of range for 'ms.date': '09/06/2022'. Must be a date in format M/D/YYYY, no more than 30 days from today.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201458368972-8047/BuildReport?accessString=327c3757594e80dae7340f0a916310cf35d8b75addb5a62154a780a43e61ae84).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:30 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

You changed the dates to `DD/MM/YYYY`, which is not correct.

2022-06-20 19:46 UTC, VesaJuvonen commented
Docs Build status updates of commit _[462705a](https://github.com/DhurataJ/sp-dev-docs/commits/462705a86f031cc13c17600b6ff1f149a8e0cef4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-8391a257)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-8391a257)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-8391a257)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-8391a257)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-8391a257"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-8391a257"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-8391a257"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-8391a257"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201945162895-8047/BuildReport?accessString=1e3510d2a2221f2e1009e59d0762298361764ee2165d1ac0fbb4526441a0ee18).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:48 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0e3bdca](https://github.com/DhurataJ/sp-dev-docs/commits/0e3bdcae49d896ec83a64474f246b8559ca3a070)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-c611c41a)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-c611c41a)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-c611c41a)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-c611c41a)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-c611c41a"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-c611c41a"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-c611c41a"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-c611c41a"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201947004721-8047/BuildReport?accessString=7792329bc66fb15e036848dd73cd35f7b9f5f0a6becd7a65c685ba284750fb48).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:49 UTC, VesaJuvonen commented
Docs Build status updates of commit _[622163e](https://github.com/DhurataJ/sp-dev-docs/commits/622163ef9df22173430f5953a25f5f60f4a320ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-08b6ef3c)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-08b6ef3c)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-08b6ef3c)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-08b6ef3c)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-08b6ef3c"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-08b6ef3c"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-08b6ef3c"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-08b6ef3c"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201947358511-8047/BuildReport?accessString=954f0973285701cc9ce903e781ea387fb3ec8c898abf73d17ed9071ea89272fb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:51 UTC, VesaJuvonen commented
Docs Build status updates of commit _[9e3cc70](https://github.com/DhurataJ/sp-dev-docs/commits/9e3cc70bb3d17ae34a53ff326c2d4dfde7ee6f81)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-38cb87aa)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-38cb87aa)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-38cb87aa)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-38cb87aa)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-38cb87aa"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-38cb87aa"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-38cb87aa"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-38cb87aa"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201948358269-8047/BuildReport?accessString=b8f78e10f2b26094031a0c8d2e6dcf3f26714e0b888d84950a5422060a5aae90).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 19:52 UTC, VesaJuvonen commented
Docs Build status updates of commit _[f85e249](https://github.com/DhurataJ/sp-dev-docs/commits/f85e24993bba4c6d2be3ace23594fedee5611cac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/alm-api-for-spfx-add-ins?branch=pr-en-us-8047) | [Details](#user-content-fface3dbc399f5ee27b444b70910097a-a53d09fb)
[docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/contribute?branch=pr-en-us-8047) | [Details](#user-content-ee1389d427701977a440ad39e29cb77d-a53d09fb)
[docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/open-source-projects?branch=pr-en-us-8047) | [Details](#user-content-977a54fedd2b397ae60a519c5e03a2b3-a53d09fb)
[docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/community/repositories?branch=pr-en-us-8047) | [Details](#user-content-fecd60bf5d3047c9ffff2cd45a5d14cf-a53d09fb)
[docs/declarative-customization/site-design-pnppowershell.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/declarative-customization/site-design-pnppowershell.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/declarative-customization/site-design-pnppowershell?branch=pr-en-us-8047) |

<a id="fface3dbc399f5ee27b444b70910097a-a53d09fb"></a>
### [docs/apis/alm-api-for-spfx-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/alm-api-for-spfx-add-ins.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ee1389d427701977a440ad39e29cb77d-a53d09fb"></a>
### [docs/community/contribute.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/contribute.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="977a54fedd2b397ae60a519c5e03a2b3-a53d09fb"></a>
### [docs/community/open-source-projects.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/open-source-projects.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="fecd60bf5d3047c9ffff2cd45a5d14cf-a53d09fb"></a>
### [docs/community/repositories.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/community/repositories.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206201948106622-8047/BuildReport?accessString=8388e95057d5d857f9bd8cd2046936ea476abe27a6fdb926c8b60a6cc83d6a49).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 09:41 UTC, andrewconnell approved these changes

2022-06-21 09:42 UTC, merged