BULK VALIDATION misc fixes
SharePoint/sp-dev-docs pull request #8048
Opened 2022-06-07 16:48 UTC by mSarts

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

Bulk validation issue fixes.

2022-06-07 18:19 UTC, VesaJuvonen commented
Docs Build status updates of commit _[343357b](https://github.com/mSarts/sp-dev-docs/commits/343357b63ab7f7d235a9c0b805d557f89834637d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/assemblyredirect-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirect-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirect-element-workflowinfo?branch=pr-en-us-8048) | [Details](#user-content-ac4463bcc1820dd5292ce4bbab81ff0e-bf4b2742)
[docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirects-element-workflowinfo-elementaction4?branch=pr-en-us-8048) | [Details](#user-content-21d3c772741c4908f11dfd0179051614-bf4b2742)
[docs/schema/assemblyredirects-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirects-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirects-element-workflowinfo?branch=pr-en-us-8048) | [Details](#user-content-a2fdccab038e7e8b6071b753fcadee98-bf4b2742)
[docs/schema/assignment-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assignment-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assignment-element-deploymentmanifest?branch=pr-en-us-8048) | [Details](#user-content-4e7407b56eaffc8d86aaca1aaeaa3be9-bf4b2742)
[docs/schema/association-element-in-associations-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-associations-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-associations-subscription-schema?branch=pr-en-us-8048) | [Details](#user-content-531920706d9e8da9ebb4f40c8cd01048-bf4b2742)
[docs/schema/association-element-in-methodinstances-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-methodinstances-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-methodinstances-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-90a19b4f3072590c77f5f83a2b2a5ca8-bf4b2742)
[docs/schema/association-element-in-methodinstances-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-methodinstances-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-methodinstances-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-0b9e5859cf4c6486445f7c83c2339085-bf4b2742)
[docs/schema/association-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-workflowconfig?branch=pr-en-us-8048) | [Details](#user-content-c4da722cb66c275b79211e7b520b9240-bf4b2742)
[docs/schema/association-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element?branch=pr-en-us-8048) | [Details](#user-content-6bdbb15b41a3008f51a9f6789ba5b97c-bf4b2742)
[docs/schema/associationcategories-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationcategories-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationcategories-element-workflow?branch=pr-en-us-8048) | [Details](#user-content-8c31501e7f25523e67f24b9d2afefb38-bf4b2742)
[docs/schema/associationdata-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationdata-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationdata-element-workflow?branch=pr-en-us-8048) | [Details](#user-content-412bba210646932f1a534b43edbc6cda-bf4b2742)
[docs/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-47d647cddf563e24111329fd55af39fb-bf4b2742)
[docs/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-f80586d7e48a5077fceb05a52e4fb3d7-bf4b2742)
[docs/schema/associationgroups-element-in-entity-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroups-element-in-entity-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroups-element-in-entity-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-8060bd461ea07c2d0b46171145ab7415-bf4b2742)
[docs/schema/associationgroups-element-in-entity-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroups-element-in-entity-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroups-element-in-entity-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-c99f12a657cfa31e64e8348cc70e3205-bf4b2742)
[docs/schema/associationreference-element-in-associationgroup-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationreference-element-in-associationgroup-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationreference-element-in-associationgroup-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-d377fe9e9be22d93c75fac031f5d7b97-bf4b2742)
[docs/schema/associations-element-in-subscription-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associations-element-in-subscription-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associations-element-in-subscription-subscription-schema?branch=pr-en-us-8048) | [Details](#user-content-cbe15d5535db699a48b6f830f8f89dab-bf4b2742)
[docs/schema/associations-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associations-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associations-element?branch=pr-en-us-8048) | [Details](#user-content-e42cc056ba680fe61036759f83b25fec-bf4b2742)

<a id="ac4463bcc1820dd5292ce4bbab81ff0e-bf4b2742"></a>
### [docs/schema/assemblyredirect-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirect-element-workflowinfo.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs [...]

2022-06-07 18:19 UTC, mSarts commented on docs/schema/assemblyredirect-element-workflowinfo.md
>  manager: laurawi
Updated per request.

2022-06-07 18:21 UTC, mSarts commented
**Global effort to fix build validation errors**

@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-09 11:07 UTC, andrewconnell requested changes
Please review all files where the HTML tables are being updated... these should be converted to Markdown tables, not HTML if they're being changed.

Also, when you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 11:07 UTC, andrewconnell commented on docs/schema/association-element-in-associations-subscription-schema.md
> +<td align="left"><p><span><a href="localizeddisplaynames-element-in-metadataobject-subscription-schema.md">LocalizedDisplayNames element in MetadataObject (Subscription Schema)</a></span></p></td>
If this page is being updated:
- don't just remove the attribute, but remove the entire span
- but, it should be converted from an HTML table => Markdown table

2022-06-09 18:37 UTC, VesaJuvonen commented
Docs Build status updates of commit _[cb9c5ee](https://github.com/mSarts/sp-dev-docs/commits/cb9c5eef6e2b577b0bc794caf18a9260b6be56d9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/assemblyredirect-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirect-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirect-element-workflowinfo?branch=pr-en-us-8048) | [Details](#user-content-ac4463bcc1820dd5292ce4bbab81ff0e-55ac6064)
[docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirects-element-workflowinfo-elementaction4?branch=pr-en-us-8048) | [Details](#user-content-21d3c772741c4908f11dfd0179051614-55ac6064)
[docs/schema/assemblyredirects-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirects-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirects-element-workflowinfo?branch=pr-en-us-8048) | [Details](#user-content-a2fdccab038e7e8b6071b753fcadee98-55ac6064)
[docs/schema/assignment-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assignment-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assignment-element-deploymentmanifest?branch=pr-en-us-8048) | [Details](#user-content-4e7407b56eaffc8d86aaca1aaeaa3be9-55ac6064)
[docs/schema/association-element-in-associations-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-associations-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-associations-subscription-schema?branch=pr-en-us-8048) | [Details](#user-content-531920706d9e8da9ebb4f40c8cd01048-55ac6064)
[docs/schema/association-element-in-methodinstances-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-methodinstances-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-methodinstances-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-90a19b4f3072590c77f5f83a2b2a5ca8-55ac6064)
[docs/schema/association-element-in-methodinstances-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-methodinstances-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-methodinstances-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-0b9e5859cf4c6486445f7c83c2339085-55ac6064)
[docs/schema/association-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-workflowconfig?branch=pr-en-us-8048) | [Details](#user-content-c4da722cb66c275b79211e7b520b9240-55ac6064)
[docs/schema/association-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element?branch=pr-en-us-8048) | [Details](#user-content-6bdbb15b41a3008f51a9f6789ba5b97c-55ac6064)
[docs/schema/associationcategories-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationcategories-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationcategories-element-workflow?branch=pr-en-us-8048) | [Details](#user-content-8c31501e7f25523e67f24b9d2afefb38-55ac6064)
[docs/schema/associationdata-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationdata-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationdata-element-workflow?branch=pr-en-us-8048) | [Details](#user-content-412bba210646932f1a534b43edbc6cda-55ac6064)
[docs/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-47d647cddf563e24111329fd55af39fb-55ac6064)
[docs/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-f80586d7e48a5077fceb05a52e4fb3d7-55ac6064)
[docs/schema/associationgroups-element-in-entity-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroups-element-in-entity-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroups-element-in-entity-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-8060bd461ea07c2d0b46171145ab7415-55ac6064)
[docs/schema/associationgroups-element-in-entity-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroups-element-in-entity-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroups-element-in-entity-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-c99f12a657cfa31e64e8348cc70e3205-55ac6064)
[docs/schema/associationreference-element-in-associationgroup-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationreference-element-in-associationgroup-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationreference-element-in-associationgroup-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-d377fe9e9be22d93c75fac031f5d7b97-55ac6064)
[docs/schema/associations-element-in-subscription-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associations-element-in-subscription-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associations-element-in-subscription-subscription-schema?branch=pr-en-us-8048) | [Details](#user-content-cbe15d5535db699a48b6f830f8f89dab-55ac6064)
[docs/schema/associations-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associations-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associations-element?branch=pr-en-us-8048) | [Details](#user-content-e42cc056ba680fe61036759f83b25fec-55ac6064)

<a id="ac4463bcc1820dd5292ce4bbab81ff0e-55ac6064"></a>
### [docs/schema/assemblyredirect-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirect-element-workflowinfo.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs [...]

2022-06-09 18:59 UTC, mSarts commented
@andrewconnell 
Updated ms.date freshness and HTML tables to Markdown.

2022-06-10 22:06 UTC, RedZephyr13 commented on docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md
> +| Element information  | file  |
Let's capitalize "file" here.

2022-06-10 22:06 UTC, RedZephyr13 commented on docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md
> +| Element information  | file  |
Let's capitalize "file" here.

2022-06-13 13:36 UTC, mSarts commented on docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md
> +| Element information  | file  |
Addressed.

2022-06-13 13:36 UTC, mSarts commented on docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md
> +| Element information  | file  |
Addressed.

2022-06-13 13:40 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8fb4015](https://github.com/mSarts/sp-dev-docs/commits/8fb4015ce1485b1af34b6d7ed24174dace264932)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/assemblyredirect-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirect-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirect-element-workflowinfo?branch=pr-en-us-8048) | [Details](#user-content-ac4463bcc1820dd5292ce4bbab81ff0e-7193810a)
[docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirects-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirects-element-workflowinfo-elementaction4?branch=pr-en-us-8048) | [Details](#user-content-21d3c772741c4908f11dfd0179051614-7193810a)
[docs/schema/assemblyredirects-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirects-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assemblyredirects-element-workflowinfo?branch=pr-en-us-8048) | [Details](#user-content-a2fdccab038e7e8b6071b753fcadee98-7193810a)
[docs/schema/assignment-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assignment-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/assignment-element-deploymentmanifest?branch=pr-en-us-8048) | [Details](#user-content-4e7407b56eaffc8d86aaca1aaeaa3be9-7193810a)
[docs/schema/association-element-in-associations-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-associations-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-associations-subscription-schema?branch=pr-en-us-8048) | [Details](#user-content-531920706d9e8da9ebb4f40c8cd01048-7193810a)
[docs/schema/association-element-in-methodinstances-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-methodinstances-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-methodinstances-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-90a19b4f3072590c77f5f83a2b2a5ca8-7193810a)
[docs/schema/association-element-in-methodinstances-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-in-methodinstances-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-in-methodinstances-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-0b9e5859cf4c6486445f7c83c2339085-7193810a)
[docs/schema/association-element-workflowconfig.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element-workflowconfig.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element-workflowconfig?branch=pr-en-us-8048) | [Details](#user-content-c4da722cb66c275b79211e7b520b9240-7193810a)
[docs/schema/association-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/association-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/association-element?branch=pr-en-us-8048) | [Details](#user-content-6bdbb15b41a3008f51a9f6789ba5b97c-7193810a)
[docs/schema/associationcategories-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationcategories-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationcategories-element-workflow?branch=pr-en-us-8048) | [Details](#user-content-8c31501e7f25523e67f24b9d2afefb38-7193810a)
[docs/schema/associationdata-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationdata-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationdata-element-workflow?branch=pr-en-us-8048) | [Details](#user-content-412bba210646932f1a534b43edbc6cda-7193810a)
[docs/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroup-element-in-associationgroups-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-47d647cddf563e24111329fd55af39fb-7193810a)
[docs/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroup-element-in-associationgroups-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-f80586d7e48a5077fceb05a52e4fb3d7-7193810a)
[docs/schema/associationgroups-element-in-entity-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroups-element-in-entity-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroups-element-in-entity-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-8060bd461ea07c2d0b46171145ab7415-7193810a)
[docs/schema/associationgroups-element-in-entity-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationgroups-element-in-entity-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationgroups-element-in-entity-bdcmetadataresource-schema?branch=pr-en-us-8048) | [Details](#user-content-c99f12a657cfa31e64e8348cc70e3205-7193810a)
[docs/schema/associationreference-element-in-associationgroup-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associationreference-element-in-associationgroup-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associationreference-element-in-associationgroup-bdcmetadata-schema?branch=pr-en-us-8048) | [Details](#user-content-d377fe9e9be22d93c75fac031f5d7b97-7193810a)
[docs/schema/associations-element-in-subscription-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associations-element-in-subscription-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associations-element-in-subscription-subscription-schema?branch=pr-en-us-8048) | [Details](#user-content-cbe15d5535db699a48b6f830f8f89dab-7193810a)
[docs/schema/associations-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/associations-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/associations-element?branch=pr-en-us-8048) | [Details](#user-content-e42cc056ba680fe61036759f83b25fec-7193810a)

<a id="ac4463bcc1820dd5292ce4bbab81ff0e-7193810a"></a>
### [docs/schema/assemblyredirect-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/assemblyredirect-element-workflowinfo.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs [...]

2022-06-13 13:41 UTC, mSarts commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-20 09:24 UTC, andrewconnell approved these changes

2022-06-20 10:10 UTC, merged