BULK VALIDATION various fixes
SharePoint/sp-dev-docs pull request #8052
Opened 2022-06-07 19:57 UTC by mSarts

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

Validation issue fixes.

2022-06-07 19:58 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1ed9277](https://github.com/mSarts/sp-dev-docs/commits/1ed9277b8919cd2aeb19d423a80284e1860fb7b1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/attachment-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/attachment-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/attachment-element-deploymentmanifest?branch=pr-en-us-8052) | [Details](#user-content-16aae9269872ae047255b5dfff7b8f96-1879d565)
[docs/schema/attachments-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/attachments-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/attachments-element-deploymentmanifest?branch=pr-en-us-8052) | [Details](#user-content-e2ed7cc00fce0c30c3462cfc51610d5b-1879d565)
[docs/schema/authenticationdata-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/authenticationdata-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/authenticationdata-complextype-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-72ae00230304cbcd5a01b48a755c455f-1879d565)
[docs/schema/authenticationdata-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/authenticationdata-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/authenticationdata-element-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-43fd1ca35e429d8b28c571e58cf5c91d-1879d565)
[docs/schema/authenticationinformation-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/authenticationinformation-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/authenticationinformation-complextype-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-75903820bea060aa52b8ce7cf3f6a326-1879d565)
[docs/schema/authenticationinformation-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/authenticationinformation-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/authenticationinformation-element-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-8f1fd41e45bac515231c91a895c84f96-1879d565)
[docs/schema/authenticationtype-element-authenticationinformation-complextypesps15xsdsearchse.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/authenticationtype-element-authenticationinformation-complextypesps15xsdsearchse.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/authenticationtype-element-authenticationinformation-complextypesps15xsdsearchse?branch=pr-en-us-8052) | [Details](#user-content-14542ce9dc8f5207b13d361f72e77d9b-1879d565)
[docs/schema/authinfo-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/authinfo-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/authinfo-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8052) | [Details](#user-content-5439eb76101423ab4d81b2adc02401a3-1879d565)
[docs/schema/autodeployedwebapplication-element-appprincipaldefinition-complextypesharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/autodeployedwebapplication-element-appprincipaldefinition-complextypesharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/autodeployedwebapplication-element-appprincipaldefinition-complextypesharepoint?branch=pr-en-us-8052) | [Details](#user-content-820f5b86c9353d18878646e1c7d9d7b3-1879d565)
[docs/schema/autodeployedwebapplicationdebuginfoappurldefinition-simpletype-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/autodeployedwebapplicationdebuginfoappurldefinition-simpletype-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/autodeployedwebapplicationdebuginfoappurldefinition-simpletype-sharepoint-add-in?branch=pr-en-us-8052) | [Details](#user-content-206df31f8638a48fd5bc415946baa720-1879d565)
[docs/schema/autodeployedwebapplicationdebuginfodefinition-complextype-sharepoint-add-in-mani.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/autodeployedwebapplicationdebuginfodefinition-complextype-sharepoint-add-in-mani.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/autodeployedwebapplicationdebuginfodefinition-complextype-sharepoint-add-in-mani?branch=pr-en-us-8052) | [Details](#user-content-b398b024876b92d1c15763482c79254f-1879d565)
[docs/schema/baseinfo-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/baseinfo-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/baseinfo-complextype-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-ce20f18c426f331b2b86d076e9db2857-1879d565)
[docs/schema/baseinfo-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/baseinfo-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/baseinfo-element-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-e7ed912338752fd988becadc479713a7-1879d565)
[docs/schema/baseinfocollectionofaliasinfotzwwwpjw-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/baseinfocollectionofaliasinfotzwwwpjw-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/baseinfocollectionofaliasinfotzwwwpjw-complextype-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-a4373ce02c90446030080a42ade3cc09-1879d565)
[docs/schema/baseinfocollectionofaliasinfotzwwwpjw-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/baseinfocollectionofaliasinfotzwwwpjw-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/baseinfocollectionofaliasinfotzwwwpjw-element-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-26b6d13a230027a8874f1b35155f4c74-1879d565)
[docs/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-complextype-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-18f704b219bc1015b48478fbbe76724d-1879d565)
[docs/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/baseinfocollectionofcrawledpropertyinfotzwwwpjw-element-sps15xsdsearchset2?branch=pr-en-us-8052) | [Details](#user-content-858b847baa2fbac78d23794b75097287-1879d565)
[docs/schema/baseinfocollectionofmanagedpropertyinfotzwwwpjw-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main [...]

2022-06-07 20:07 UTC, RedZephyr13 commented on docs/schema/authenticationdata-element-sps15xsdsearchset2.md
> +description: AuthenticationData element (SPS15XSDSearchSet2) is an XML element.
For these articles that don't have much information in the intro paragraph, you can also use this format instead: "Learn about the AuthenticationData element (SPS15XSDSearchSet2)."

2022-06-07 20:12 UTC, mSarts commented
**Global effort to fix build validation errors**

@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-09 11:37 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 19:18 UTC, mSarts commented
@andrewconnell ms.date updated.

2022-06-13 14:23 UTC, mSarts commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-20 09:29 UTC, andrewconnell approved these changes

2022-06-20 10:10 UTC, merged