[Bulk] Validation: validation fixes JM 6/7b
SharePoint/sp-dev-docs pull request #8053
Opened 2022-06-07 20:00 UTC by jmart1428

This PR fixes 31 issues.

-missing descriptions
-duplicate descriptions
-column header missing
-disallowed HTML attribute

2022-06-07 20:54 UTC, jmart1428 commented
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-09 11:36 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 11:36 UTC, andrewconnell commented on docs/schema/children-element-in-container-layoutdefinitions-schema.md
> +<td align="left"><p><span><a href="obpart-element-in-arrayofobpart-layoutdefinitions-schema.md">OBPart element in ArrayOfOBPart (LayoutDefinitions Schema)</a></span></p></td>
When submitting changes to an HTML table, go ahead and convert to markdown.

2022-06-09 17:34 UTC, VesaJuvonen commented
Docs Build status updates of commit _[60f859a](https://github.com/jmart1428/sp-dev-docs/commits/60f859a408bf6bd6706a219a5491b9668d2a5703)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-a3c168bf7defeac96e0f42a66f60aa74-c63c08b1)
[docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8053) | [Details](#user-content-39e0a508958ddd4dade65b19b3d1d947-c63c08b1)
[docs/schema/business-connectivity-services-bcs-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/business-connectivity-services-bcs-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/business-connectivity-services-bcs-schemas?branch=pr-en-us-8053) | [Details](#user-content-e9e9da19873f37090d97230333374dc4-c63c08b1)
[docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-7e8b7a48172c43882768cf3285ae53f5-c63c08b1)
[docs/schema/calendarviewstyles-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspview?branch=pr-en-us-8053) | [Details](#user-content-58341932e80fe8b67fc978343a9d2762-c63c08b1)
[docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspwebpart?branch=pr-en-us-8053) | [Details](#user-content-f2678d070c022f2b132f552a99089103-c63c08b1)
[docs/schema/categories-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categories-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categories-element-workflow?branch=pr-en-us-8053) | [Details](#user-content-40d26b40465df88abdfd30003a5a1daa-c63c08b1)
[docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex?branch=pr-en-us-8053) | [Details](#user-content-fc371f5477a2a5f7ae0ff8d54be03205-c63c08b1)
[docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-4ce02d29c3d366b98c52333fee8c131a-c63c08b1)
[docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-b36bbf63bbcef394017694279b71ede6-c63c08b1)
[docs/schema/children-element-in-container-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/children-element-in-container-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/children-element-in-container-layoutdefinitions-schema?branch=pr-en-us-8053) | [Details](#user-content-adb049e9d93045945aa8def24cc69810-c63c08b1)
[docs/schema/class-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/class-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/class-element-event?branch=pr-en-us-8053) | [Details](#user-content-1326bef7d386d29fd0809b349a0f8447-c63c08b1)
[docs/schema/client-web-part-definition-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/client-web-part-definition-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/client-web-part-definition-schema?branch=pr-en-us-8053) | [Details](#user-content-4c131d44cd452d0f91d999ae1f8c97d9-c63c08b1)
[docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-67d6a22979825f5953f9e16e6c339dcf-c63c08b1)
[docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-63380ef6bc9c536ae34ac8381c379b12-c63c08b1)
[docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-bc36fcc960f90b164c12d767f7f1bfb5-c63c08b1)
[docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartenumitem-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-321b7043759ad7fa7e31737cfbf665f9-c63c08b1)

<a id="a3c168bf7defeac96e0f42a66f60aa74-c63c08b1"></a>
### [docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://rev [...]

2022-06-13 14:38 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8976471](https://github.com/jmart1428/sp-dev-docs/commits/89764714f27f9983ebfdacaf11bc36998e9107e0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-a3c168bf7defeac96e0f42a66f60aa74-06395383)
[docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8053) | [Details](#user-content-39e0a508958ddd4dade65b19b3d1d947-06395383)
[docs/schema/business-connectivity-services-bcs-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/business-connectivity-services-bcs-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/business-connectivity-services-bcs-schemas?branch=pr-en-us-8053) | [Details](#user-content-e9e9da19873f37090d97230333374dc4-06395383)
[docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-7e8b7a48172c43882768cf3285ae53f5-06395383)
[docs/schema/calendarviewstyles-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspview?branch=pr-en-us-8053) | [Details](#user-content-58341932e80fe8b67fc978343a9d2762-06395383)
[docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspwebpart?branch=pr-en-us-8053) | [Details](#user-content-f2678d070c022f2b132f552a99089103-06395383)
[docs/schema/categories-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categories-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categories-element-workflow?branch=pr-en-us-8053) | [Details](#user-content-40d26b40465df88abdfd30003a5a1daa-06395383)
[docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex?branch=pr-en-us-8053) | [Details](#user-content-fc371f5477a2a5f7ae0ff8d54be03205-06395383)
[docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-4ce02d29c3d366b98c52333fee8c131a-06395383)
[docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-b36bbf63bbcef394017694279b71ede6-06395383)
[docs/schema/children-element-in-container-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/children-element-in-container-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/children-element-in-container-layoutdefinitions-schema?branch=pr-en-us-8053) | [Details](#user-content-adb049e9d93045945aa8def24cc69810-06395383)
[docs/schema/class-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/class-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/class-element-event?branch=pr-en-us-8053) | [Details](#user-content-1326bef7d386d29fd0809b349a0f8447-06395383)
[docs/schema/client-web-part-definition-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/client-web-part-definition-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/client-web-part-definition-schema?branch=pr-en-us-8053) | [Details](#user-content-4c131d44cd452d0f91d999ae1f8c97d9-06395383)
[docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-67d6a22979825f5953f9e16e6c339dcf-06395383)
[docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-63380ef6bc9c536ae34ac8381c379b12-06395383)
[docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-bc36fcc960f90b164c12d767f7f1bfb5-06395383)
[docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartenumitem-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-321b7043759ad7fa7e31737cfbf665f9-06395383)

<a id="a3c168bf7defeac96e0f42a66f60aa74-06395383"></a>
### [docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://rev [...]

2022-06-13 18:32 UTC, RedZephyr13 commented on docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md
> +|--------------|-----------|-------------|
Please change to 2 column table.

2022-06-13 18:32 UTC, RedZephyr13 commented on docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md
> +| Element Type | Namespace | Schema File |
Please change to 2 column table.

2022-06-13 18:32 UTC, RedZephyr13 commented on docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md
> +|--------------|-----------|-------------|
Please change to 2 column table.

2022-06-13 18:35 UTC, RedZephyr13 commented on docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md
> +| Element Type | Namespace | Schema File |
Please change to 2 column table.

2022-06-13 18:35 UTC, RedZephyr13 commented on docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md
> +| Namespace | Schema File | Extension Base |
Please change to 2 column table.

2022-06-13 18:36 UTC, RedZephyr13 commented on docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md
> +| Namespace | Schema File | Extension Base |
Please change to 2 column table.

2022-06-13 19:39 UTC, VesaJuvonen commented
Docs Build status updates of commit _[af5c32a](https://github.com/jmart1428/sp-dev-docs/commits/af5c32a637878d5dac9b4a2c09fcbe76c97c9d96)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-a3c168bf7defeac96e0f42a66f60aa74-eb413795)
[docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8053) | [Details](#user-content-39e0a508958ddd4dade65b19b3d1d947-eb413795)
[docs/schema/business-connectivity-services-bcs-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/business-connectivity-services-bcs-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/business-connectivity-services-bcs-schemas?branch=pr-en-us-8053) | [Details](#user-content-e9e9da19873f37090d97230333374dc4-eb413795)
[docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-7e8b7a48172c43882768cf3285ae53f5-eb413795)
[docs/schema/calendarviewstyles-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspview?branch=pr-en-us-8053) | [Details](#user-content-58341932e80fe8b67fc978343a9d2762-eb413795)
[docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspwebpart?branch=pr-en-us-8053) | [Details](#user-content-f2678d070c022f2b132f552a99089103-eb413795)
[docs/schema/categories-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categories-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categories-element-workflow?branch=pr-en-us-8053) | [Details](#user-content-40d26b40465df88abdfd30003a5a1daa-eb413795)
[docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex?branch=pr-en-us-8053) | [Details](#user-content-fc371f5477a2a5f7ae0ff8d54be03205-eb413795)
[docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-4ce02d29c3d366b98c52333fee8c131a-eb413795)
[docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-b36bbf63bbcef394017694279b71ede6-eb413795)
[docs/schema/children-element-in-container-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/children-element-in-container-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/children-element-in-container-layoutdefinitions-schema?branch=pr-en-us-8053) | [Details](#user-content-adb049e9d93045945aa8def24cc69810-eb413795)
[docs/schema/class-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/class-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/class-element-event?branch=pr-en-us-8053) | [Details](#user-content-1326bef7d386d29fd0809b349a0f8447-eb413795)
[docs/schema/client-web-part-definition-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/client-web-part-definition-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/client-web-part-definition-schema?branch=pr-en-us-8053) | [Details](#user-content-4c131d44cd452d0f91d999ae1f8c97d9-eb413795)
[docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-67d6a22979825f5953f9e16e6c339dcf-eb413795)
[docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-63380ef6bc9c536ae34ac8381c379b12-eb413795)
[docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-bc36fcc960f90b164c12d767f7f1bfb5-eb413795)
[docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartenumitem-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-321b7043759ad7fa7e31737cfbf665f9-eb413795)

<a id="a3c168bf7defeac96e0f42a66f60aa74-eb413795"></a>
### [docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://rev [...]

2022-06-13 19:39 UTC, jmart1428 commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-20 09:38 UTC, andrewconnell requested changes
Don't create inconsistencies across the reference docs. In this PR, you're submitting changes to a table where some changes have the columns & rows transposed. Please be uniform across all reference docs.

2022-06-20 09:39 UTC, andrewconnell commented on docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md
> +| Element Type | Namespace | Schema File |
This is inconsistent with all other files in this PR... don't transpose rows=>columns. Default to what's already there in the docs.

2022-06-20 13:05 UTC, VesaJuvonen commented
Docs Build status updates of commit _[3993e29](https://github.com/jmart1428/sp-dev-docs/commits/3993e2961fdf3614717f74bc1b02950efef72b44)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-a3c168bf7defeac96e0f42a66f60aa74-eaf90e93)
[docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/builtin-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8053) | [Details](#user-content-39e0a508958ddd4dade65b19b3d1d947-eaf90e93)
[docs/schema/business-connectivity-services-bcs-schemas.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/business-connectivity-services-bcs-schemas.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/business-connectivity-services-bcs-schemas?branch=pr-en-us-8053) | [Details](#user-content-e9e9da19873f37090d97230333374dc4-eaf90e93)
[docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/button-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-7e8b7a48172c43882768cf3285ae53f5-eaf90e93)
[docs/schema/calendarviewstyles-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspview?branch=pr-en-us-8053) | [Details](#user-content-58341932e80fe8b67fc978343a9d2762-eaf90e93)
[docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/calendarviewstyles-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/calendarviewstyles-element-deploymentmanifestspwebpart?branch=pr-en-us-8053) | [Details](#user-content-f2678d070c022f2b132f552a99089103-eaf90e93)
[docs/schema/categories-element-workflow.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categories-element-workflow.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categories-element-workflow?branch=pr-en-us-8053) | [Details](#user-content-40d26b40465df88abdfd30003a5a1daa-eaf90e93)
[docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoriesandcrawledproperties-element-searchschemaconfigurationsettings-complex?branch=pr-en-us-8053) | [Details](#user-content-fc371f5477a2a5f7ae0ff8d54be03205-eaf90e93)
[docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/categoryname-element-crawledpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8053) | [Details](#user-content-4ce02d29c3d366b98c52333fee8c131a-eaf90e93)
[docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/checkbox-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-b36bbf63bbcef394017694279b71ede6-eaf90e93)
[docs/schema/children-element-in-container-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/children-element-in-container-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/children-element-in-container-layoutdefinitions-schema?branch=pr-en-us-8053) | [Details](#user-content-adb049e9d93045945aa8def24cc69810-eaf90e93)
[docs/schema/class-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/class-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/class-element-event?branch=pr-en-us-8053) | [Details](#user-content-1326bef7d386d29fd0809b349a0f8447-eaf90e93)
[docs/schema/client-web-part-definition-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/client-web-part-definition-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/client-web-part-definition-schema?branch=pr-en-us-8053) | [Details](#user-content-4c131d44cd452d0f91d999ae1f8c97d9-eaf90e93)
[docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpart-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-67d6a22979825f5953f9e16e6c339dcf-eaf90e93)
[docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontent-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-63380ef6bc9c536ae34ac8381c379b12-eaf90e93)
[docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartdefinitioncontenttype-simpletype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-bc36fcc960f90b164c12d767f7f1bfb5-eaf90e93)
[docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/clientwebpartenumitem-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/clientwebpartenumitem-complextype-apphostwebfeatures?branch=pr-en-us-8053) | [Details](#user-content-321b7043759ad7fa7e31737cfbf665f9-eaf90e93)

<a id="a3c168bf7defeac96e0f42a66f60aa74-eaf90e93"></a>
### [docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/builtin-element-resultitemtype-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://rev [...]

2022-06-20 19:28 UTC, andrewconnell approved these changes

2022-06-20 19:28 UTC, merged