Validation: fix multiple issues
SharePoint/sp-dev-docs pull request #8057
Opened 2022-06-07 23:05 UTC by LSchaufMS

## Category

- [X] Content fix
- [ ] New article

## Related issues

- no issue numbers; changes are part of the Validation cleanup efforts

## What's in this Pull Request?

This PR fixes 50 issues in 26 files.

2022-06-07 23:06 UTC, VesaJuvonen commented
Docs Build status updates of commit _[c92c134](https://github.com/LSchaufMS/sp-dev-docs/commits/c92c134dd79d184584b0efd4b7bd2432ee4ac4cd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-e2f91882f7e3d54ffed7fbfa07a6bfb3-76198806)
[docs/schema/commanduiextension-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) | [Details](#user-content-699e1b006b452eddba6a6f03258eebbf-76198806)
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-6b798d064ae2ffff76387d839a46c073-76198806)
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-355419b836a892fec256787cb4dae0af-76198806)
[docs/schema/commanduihandler-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) | [Details](#user-content-0dfa9b7122672a6cfd9b3fe6608813a7-76198806)
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-5ea0252dab169992554c632fac1a02e2-76198806)
[docs/schema/commanduihandlers-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) | [Details](#user-content-24da220033ccf806e4ee9c847effdbc7-76198806)
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-d837b1cbae627c37fcde488a6f7dce25-76198806)
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-7b4ac138cccd4ddedb564d10eba39cee-76198806)
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) | [Details](#user-content-7016c0c0c60b19fca33373bdc70d6f24-76198806)
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-c67718c1f5f75963366d51b426a68445-76198806)
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-c31079a1ff8daf1dae3903907a957d8b-76198806)
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-69e2f3442bb3fbed74db489389fe73b7-76198806)
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-b3109f9afc04b1376457f2b4547f03bd-76198806)
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-fb28b7cc238ffeb32c2fd9d37b0d40f1-76198806)
[docs/schema/condition-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-fc147106076c96771689f7289bf7952a-76198806)
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-017392895490f8e632f81e1301049e33-76198806)
[docs/schema/conditions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-75107088ea3f332cd89be6dfad218e3b-76198806)
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/connectiontimeout-element-source-complextypesps15xsdsearch [...]

2022-06-07 23:13 UTC, VesaJuvonen commented
Docs Build status updates of commit _[f5ee3b1](https://github.com/LSchaufMS/sp-dev-docs/commits/f5ee3b166d90c947eef330c64517f35162059eed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-e2f91882f7e3d54ffed7fbfa07a6bfb3-f815037c)
[docs/schema/commanduiextension-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) | [Details](#user-content-699e1b006b452eddba6a6f03258eebbf-f815037c)
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-6b798d064ae2ffff76387d839a46c073-f815037c)
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-355419b836a892fec256787cb4dae0af-f815037c)
[docs/schema/commanduihandler-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) | [Details](#user-content-0dfa9b7122672a6cfd9b3fe6608813a7-f815037c)
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-5ea0252dab169992554c632fac1a02e2-f815037c)
[docs/schema/commanduihandlers-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) | [Details](#user-content-24da220033ccf806e4ee9c847effdbc7-f815037c)
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-d837b1cbae627c37fcde488a6f7dce25-f815037c)
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-7b4ac138cccd4ddedb564d10eba39cee-f815037c)
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) | [Details](#user-content-7016c0c0c60b19fca33373bdc70d6f24-f815037c)
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-c67718c1f5f75963366d51b426a68445-f815037c)
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-c31079a1ff8daf1dae3903907a957d8b-f815037c)
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-69e2f3442bb3fbed74db489389fe73b7-f815037c)
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-b3109f9afc04b1376457f2b4547f03bd-f815037c)
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-fb28b7cc238ffeb32c2fd9d37b0d40f1-f815037c)
[docs/schema/condition-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-fc147106076c96771689f7289bf7952a-f815037c)
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-017392895490f8e632f81e1301049e33-f815037c)
[docs/schema/conditions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-75107088ea3f332cd89be6dfad218e3b-f815037c)
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/connectiontimeout-element-source-complextypesps15xsdsearch [...]

2022-06-07 23:26 UTC, dereklh7 commented on docs/schema/commanduihandler-element.md
> +description: Describes the CommandUIHandler element, which defines the handler for a command.
Too short per https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-seo-meta-description?branch=main.

2022-06-07 23:27 UTC, dereklh7 commented on docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md
> +description: Describes the CommandUIHandlers element (CommandUIExtensionType complexType), including element information, definition, attributes, and parent & child elements.
Too long per https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-seo-meta-description?branch=main.

2022-06-07 23:28 UTC, dereklh7 commented on docs/schema/condition-element-workflowinfo.md
> +description: A Condition element represents a Condition statement, which is part of a rule sentence that can be displayed in a declarative, rules-based, code-free workflow editor.
Too long per https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-seo-meta-description?branch=main.

2022-06-07 23:29 UTC, dereklh7 commented on docs/schema/conditions-element-workflowinfo-elementaction4.md
> +<p>**Example**: `&lt;Conditions And="and">`</p></td>
Not a huge deal, but the repo owner for this repo is preferring an alternative fix for these types of issues - so a better fix may be "\<Conditions And="and"\>".

2022-06-07 23:30 UTC, dereklh7 commented on docs/schema/conditions-element-workflowinfo-elementaction4.md
> +<p>**Example**: `&lt;Conditions Else="Else if">`</p></td>
Not a huge deal, but the repo owner for this repo is preferring an alternative fix for these types of issues - so a better fix may be "<Conditions Else="Else if">" and so on throughout this file.

2022-06-07 23:31 UTC, dereklh7 commented on docs/schema/conditions-element-workflowinfo.md
> +<p>`&lt;Conditions And="and">`</p></td>
I see in this file that you're opting to use the alternative fix with the back slashes - let's go ahead and be consistent with implementing the back slash fix throughout this file and PR.

2022-06-07 23:44 UTC, LSchaufMS commented
**Global effort to fix build validation errors**

@VesaJuvonen 

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-07 23:44 UTC, VesaJuvonen commented
Docs Build status updates of commit _[144a44f](https://github.com/LSchaufMS/sp-dev-docs/commits/144a44f8e1d43cce4f71eb927805c79cd63be41d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-e2f91882f7e3d54ffed7fbfa07a6bfb3-3e5e5cf1)
[docs/schema/commanduiextension-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) | [Details](#user-content-699e1b006b452eddba6a6f03258eebbf-3e5e5cf1)
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-6b798d064ae2ffff76387d839a46c073-3e5e5cf1)
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-355419b836a892fec256787cb4dae0af-3e5e5cf1)
[docs/schema/commanduihandler-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) | [Details](#user-content-0dfa9b7122672a6cfd9b3fe6608813a7-3e5e5cf1)
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-5ea0252dab169992554c632fac1a02e2-3e5e5cf1)
[docs/schema/commanduihandlers-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) | [Details](#user-content-24da220033ccf806e4ee9c847effdbc7-3e5e5cf1)
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-d837b1cbae627c37fcde488a6f7dce25-3e5e5cf1)
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-7b4ac138cccd4ddedb564d10eba39cee-3e5e5cf1)
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) | [Details](#user-content-7016c0c0c60b19fca33373bdc70d6f24-3e5e5cf1)
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-c67718c1f5f75963366d51b426a68445-3e5e5cf1)
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-c31079a1ff8daf1dae3903907a957d8b-3e5e5cf1)
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-69e2f3442bb3fbed74db489389fe73b7-3e5e5cf1)
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-b3109f9afc04b1376457f2b4547f03bd-3e5e5cf1)
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-fb28b7cc238ffeb32c2fd9d37b0d40f1-3e5e5cf1)
[docs/schema/condition-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-fc147106076c96771689f7289bf7952a-3e5e5cf1)
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-017392895490f8e632f81e1301049e33-3e5e5cf1)
[docs/schema/conditions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-75107088ea3f332cd89be6dfad218e3b-3e5e5cf1)
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/connectiontimeout-element-source-complextypesps15xsdsearch [...]

2022-06-09 11:30 UTC, andrewconnell requested changes
When submitting changes to an HTML table, go ahead and convert to markdown.

When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 11:30 UTC, andrewconnell commented on docs/schema/commanduihandler-element.md
> +<li><p>`{ItemUrl}` - Web-relative URL of the list item (Url).</p></li>
Convert HTML to markdown

2022-06-09 11:30 UTC, andrewconnell commented on docs/schema/conditions-element-workflowinfo.md
> +<p>`\<Conditions And="and">`</p></td>
Correct markdown escaping of angled brackets should be prefixed with `\`; don't change to the HTML encoding.

2022-06-09 11:30 UTC, andrewconnell commented on docs/schema/constantparameter-element-in-actionparameterdefinitions-solutionmanifestdeclarat.md
> +<td align="left"><p><span><a href="parameters-element-in-actiondefinition-solutionmanifestdeclarativeextensions-sch.md">Parameters element in ActionDefinition (SolutionManifestDeclarativeExtensions S
When submitting changes to an HTML table, go ahead and convert to markdown.

2022-06-09 11:30 UTC, andrewconnell commented on docs/schema/container-element-layoutdefinitions-schema.md
> +<td align="left"><p><span><a href="customproperties-element-in-uielement-layoutdefinitions-schema.md">CustomProperties element in UIelement (LayoutDefinitions schema)</a></span></p></td>
When submitting changes to an HTML table, go ahead and convert to markdown.

2022-06-09 15:10 UTC, VesaJuvonen commented
Docs Build status updates of commit _[462a3ee](https://github.com/LSchaufMS/sp-dev-docs/commits/462a3ee6e41912583663701e3a711ff5ab439483)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-e2f91882f7e3d54ffed7fbfa07a6bfb3-a7d789ad)
[docs/schema/commanduiextension-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) | [Details](#user-content-699e1b006b452eddba6a6f03258eebbf-a7d789ad)
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-6b798d064ae2ffff76387d839a46c073-a7d789ad)
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-355419b836a892fec256787cb4dae0af-a7d789ad)
[docs/schema/commanduihandler-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) | [Details](#user-content-0dfa9b7122672a6cfd9b3fe6608813a7-a7d789ad)
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-5ea0252dab169992554c632fac1a02e2-a7d789ad)
[docs/schema/commanduihandlers-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) | [Details](#user-content-24da220033ccf806e4ee9c847effdbc7-a7d789ad)
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-d837b1cbae627c37fcde488a6f7dce25-a7d789ad)
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-7b4ac138cccd4ddedb564d10eba39cee-a7d789ad)
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) | [Details](#user-content-7016c0c0c60b19fca33373bdc70d6f24-a7d789ad)
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-c67718c1f5f75963366d51b426a68445-a7d789ad)
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-c31079a1ff8daf1dae3903907a957d8b-a7d789ad)
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-69e2f3442bb3fbed74db489389fe73b7-a7d789ad)
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-b3109f9afc04b1376457f2b4547f03bd-a7d789ad)
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-fb28b7cc238ffeb32c2fd9d37b0d40f1-a7d789ad)
[docs/schema/condition-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-fc147106076c96771689f7289bf7952a-a7d789ad)
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-017392895490f8e632f81e1301049e33-a7d789ad)
[docs/schema/conditions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-75107088ea3f332cd89be6dfad218e3b-a7d789ad)
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/connectiontimeout-element-source-complextypesps15xsdsearch [...]

2022-06-10 16:16 UTC, VesaJuvonen commented
Docs Build status updates of commit _[07d3b5b](https://github.com/LSchaufMS/sp-dev-docs/commits/07d3b5bc29863892d776e920217e4872ab3c97a2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-e2f91882f7e3d54ffed7fbfa07a6bfb3-13571dad)
[docs/schema/commanduiextension-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) | [Details](#user-content-699e1b006b452eddba6a6f03258eebbf-13571dad)
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-6b798d064ae2ffff76387d839a46c073-13571dad)
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-355419b836a892fec256787cb4dae0af-13571dad)
[docs/schema/commanduihandler-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) | [Details](#user-content-0dfa9b7122672a6cfd9b3fe6608813a7-13571dad)
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-5ea0252dab169992554c632fac1a02e2-13571dad)
[docs/schema/commanduihandlers-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) | [Details](#user-content-24da220033ccf806e4ee9c847effdbc7-13571dad)
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-d837b1cbae627c37fcde488a6f7dce25-13571dad)
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-7b4ac138cccd4ddedb564d10eba39cee-13571dad)
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) | [Details](#user-content-7016c0c0c60b19fca33373bdc70d6f24-13571dad)
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-c67718c1f5f75963366d51b426a68445-13571dad)
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-c31079a1ff8daf1dae3903907a957d8b-13571dad)
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-69e2f3442bb3fbed74db489389fe73b7-13571dad)
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-b3109f9afc04b1376457f2b4547f03bd-13571dad)
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-fb28b7cc238ffeb32c2fd9d37b0d40f1-13571dad)
[docs/schema/condition-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-fc147106076c96771689f7289bf7952a-13571dad)
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-017392895490f8e632f81e1301049e33-13571dad)
[docs/schema/conditions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-75107088ea3f332cd89be6dfad218e3b-13571dad)
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/connectiontimeout-element-source-complextypesps15xsdsearch [...]

2022-06-10 16:27 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8aa86fc](https://github.com/LSchaufMS/sp-dev-docs/commits/8aa86fc342636c6cdf93c1ca2bc148d51e012493)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-e2f91882f7e3d54ffed7fbfa07a6bfb3-406ac6eb)
[docs/schema/commanduiextension-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextension-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) | [Details](#user-content-699e1b006b452eddba6a6f03258eebbf-406ac6eb)
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-6b798d064ae2ffff76387d839a46c073-406ac6eb)
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-355419b836a892fec256787cb4dae0af-406ac6eb)
[docs/schema/commanduihandler-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandler-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) | [Details](#user-content-0dfa9b7122672a6cfd9b3fe6608813a7-406ac6eb)
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-5ea0252dab169992554c632fac1a02e2-406ac6eb)
[docs/schema/commanduihandlers-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlers-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) | [Details](#user-content-24da220033ccf806e4ee9c847effdbc7-406ac6eb)
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-d837b1cbae627c37fcde488a6f7dce25-406ac6eb)
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-7b4ac138cccd4ddedb564d10eba39cee-406ac6eb)
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) | [Details](#user-content-7016c0c0c60b19fca33373bdc70d6f24-406ac6eb)
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-c67718c1f5f75963366d51b426a68445-406ac6eb)
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositestep-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-c31079a1ff8daf1dae3903907a957d8b-406ac6eb)
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-69e2f3442bb3fbed74db489389fe73b7-406ac6eb)
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/compositesteps-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-b3109f9afc04b1376457f2b4547f03bd-406ac6eb)
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-fb28b7cc238ffeb32c2fd9d37b0d40f1-406ac6eb)
[docs/schema/condition-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/condition-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-fc147106076c96771689f7289bf7952a-406ac6eb)
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-017392895490f8e632f81e1301049e33-406ac6eb)
[docs/schema/conditions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/conditions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-75107088ea3f332cd89be6dfad218e3b-406ac6eb)
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/connectiontimeout-element-source-complextypesps15xsdsearch [...]

2022-06-20 09:22 UTC, andrewconnell requested changes

2022-06-28 22:23 UTC, VesaJuvonen commented
Docs Build status updates of commit _[901d1e8](https://github.com/LSchaufMS/sp-dev-docs/commits/901d1e8118dd69f484930fab1708b8fec8f804db)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduiextension-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) | [Details](#user-content-699e1b006b452eddba6a6f03258eebbf-85867c58)
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-e2f91882f7e3d54ffed7fbfa07a6bfb3-85867c58)
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-6b798d064ae2ffff76387d839a46c073-85867c58)
[docs/schema/commanduihandler-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandler-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) | [Details](#user-content-0dfa9b7122672a6cfd9b3fe6608813a7-85867c58)
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-355419b836a892fec256787cb4dae0af-85867c58)
[docs/schema/commanduihandlers-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlers-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) | [Details](#user-content-24da220033ccf806e4ee9c847effdbc7-85867c58)
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-5ea0252dab169992554c632fac1a02e2-85867c58)
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-d837b1cbae627c37fcde488a6f7dce25-85867c58)
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) | [Details](#user-content-7b4ac138cccd4ddedb564d10eba39cee-85867c58)
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) | [Details](#user-content-7016c0c0c60b19fca33373bdc70d6f24-85867c58)
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-c67718c1f5f75963366d51b426a68445-85867c58)
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositestep-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-c31079a1ff8daf1dae3903907a957d8b-85867c58)
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositesteps-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-b3109f9afc04b1376457f2b4547f03bd-85867c58)
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-69e2f3442bb3fbed74db489389fe73b7-85867c58)
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-fb28b7cc238ffeb32c2fd9d37b0d40f1-85867c58)
[docs/schema/condition-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/condition-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-fc147106076c96771689f7289bf7952a-85867c58)
[docs/schema/conditions-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/conditions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) | [Details](#user-content-75107088ea3f332cd89be6dfad218e3b-85867c58)
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) | [Details](#user-content-017392895490f8e632f81e1301049e33-85867c58)
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/connectiontimeout-element-source-comple [...]

2022-06-28 22:24 UTC, LSchaufMS commented
Issue resolved - file pushed.

2022-06-29 10:13 UTC, andrewconnell commented
Please address all merge conflicts before we can review this PR.

2022-06-29 10:14 UTC, andrewconnell approved these changes

2022-06-29 10:15 UTC, andrewconnell requested changes
Please address all merge conflicts before we can review this PR.

2022-06-29 22:04 UTC, LSchaufMS commented
@andrewconnell Merge conflicts resolved.

2022-06-29 22:05 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a884b87](https://github.com/LSchaufMS/sp-dev-docs/commits/a884b87b6fd2a3582d485e208faaa744ba1ffa47)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/commanduiextension-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduiextension-element.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element?branch=pr-en-us-8057) |
[docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextension-element-customactiondefinition-complextypeapphostwebfeatures?branch=pr-en-us-8057) |
[docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduiextensiontype-complextype-apphostwebfeatures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduiextensiontype-complextype-apphostwebfeatures?branch=pr-en-us-8057) |
[docs/schema/commanduihandler-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandler-element.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element?branch=pr-en-us-8057) |
[docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandler-element-commanduihandlerstype-complextypeapphostwebfeatures?branch=pr-en-us-8057) |
[docs/schema/commanduihandlers-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlers-element.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element?branch=pr-en-us-8057) |
[docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlers-element-commanduiextensiontype-complextypeapphostwebfeatures?branch=pr-en-us-8057) |
[docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlerstype-complextype-apphostwebfeatures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlerstype-complextype-apphostwebfeatures?branch=pr-en-us-8057) |
[docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/commanduihandlertype-complextype-apphostwebfeatures.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/commanduihandlertype-complextype-apphostwebfeatures?branch=pr-en-us-8057) |
[docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/completematching-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8057) |
[docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-compositesteps-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) |
[docs/schema/compositestep-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositestep-element-workflowinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositestep-element-workflowinfo?branch=pr-en-us-8057) |
[docs/schema/compositesteps-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositesteps-element-workflowinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo?branch=pr-en-us-8057) |
[docs/schema/compositesteps-element-workflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/compositesteps-element-workflowinfo-elementaction4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/compositesteps-element-workflowinfo-elementaction4?branch=pr-en-us-8057) |
[docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/condition-element-conditions-elementworkflowinfo-elementaction4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-conditions-elementworkflowinfo-elementaction4?branch=pr-en-us-8057) |
[docs/schema/condition-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/condition-element-workflowinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/condition-element-workflowinfo?branch=pr-en-us-8057) |
[docs/schema/conditions-element-workflowinfo.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/conditions-element-workflowinfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo?branch=pr-en-us-8057) |
[docs/schema/conditions-element-workflowinfo-elementaction4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/conditions-element-workflowinfo-elementaction4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/conditions-element-workflowinfo-elementaction4?branch=pr-en-us-8057) |
[docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/connectiontimeout-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8057) |
[docs/schema/connectionurltemplate-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/connectionurltemplate-element-source-complextypesps15xsdsearchset1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/connectionurltemplate-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8057) |
[docs/schema/constantparameter-element-in-actionparameterdefinitions-solutionmanifestdeclarat.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0607/docs/schema/constantparameter-element-in-actionparameterdefinitions-solutionmanifestdeclarat.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/constantparameter-elemen [...]

2022-06-30 14:29 UTC, merged