Validation fixes
SharePoint/sp-dev-docs pull request #8060
Opened 2022-06-08 13:01 UTC by chrisms86

## Category

- [x] Content fix
- [ ] New article

## Related issues

- fixes # 29

## What's in this Pull Request?

Validation fixes including converting tables to Markdown

## Submission guidelines

2022-06-08 19:04 UTC, chrisms86 commented
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-09 11:28 UTC, andrewconnell requested changes
When submitting changes to an HTML table, go ahead and convert to markdown.

When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 11:28 UTC, andrewconnell commented on docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md
> +<td align="left"><p><a href="contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec.md">ContextEventHandlers Element in DeclarativeContextDefinition (SolutionManifestDeclara
When submitting changes to an HTML table, go ahead and convert to markdown.

2022-06-09 11:28 UTC, andrewconnell commented on docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md
> +<td align="left"><p><a href="entities-element-in-contextdefinition-solutionmanifestdefinitions-schema.md">Entities Element in ContextDefinition (SolutionManifestDefinitions Schema)</a></p></td>
When submitting changes to an HTML table, go ahead and convert to markdown.

2022-06-09 14:04 UTC, chrisms86 commented
@andrewconnell edited tables have been converted to markdown, please review. Thank you

2022-06-09 14:05 UTC, VesaJuvonen commented
Docs Build status updates of commit _[bce8af6](https://github.com/chrisms86/sp-dev-docs/commits/bce8af6dc57b1e242fbf81650441865a50fb101e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8060) | [Details](#user-content-e52e1b6b180e9c098a505bee4c708453-92cd6e35)
[docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex?branch=pr-en-us-8060) | [Details](#user-content-e406aec68af4ab7840702ecbc40b2f8e-92cd6e35)
[docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions?branch=pr-en-us-8060) | [Details](#user-content-490f7ab197c3c0cdebb21b199da171a6-92cd6e35)
[docs/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini?branch=pr-en-us-8060) | [Details](#user-content-452d4cb7ac46b1288b5d30ab4f097d88-92cd6e35)
[docs/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition?branch=pr-en-us-8060) | [Details](#user-content-30d166e46c1f7e129fa95c269783c0fd-92cd6e35)
[docs/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec?branch=pr-en-us-8060) | [Details](#user-content-b56a38163342efedb3621c624086d738-92cd6e35)
[docs/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-f006622525ae75299c6f68778ec3cff5-92cd6e35)
[docs/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-67e093ad90778427b7d35d2f60ce0f32-92cd6e35)
[docs/schema/control-element-delegate-control.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/control-element-delegate-control.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/control-element-delegate-control?branch=pr-en-us-8060) | [Details](#user-content-870ba0cda6dd3b1c879a9cfc031ef9fa-92cd6e35)
[docs/schema/controls-element-commanduidefinition.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-commanduidefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-commanduidefinition?branch=pr-en-us-8060) | [Details](#user-content-35835e3f33daa0547902da2cc0007f26-92cd6e35)
[docs/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-536f8f072a47cc477adb0a972e564598-92cd6e35)
[docs/schema/controls-element-group.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-group?branch=pr-en-us-8060) | [Details](#user-content-7d255982f5637b4605609dba0341019f-92cd6e35)
[docs/schema/converttype-element-in-interpretation-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/converttype-element-in-interpretation-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/converttype-element-in-interpretation-bdcmetadata-schema?branch=pr-en-us-8060) | [Details](#user-content-ac6b7ba5508b60b1006a9e803817966a-92cd6e35)

<a id="e52e1b6b180e9c098a505bee4c708453-92cd6e35"></a>
### [docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e406aec68af4ab7840702ecbc40b2f8e-92cd6e35"></a>
### [docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="490f7ab197c3c0cdebb21b199da171a6-92cd6e35"></a>
### [docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** ````` [...]

2022-06-09 15:09 UTC, chrisms86 commented
@andrewconnell please disregard previous comment, I need to make ms.date changes before you review again

2022-06-09 16:21 UTC, VesaJuvonen commented
Docs Build status updates of commit _[e2fbd65](https://github.com/chrisms86/sp-dev-docs/commits/e2fbd6569df822c43244207676312ce4f5599899)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8060) | [Details](#user-content-e52e1b6b180e9c098a505bee4c708453-7fea2c8f)
[docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex?branch=pr-en-us-8060) | [Details](#user-content-e406aec68af4ab7840702ecbc40b2f8e-7fea2c8f)
[docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions?branch=pr-en-us-8060) | [Details](#user-content-490f7ab197c3c0cdebb21b199da171a6-7fea2c8f)
[docs/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini?branch=pr-en-us-8060) | [Details](#user-content-452d4cb7ac46b1288b5d30ab4f097d88-7fea2c8f)
[docs/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition?branch=pr-en-us-8060) | [Details](#user-content-30d166e46c1f7e129fa95c269783c0fd-7fea2c8f)
[docs/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec?branch=pr-en-us-8060) | [Details](#user-content-b56a38163342efedb3621c624086d738-7fea2c8f)
[docs/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-f006622525ae75299c6f68778ec3cff5-7fea2c8f)
[docs/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-67e093ad90778427b7d35d2f60ce0f32-7fea2c8f)
[docs/schema/control-element-delegate-control.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/control-element-delegate-control.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/control-element-delegate-control?branch=pr-en-us-8060) | [Details](#user-content-870ba0cda6dd3b1c879a9cfc031ef9fa-7fea2c8f)
[docs/schema/controls-element-commanduidefinition.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-commanduidefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-commanduidefinition?branch=pr-en-us-8060) | [Details](#user-content-35835e3f33daa0547902da2cc0007f26-7fea2c8f)
[docs/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-536f8f072a47cc477adb0a972e564598-7fea2c8f)
[docs/schema/controls-element-group.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-group?branch=pr-en-us-8060) | [Details](#user-content-7d255982f5637b4605609dba0341019f-7fea2c8f)
[docs/schema/converttype-element-in-interpretation-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/converttype-element-in-interpretation-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/converttype-element-in-interpretation-bdcmetadata-schema?branch=pr-en-us-8060) | [Details](#user-content-ac6b7ba5508b60b1006a9e803817966a-7fea2c8f)

<a id="e52e1b6b180e9c098a505bee4c708453-7fea2c8f"></a>
### [docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e406aec68af4ab7840702ecbc40b2f8e-7fea2c8f"></a>
### [docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="490f7ab197c3c0cdebb21b199da171a6-7fea2c8f"></a>
### [docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** ````` [...]

2022-06-14 11:39 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b1dc9bf](https://github.com/chrisms86/sp-dev-docs/commits/b1dc9bfa16bb33385ded373822fbaea21ae26114)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8060) | [Details](#user-content-e52e1b6b180e9c098a505bee4c708453-d3197486)
[docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex?branch=pr-en-us-8060) | [Details](#user-content-e406aec68af4ab7840702ecbc40b2f8e-d3197486)
[docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions?branch=pr-en-us-8060) | [Details](#user-content-490f7ab197c3c0cdebb21b199da171a6-d3197486)
[docs/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinitiongroup-element-in-contextdefinitiongroups-solutionmanifestdefini?branch=pr-en-us-8060) | [Details](#user-content-452d4cb7ac46b1288b5d30ab4f097d88-d3197486)
[docs/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextdefinitiongroups-element-in-solutiondefinition-solutionmanifestdefinition?branch=pr-en-us-8060) | [Details](#user-content-30d166e46c1f7e129fa95c269783c0fd-d3197486)
[docs/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contexteventhandlers-element-in-declarativecontextdefinition-solutionmanifestdec?branch=pr-en-us-8060) | [Details](#user-content-b56a38163342efedb3621c624086d738-d3197486)
[docs/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextualgroup-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-f006622525ae75299c6f68778ec3cff5-d3197486)
[docs/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/contextualtabs-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-67e093ad90778427b7d35d2f60ce0f32-d3197486)
[docs/schema/control-element-delegate-control.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/control-element-delegate-control.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/control-element-delegate-control?branch=pr-en-us-8060) | [Details](#user-content-870ba0cda6dd3b1c879a9cfc031ef9fa-d3197486)
[docs/schema/controls-element-commanduidefinition.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-commanduidefinition.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-commanduidefinition?branch=pr-en-us-8060) | [Details](#user-content-35835e3f33daa0547902da2cc0007f26-d3197486)
[docs/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-commanduidefinitiontype-complextypeapphostwebfeatures?branch=pr-en-us-8060) | [Details](#user-content-536f8f072a47cc477adb0a972e564598-d3197486)
[docs/schema/controls-element-group.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/controls-element-group.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/controls-element-group?branch=pr-en-us-8060) | [Details](#user-content-7d255982f5637b4605609dba0341019f-d3197486)
[docs/schema/converttype-element-in-interpretation-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/converttype-element-in-interpretation-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/converttype-element-in-interpretation-bdcmetadata-schema?branch=pr-en-us-8060) | [Details](#user-content-ac6b7ba5508b60b1006a9e803817966a-d3197486)

<a id="e52e1b6b180e9c098a505bee4c708453-d3197486"></a>
### [docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/context-element-managedpropertyinfo-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e406aec68af4ab7840702ecbc40b2f8e-d3197486"></a>
### [docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdeactivated-element-in-contexteventhandlers-solutionmanifestdeclarativeex.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="490f7ab197c3c0cdebb21b199da171a6-d3197486"></a>
### [docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/contextdefinition-element-in-contextdefinitiongroup-solutionmanifestdefinitions.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** ````` [...]

2022-06-14 14:32 UTC, chrisms86 commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-20 10:11 UTC, merged