Validation fixes
SharePoint/sp-dev-docs pull request #8067
Opened 2022-06-08 17:53 UTC by chrisms86

## Category

- [ x] Content fix

2022-06-08 17:55 UTC, VesaJuvonen commented
Docs Build status updates of commit _[6a189c1](https://github.com/chrisms86/sp-dev-docs/commits/6a189c1d0605f0277e1ccb09b5877be82df8188a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-2600a97948e7a662dbf4ebeb087aafbd-17e4f666)
[docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-51eb6d96c56f4f442cd1dbcecb7febd3-17e4f666)
[docs/schema/customaction-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element?branch=pr-en-us-8067) | [Details](#user-content-77ce99f08062164c514de613cd372973-17e4f666)
[docs/schema/customactiongroup-element-custom-action.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactiongroup-element-custom-action.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactiongroup-element-custom-action?branch=pr-en-us-8067) | [Details](#user-content-64b65348ff4177bf584bdecf427af1fe-17e4f666)
[docs/schema/customactionlocations-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionlocations-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionlocations-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eaf2c1bf98510e4d3651ca88f0af1318-17e4f666)
[docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionregistrationtype-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eb54bc612446be48611e3e3c2770458f-17e4f666)
[docs/schema/customization-element-list.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customization-element-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customization-element-list?branch=pr-en-us-8067) | [Details](#user-content-637250a342e82ddffa5f1b34ff9e5bf9-17e4f666)
[docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperties-element-in-uielement-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-c6bb8f257048728659826f09dcadca42-17e4f666)
[docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-a05cadda9e44cd1d4d41db7a4ca21cab-17e4f666)
[docs/schema/customupgradeaction-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customupgradeaction-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customupgradeaction-element-feature?branch=pr-en-us-8067) | [Details](#user-content-920cc7feac7ec3b83d49529103f2fe8c-17e4f666)
[docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-00b3b6c232a0ee200fbd5d9ca5c57ce4-17e4f666)
[docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e724d444493f5c5a802ecb44962426ed-17e4f666)
[docs/schema/data-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-event?branch=pr-en-us-8067) | [Details](#user-content-11984849dc756c185fb0c6d6154dc036-17e4f666)
[docs/schema/data-element-list-instance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-list-instance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-list-instance?branch=pr-en-us-8067) | [Details](#user-content-11e37310d46917fce4debc1833f12b8c-17e4f666)
[docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e9e064efbeaf9434f6661f964aa3f35a-17e4f666)

<a id="2600a97948e7a662dbf4ebeb087aafbd-17e4f666"></a>
### [docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="51eb6d96c56f4f442cd1dbcecb7febd3-17e4f666"></a>
### [docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="77ce99f08062164c514de613cd372973-17e4f666"></a>
### [docs/schema/customaction-element.md](https://github.com/SharePoint/sp-de [...]

2022-06-08 19:04 UTC, chrisms86 commented
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-09 11:18 UTC, andrewconnell requested changes
If updating the HTML table, convert it to markdown.

When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 11:18 UTC, andrewconnell commented on docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md
> +<td align="left"><p><a href="customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md">CustomProperty Element in ArrayOfCustomProperty (LayoutDefinitions Schema)</a></p></td>
If changing the HTML table, convert it to markdown

2022-06-09 14:51 UTC, VesaJuvonen commented
Docs Build status updates of commit _[3d093f7](https://github.com/chrisms86/sp-dev-docs/commits/3d093f75ac341a7dd844d66a2bb770ad9cd41f18)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-2600a97948e7a662dbf4ebeb087aafbd-e08f0140)
[docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-51eb6d96c56f4f442cd1dbcecb7febd3-e08f0140)
[docs/schema/customaction-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element?branch=pr-en-us-8067) | [Details](#user-content-77ce99f08062164c514de613cd372973-e08f0140)
[docs/schema/customactiongroup-element-custom-action.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactiongroup-element-custom-action.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactiongroup-element-custom-action?branch=pr-en-us-8067) | [Details](#user-content-64b65348ff4177bf584bdecf427af1fe-e08f0140)
[docs/schema/customactionlocations-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionlocations-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionlocations-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eaf2c1bf98510e4d3651ca88f0af1318-e08f0140)
[docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionregistrationtype-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eb54bc612446be48611e3e3c2770458f-e08f0140)
[docs/schema/customization-element-list.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customization-element-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customization-element-list?branch=pr-en-us-8067) | [Details](#user-content-637250a342e82ddffa5f1b34ff9e5bf9-e08f0140)
[docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperties-element-in-uielement-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-c6bb8f257048728659826f09dcadca42-e08f0140)
[docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-a05cadda9e44cd1d4d41db7a4ca21cab-e08f0140)
[docs/schema/customupgradeaction-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customupgradeaction-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customupgradeaction-element-feature?branch=pr-en-us-8067) | [Details](#user-content-920cc7feac7ec3b83d49529103f2fe8c-e08f0140)
[docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-00b3b6c232a0ee200fbd5d9ca5c57ce4-e08f0140)
[docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e724d444493f5c5a802ecb44962426ed-e08f0140)
[docs/schema/data-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-event?branch=pr-en-us-8067) | [Details](#user-content-11984849dc756c185fb0c6d6154dc036-e08f0140)
[docs/schema/data-element-list-instance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-list-instance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-list-instance?branch=pr-en-us-8067) | [Details](#user-content-11e37310d46917fce4debc1833f12b8c-e08f0140)
[docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e9e064efbeaf9434f6661f964aa3f35a-e08f0140)

<a id="2600a97948e7a662dbf4ebeb087aafbd-e08f0140"></a>
### [docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="51eb6d96c56f4f442cd1dbcecb7febd3-e08f0140"></a>
### [docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="77ce99f08062164c514de613cd372973-e08f0140"></a>
### [docs/schema/customaction-element.md](https://github.com/SharePoint/sp-de [...]

2022-06-09 16:31 UTC, VesaJuvonen commented
Docs Build status updates of commit _[eea1a5e](https://github.com/chrisms86/sp-dev-docs/commits/eea1a5e2b534223b93054e73adcec615d25c30d5)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-2600a97948e7a662dbf4ebeb087aafbd-05a6de04)
[docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-51eb6d96c56f4f442cd1dbcecb7febd3-05a6de04)
[docs/schema/customaction-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element?branch=pr-en-us-8067) | [Details](#user-content-77ce99f08062164c514de613cd372973-05a6de04)
[docs/schema/customactiongroup-element-custom-action.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactiongroup-element-custom-action.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactiongroup-element-custom-action?branch=pr-en-us-8067) | [Details](#user-content-64b65348ff4177bf584bdecf427af1fe-05a6de04)
[docs/schema/customactionlocations-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionlocations-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionlocations-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eaf2c1bf98510e4d3651ca88f0af1318-05a6de04)
[docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionregistrationtype-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eb54bc612446be48611e3e3c2770458f-05a6de04)
[docs/schema/customization-element-list.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customization-element-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customization-element-list?branch=pr-en-us-8067) | [Details](#user-content-637250a342e82ddffa5f1b34ff9e5bf9-05a6de04)
[docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperties-element-in-uielement-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-c6bb8f257048728659826f09dcadca42-05a6de04)
[docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-a05cadda9e44cd1d4d41db7a4ca21cab-05a6de04)
[docs/schema/customupgradeaction-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customupgradeaction-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customupgradeaction-element-feature?branch=pr-en-us-8067) | [Details](#user-content-920cc7feac7ec3b83d49529103f2fe8c-05a6de04)
[docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-00b3b6c232a0ee200fbd5d9ca5c57ce4-05a6de04)
[docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e724d444493f5c5a802ecb44962426ed-05a6de04)
[docs/schema/data-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-event?branch=pr-en-us-8067) | [Details](#user-content-11984849dc756c185fb0c6d6154dc036-05a6de04)
[docs/schema/data-element-list-instance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-list-instance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-list-instance?branch=pr-en-us-8067) | [Details](#user-content-11e37310d46917fce4debc1833f12b8c-05a6de04)
[docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e9e064efbeaf9434f6661f964aa3f35a-05a6de04)

<a id="2600a97948e7a662dbf4ebeb087aafbd-05a6de04"></a>
### [docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="51eb6d96c56f4f442cd1dbcecb7febd3-05a6de04"></a>
### [docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="77ce99f08062164c514de613cd372973-05a6de04"></a>
### [docs/schema/customaction-element.md](https://github.com/SharePoint/sp-de [...]

2022-06-13 21:11 UTC, RedZephyr13 commented on docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md
> +**Element type**: CustomActionDefinition
We've been directed to keep Markdown tables as tables. You can use "Information/Location" or "Name/Value" as headers, or if you find a more specific header that fits, use that.

2022-06-14 12:13 UTC, VesaJuvonen commented
Docs Build status updates of commit _[4aa0dc9](https://github.com/chrisms86/sp-dev-docs/commits/4aa0dc9a16d787432adaade6e56a7737b90d5b2c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-2600a97948e7a662dbf4ebeb087aafbd-a3d6d6e9)
[docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-51eb6d96c56f4f442cd1dbcecb7febd3-a3d6d6e9)
[docs/schema/customaction-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element?branch=pr-en-us-8067) | [Details](#user-content-77ce99f08062164c514de613cd372973-a3d6d6e9)
[docs/schema/customactiongroup-element-custom-action.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactiongroup-element-custom-action.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactiongroup-element-custom-action?branch=pr-en-us-8067) | [Details](#user-content-64b65348ff4177bf584bdecf427af1fe-a3d6d6e9)
[docs/schema/customactionlocations-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionlocations-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionlocations-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eaf2c1bf98510e4d3651ca88f0af1318-a3d6d6e9)
[docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionregistrationtype-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eb54bc612446be48611e3e3c2770458f-a3d6d6e9)
[docs/schema/customization-element-list.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customization-element-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customization-element-list?branch=pr-en-us-8067) | [Details](#user-content-637250a342e82ddffa5f1b34ff9e5bf9-a3d6d6e9)
[docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperties-element-in-uielement-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-c6bb8f257048728659826f09dcadca42-a3d6d6e9)
[docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-a05cadda9e44cd1d4d41db7a4ca21cab-a3d6d6e9)
[docs/schema/customupgradeaction-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customupgradeaction-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customupgradeaction-element-feature?branch=pr-en-us-8067) | [Details](#user-content-920cc7feac7ec3b83d49529103f2fe8c-a3d6d6e9)
[docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-00b3b6c232a0ee200fbd5d9ca5c57ce4-a3d6d6e9)
[docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e724d444493f5c5a802ecb44962426ed-a3d6d6e9)
[docs/schema/data-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-event?branch=pr-en-us-8067) | [Details](#user-content-11984849dc756c185fb0c6d6154dc036-a3d6d6e9)
[docs/schema/data-element-list-instance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-list-instance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-list-instance?branch=pr-en-us-8067) | [Details](#user-content-11e37310d46917fce4debc1833f12b8c-a3d6d6e9)
[docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e9e064efbeaf9434f6661f964aa3f35a-a3d6d6e9)

<a id="2600a97948e7a662dbf4ebeb087aafbd-a3d6d6e9"></a>
### [docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="51eb6d96c56f4f442cd1dbcecb7febd3-a3d6d6e9"></a>
### [docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="77ce99f08062164c514de613cd372973-a3d6d6e9"></a>
### [docs/schema/customaction-element.md](https://github.com/SharePoint/sp-de [...]

2022-06-14 12:17 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8625b21](https://github.com/chrisms86/sp-dev-docs/commits/8625b2138f9a23ccb4180ab7fcc1c1953e62ba9d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-2600a97948e7a662dbf4ebeb087aafbd-5c50c036)
[docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-51eb6d96c56f4f442cd1dbcecb7febd3-5c50c036)
[docs/schema/customaction-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element?branch=pr-en-us-8067) | [Details](#user-content-77ce99f08062164c514de613cd372973-5c50c036)
[docs/schema/customactiongroup-element-custom-action.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactiongroup-element-custom-action.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactiongroup-element-custom-action?branch=pr-en-us-8067) | [Details](#user-content-64b65348ff4177bf584bdecf427af1fe-5c50c036)
[docs/schema/customactionlocations-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionlocations-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionlocations-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eaf2c1bf98510e4d3651ca88f0af1318-5c50c036)
[docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionregistrationtype-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eb54bc612446be48611e3e3c2770458f-5c50c036)
[docs/schema/customization-element-list.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customization-element-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customization-element-list?branch=pr-en-us-8067) | [Details](#user-content-637250a342e82ddffa5f1b34ff9e5bf9-5c50c036)
[docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperties-element-in-uielement-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-c6bb8f257048728659826f09dcadca42-5c50c036)
[docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-a05cadda9e44cd1d4d41db7a4ca21cab-5c50c036)
[docs/schema/customupgradeaction-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customupgradeaction-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customupgradeaction-element-feature?branch=pr-en-us-8067) | [Details](#user-content-920cc7feac7ec3b83d49529103f2fe8c-5c50c036)
[docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-00b3b6c232a0ee200fbd5d9ca5c57ce4-5c50c036)
[docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e724d444493f5c5a802ecb44962426ed-5c50c036)
[docs/schema/data-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-event?branch=pr-en-us-8067) | [Details](#user-content-11984849dc756c185fb0c6d6154dc036-5c50c036)
[docs/schema/data-element-list-instance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-list-instance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-list-instance?branch=pr-en-us-8067) | [Details](#user-content-11e37310d46917fce4debc1833f12b8c-5c50c036)
[docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e9e064efbeaf9434f6661f964aa3f35a-5c50c036)

<a id="2600a97948e7a662dbf4ebeb087aafbd-5c50c036"></a>
### [docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="51eb6d96c56f4f442cd1dbcecb7febd3-5c50c036"></a>
### [docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="77ce99f08062164c514de613cd372973-5c50c036"></a>
### [docs/schema/customaction-element.md](https://github.com/SharePoint/sp-de [...]

2022-06-14 12:20 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b636f5e](https://github.com/chrisms86/sp-dev-docs/commits/b636f5ed04b03edbc19cd4aa13a58e6f7246009c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-2600a97948e7a662dbf4ebeb087aafbd-b6adc5e5)
[docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-51eb6d96c56f4f442cd1dbcecb7febd3-b6adc5e5)
[docs/schema/customaction-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customaction-element?branch=pr-en-us-8067) | [Details](#user-content-77ce99f08062164c514de613cd372973-b6adc5e5)
[docs/schema/customactiongroup-element-custom-action.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactiongroup-element-custom-action.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactiongroup-element-custom-action?branch=pr-en-us-8067) | [Details](#user-content-64b65348ff4177bf584bdecf427af1fe-b6adc5e5)
[docs/schema/customactionlocations-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionlocations-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionlocations-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eaf2c1bf98510e4d3651ca88f0af1318-b6adc5e5)
[docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customactionregistrationtype-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customactionregistrationtype-simpletype-apphostwebfeatures?branch=pr-en-us-8067) | [Details](#user-content-eb54bc612446be48611e3e3c2770458f-b6adc5e5)
[docs/schema/customization-element-list.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customization-element-list.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customization-element-list?branch=pr-en-us-8067) | [Details](#user-content-637250a342e82ddffa5f1b34ff9e5bf9-b6adc5e5)
[docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperties-element-in-uielement-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperties-element-in-uielement-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-c6bb8f257048728659826f09dcadca42-b6adc5e5)
[docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customproperty-element-in-arrayofcustomproperty-layoutdefinitions-schema?branch=pr-en-us-8067) | [Details](#user-content-a05cadda9e44cd1d4d41db7a4ca21cab-b6adc5e5)
[docs/schema/customupgradeaction-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customupgradeaction-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/customupgradeaction-element-feature?branch=pr-en-us-8067) | [Details](#user-content-920cc7feac7ec3b83d49529103f2fe8c-b6adc5e5)
[docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/cutoffmaxbuckets-element-refinerconfiguration-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-00b3b6c232a0ee200fbd5d9ca5c57ce4-b6adc5e5)
[docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-authenticationinformation-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e724d444493f5c5a802ecb44962426ed-b6adc5e5)
[docs/schema/data-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-event?branch=pr-en-us-8067) | [Details](#user-content-11984849dc756c185fb0c6d6154dc036-b6adc5e5)
[docs/schema/data-element-list-instance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/data-element-list-instance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/data-element-list-instance?branch=pr-en-us-8067) | [Details](#user-content-11e37310d46917fce4debc1833f12b8c-b6adc5e5)
[docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/databaseid-element-searchobjectowner-complextypesps15xsdsearchset2?branch=pr-en-us-8067) | [Details](#user-content-e9e064efbeaf9434f6661f964aa3f35a-b6adc5e5)

<a id="2600a97948e7a662dbf4ebeb087aafbd-b6adc5e5"></a>
### [docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-customactiondefinitions-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="51eb6d96c56f4f442cd1dbcecb7febd3-b6adc5e5"></a>
### [docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/customaction-element-elementdefinitioncollection-complextypeapphostwebfeatures.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="77ce99f08062164c514de613cd372973-b6adc5e5"></a>
### [docs/schema/customaction-element.md](https://github.com/SharePoint/sp-de [...]

2022-06-14 14:33 UTC, chrisms86 commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-20 09:57 UTC, andrewconnell approved these changes

2022-06-20 10:11 UTC, merged