[Bulk] Validation: validation fixes JM 6/8c
SharePoint/sp-dev-docs pull request #8074
Opened 2022-06-08 20:13 UTC by jmart1428

This PR fixes 29 issues.

-missing descriptions
-duplicate descriptions
-column headers

2022-06-08 20:32 UTC, jmart1428 commented
**Global effort to fix build validation errors**
@VesaJuvonen 
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-09 11:15 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-09 15:23 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1590717](https://github.com/jmart1428/sp-dev-docs/commits/1590717a83ed0efd9459d4500acdbc6b721d4e8c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/manifestfiles-element-deploymentsystemdata.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifestfiles-element-deploymentsystemdata.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/manifestfiles-element-deploymentsystemdata?branch=pr-en-us-8074) | [Details](#user-content-4b0630694b9cf1bf33a975da800f2fac-07d01056)
[docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/manifesturi-simpletype-sharepoint-add-in-manifest?branch=pr-en-us-8074) | [Details](#user-content-245fa63f87c602630942b75b51499b1e-07d01056)
[docs/schema/mapfile-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mapfile-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mapfile-element-feature?branch=pr-en-us-8074) | [Details](#user-content-81425967a958bc90c11575ae8f2e444a-07d01056)
[docs/schema/mappedcrawledproperties-element-managedpropertyinfo-complextypesps15xsdsearchset.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappedcrawledproperties-element-managedpropertyinfo-complextypesps15xsdsearchset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappedcrawledproperties-element-managedpropertyinfo-complextypesps15xsdsearchset?branch=pr-en-us-8074) | [Details](#user-content-3d1188d5a942ce3c3dde35d30de37ed9-07d01056)
[docs/schema/mappedmanagedproperties-element-crawledpropertyinfo-complextypesps15xsdsearchset.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappedmanagedproperties-element-crawledpropertyinfo-complextypesps15xsdsearchset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappedmanagedproperties-element-crawledpropertyinfo-complextypesps15xsdsearchset?branch=pr-en-us-8074) | [Details](#user-content-03b346bbed8430b2c43ac90d43f93ca2-07d01056)
[docs/schema/mappingdisallowed-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappingdisallowed-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappingdisallowed-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-9661c79f453a654940a0a1d8bd95681a-07d01056)
[docs/schema/mappinginfo-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfo-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfo-complextype-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-faf0f365ff745cff7e5a2e15db453921-07d01056)
[docs/schema/mappinginfo-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfo-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfo-element-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-1626c8212434b4bda3f6bc549774aa29-07d01056)
[docs/schema/mappinginfocollection-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfocollection-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfocollection-complextype-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-1ed192fe4c2a991b1be129539370d0ea-07d01056)
[docs/schema/mappinginfocollection-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfocollection-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfocollection-element-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-144e732e27e3a0a6d11b89822f145233-07d01056)
[docs/schema/mappingorder-element-mappinginfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappingorder-element-mappinginfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappingorder-element-mappinginfo-complextypesps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-58f1dafaf9820a34ab679c62a216fdeb-07d01056)
[docs/schema/mappings-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappings-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappings-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3?branch=pr-en-us-8074) | [Details](#user-content-161c0d66e26811cabfd6cb3df0aee85c-07d01056)
[docs/schema/mappingsoverridden-element-overrideinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappingsoverridden-element-overrideinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappingsoverridden-element-overrideinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-62a94e04021fbad52b8ce733a8b60351-07d01056)
[docs/schema/maptocontenttype-element-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/maptocontenttype-element-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/maptocontenttype-element-view?branch=pr-en-us-8074) | [Details](#user-content-520f7d7f68675e7225de61e9796a5645-07d01056)
[docs/schema/matchingoptions-element-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/matchingoptions-element-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/matchingoptions-element-sps15xsdsearchset4?branch=pr-en-us-8074) | [Details](#user-content-48c8e54161674dbe43a8836040b74cc9-07d01056)
[docs/schema/matchingoptions-simpletype-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/matchingoptions-simpletype-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/matchingoptions-simpletype-sps15xsdsearchset4?branch=pr-en-us-8074) | [Details](#user-content-e63b60288d4873d3e9e377b13caf709f-07d01056)

<a id="4b0630694b9cf1bf33a975da800f2fac-07d01056"></a>
### [docs/schema/manifestfiles-element-deploymentsystemdata.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifestfiles-element-deploymentsystemdata.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="245fa63f87c602630942b75b51499b1e-07d01056"></a>
### [docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service [...]

2022-06-13 17:50 UTC, VesaJuvonen commented
Docs Build status updates of commit _[eb5c718](https://github.com/jmart1428/sp-dev-docs/commits/eb5c7181d1f983254f9a1d58915144f92fc7c9d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/manifestfiles-element-deploymentsystemdata.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifestfiles-element-deploymentsystemdata.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/manifestfiles-element-deploymentsystemdata?branch=pr-en-us-8074) | [Details](#user-content-4b0630694b9cf1bf33a975da800f2fac-f2aa558d)
[docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/manifesturi-simpletype-sharepoint-add-in-manifest?branch=pr-en-us-8074) | [Details](#user-content-245fa63f87c602630942b75b51499b1e-f2aa558d)
[docs/schema/mapfile-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mapfile-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mapfile-element-feature?branch=pr-en-us-8074) | [Details](#user-content-81425967a958bc90c11575ae8f2e444a-f2aa558d)
[docs/schema/mappedcrawledproperties-element-managedpropertyinfo-complextypesps15xsdsearchset.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappedcrawledproperties-element-managedpropertyinfo-complextypesps15xsdsearchset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappedcrawledproperties-element-managedpropertyinfo-complextypesps15xsdsearchset?branch=pr-en-us-8074) | [Details](#user-content-3d1188d5a942ce3c3dde35d30de37ed9-f2aa558d)
[docs/schema/mappedmanagedproperties-element-crawledpropertyinfo-complextypesps15xsdsearchset.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappedmanagedproperties-element-crawledpropertyinfo-complextypesps15xsdsearchset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappedmanagedproperties-element-crawledpropertyinfo-complextypesps15xsdsearchset?branch=pr-en-us-8074) | [Details](#user-content-03b346bbed8430b2c43ac90d43f93ca2-f2aa558d)
[docs/schema/mappingdisallowed-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappingdisallowed-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappingdisallowed-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-9661c79f453a654940a0a1d8bd95681a-f2aa558d)
[docs/schema/mappinginfo-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfo-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfo-complextype-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-faf0f365ff745cff7e5a2e15db453921-f2aa558d)
[docs/schema/mappinginfo-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfo-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfo-element-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-1626c8212434b4bda3f6bc549774aa29-f2aa558d)
[docs/schema/mappinginfocollection-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfocollection-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfocollection-complextype-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-1ed192fe4c2a991b1be129539370d0ea-f2aa558d)
[docs/schema/mappinginfocollection-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappinginfocollection-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappinginfocollection-element-sps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-144e732e27e3a0a6d11b89822f145233-f2aa558d)
[docs/schema/mappingorder-element-mappinginfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappingorder-element-mappinginfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappingorder-element-mappinginfo-complextypesps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-58f1dafaf9820a34ab679c62a216fdeb-f2aa558d)
[docs/schema/mappings-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappings-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappings-element-searchschemaconfigurationsettings-complextypesps15xsdsearchset3?branch=pr-en-us-8074) | [Details](#user-content-161c0d66e26811cabfd6cb3df0aee85c-f2aa558d)
[docs/schema/mappingsoverridden-element-overrideinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/mappingsoverridden-element-overrideinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/mappingsoverridden-element-overrideinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8074) | [Details](#user-content-62a94e04021fbad52b8ce733a8b60351-f2aa558d)
[docs/schema/maptocontenttype-element-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/maptocontenttype-element-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/maptocontenttype-element-view?branch=pr-en-us-8074) | [Details](#user-content-520f7d7f68675e7225de61e9796a5645-f2aa558d)
[docs/schema/matchingoptions-element-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/matchingoptions-element-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/matchingoptions-element-sps15xsdsearchset4?branch=pr-en-us-8074) | [Details](#user-content-48c8e54161674dbe43a8836040b74cc9-f2aa558d)
[docs/schema/matchingoptions-simpletype-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/matchingoptions-simpletype-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/matchingoptions-simpletype-sps15xsdsearchset4?branch=pr-en-us-8074) | [Details](#user-content-e63b60288d4873d3e9e377b13caf709f-f2aa558d)

<a id="4b0630694b9cf1bf33a975da800f2fac-f2aa558d"></a>
### [docs/schema/manifestfiles-element-deploymentsystemdata.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifestfiles-element-deploymentsystemdata.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="245fa63f87c602630942b75b51499b1e-f2aa558d"></a>
### [docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/manifesturi-simpletype-sharepoint-add-in-manifest.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service [...]

2022-06-14 18:56 UTC, jmart1428 commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-20 10:03 UTC, andrewconnell approved these changes

2022-06-20 10:11 UTC, merged