fixing broken links
SharePoint/sp-dev-docs pull request #8089
Opened 2022-06-09 17:48 UTC by DhurataJ

## Category

- [x] Content fix
- [ ] New article

## Related issues
- fixes 32

## What's in this Pull Request?
Broken link fixes such as:
- path changed links, 
- example, should not be clickable
- fine name changed

2022-06-09 17:50 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b0a06e0](https://github.com/DhurataJ/sp-dev-docs/commits/b0a06e0f9beaa3b68bc696196a6d69e9037eba45)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-74ffd4ae)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-74ffd4ae)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-74ffd4ae)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-74ffd4ae)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-74ffd4ae)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-74ffd4ae)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-74ffd4ae)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-74ffd4ae)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-74ffd4ae)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-74ffd4ae)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-74ffd4ae)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-74ffd4ae)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-74ffd4ae)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-74ffd4ae)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-74ffd4ae)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-74ffd4ae)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-20 19:59 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-20 23:57 UTC, VesaJuvonen commented
Docs Build status updates of commit _[428bac1](https://github.com/DhurataJ/sp-dev-docs/commits/428bac1c38ddfe98375e620506ccd536a1a9ca99)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-335d721c)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-335d721c)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-335d721c)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-335d721c)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-335d721c)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-335d721c)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-335d721c)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-335d721c)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-335d721c)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-335d721c)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-335d721c)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-335d721c)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-335d721c)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-335d721c)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-335d721c)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-335d721c)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-20 23:59 UTC, VesaJuvonen commented
Docs Build status updates of commit _[6456848](https://github.com/DhurataJ/sp-dev-docs/commits/645684845778872f338dd6301915e591b2f1abe7)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-baa4aa59)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-baa4aa59)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-baa4aa59)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-baa4aa59)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-baa4aa59)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-baa4aa59)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-baa4aa59)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-baa4aa59)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-baa4aa59)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-baa4aa59)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-baa4aa59)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-baa4aa59)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-baa4aa59)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-baa4aa59)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-baa4aa59)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-baa4aa59)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:00 UTC, VesaJuvonen commented
Docs Build status updates of commit _[2a9606e](https://github.com/DhurataJ/sp-dev-docs/commits/2a9606e3f71ff8c674178f0903cf3334ce289400)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-0369727b)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-0369727b)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-0369727b)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-0369727b)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-0369727b)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-0369727b)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-0369727b)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-0369727b)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-0369727b)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-0369727b)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-0369727b)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-0369727b)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-0369727b)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-0369727b)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-0369727b)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-0369727b)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:04 UTC, VesaJuvonen commented
Docs Build status updates of commit _[91f6b5d](https://github.com/DhurataJ/sp-dev-docs/commits/91f6b5dc7eec71d8ebf383d0c3c53f10f8288057)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-90633348)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-90633348)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-90633348)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-90633348)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-90633348)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-90633348)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-90633348)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-90633348)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-90633348)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-90633348)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-90633348)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-90633348)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-90633348)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-90633348)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-90633348)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-90633348)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:06 UTC, VesaJuvonen commented
Docs Build status updates of commit _[82db559](https://github.com/DhurataJ/sp-dev-docs/commits/82db5592b1c49d2fed4cb07030f063c60673804a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-96fdac87)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-96fdac87)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-96fdac87)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-96fdac87)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-96fdac87)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-96fdac87)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-96fdac87)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-96fdac87)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-96fdac87)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-96fdac87)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-96fdac87)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-96fdac87)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-96fdac87)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-96fdac87)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-96fdac87)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-96fdac87)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:07 UTC, VesaJuvonen commented
Docs Build status updates of commit _[7061381](https://github.com/DhurataJ/sp-dev-docs/commits/7061381723358b63433a07382a12e6b53b7c1adc)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-16fb195b)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-16fb195b)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-16fb195b)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-16fb195b)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-16fb195b)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-16fb195b)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-16fb195b)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-16fb195b)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-16fb195b)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-16fb195b)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-16fb195b)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-16fb195b)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-16fb195b)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-16fb195b)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-16fb195b)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-16fb195b)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:09 UTC, VesaJuvonen commented
Docs Build status updates of commit _[73573b6](https://github.com/DhurataJ/sp-dev-docs/commits/73573b657ca533598fade06389d8199e182b7da8)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-e195a9a6)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-e195a9a6)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-e195a9a6)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-e195a9a6)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-e195a9a6)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-e195a9a6)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-e195a9a6)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-e195a9a6)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-e195a9a6)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-e195a9a6)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-e195a9a6)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-e195a9a6)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-e195a9a6)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-e195a9a6)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-e195a9a6)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-e195a9a6)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:11 UTC, VesaJuvonen commented
Docs Build status updates of commit _[256b92a](https://github.com/DhurataJ/sp-dev-docs/commits/256b92a53bc21e0f765005fb3409f229742cea4a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-fc2af200)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-fc2af200)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-fc2af200)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-fc2af200)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-fc2af200)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-fc2af200)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-fc2af200)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-fc2af200)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-fc2af200)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-fc2af200)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-fc2af200)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-fc2af200)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-fc2af200)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-fc2af200)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-fc2af200)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-fc2af200)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:11 UTC, VesaJuvonen commented
Docs Build status updates of commit _[05e0782](https://github.com/DhurataJ/sp-dev-docs/commits/05e07826bd0ec106b066e56e2490557b3931a1c6)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5afb40ae)

<a id="5afb40ae"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210009078137-8089/BuildReport?accessString=a55b527274c50805e7c74361a3acfe246ae00682b378055e75929cd38a6fee33).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:12 UTC, VesaJuvonen commented
Docs Build status updates of commit _[bef244c](https://github.com/DhurataJ/sp-dev-docs/commits/bef244c0b7938068e76283148d3d22ea2f9ebdac)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-5d89ea30)

<a id="5d89ea30"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210010102540-8089/BuildReport?accessString=802b4bd640650b90a5a34a8a82c4369aee306d38cf6ec5b2d353ad7aa8c6e693).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:13 UTC, VesaJuvonen commented
Docs Build status updates of commit _[67e02d7](https://github.com/DhurataJ/sp-dev-docs/commits/67e02d77ac0a012f0a1141620b54d264226e5713)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4f0eceba)

<a id="4f0eceba"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210012520408-8089/BuildReport?accessString=613c5c562ce27d3465d5eb2e5ef1336d6522c3d87722ae0aa77842bee426a017).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:14 UTC, VesaJuvonen commented
Docs Build status updates of commit _[eacdddf](https://github.com/DhurataJ/sp-dev-docs/commits/eacdddfb42163b14be57f7809b57b18994ebf2e9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-448d96f1)

<a id="448d96f1"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210013320349-8089/BuildReport?accessString=4e856aa61f084a029e879ba21b2c8f3e11c0de77be4a94000561a6b1c587f949).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:15 UTC, VesaJuvonen commented
Docs Build status updates of commit _[c452efb](https://github.com/DhurataJ/sp-dev-docs/commits/c452efba7683d3a00b99b526d141681c61b60c97)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4fffaf9c)

<a id="4fffaf9c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210009311698-8089/BuildReport?accessString=238613ba73b0cf4ac8754a1ecdf0d419729631a116d2e3290c7c033cb692109f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:15 UTC, VesaJuvonen commented
Docs Build status updates of commit _[29014f4](https://github.com/DhurataJ/sp-dev-docs/commits/29014f49c18f3f979ce2fde83f5f34366cace920)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-32aab3d5)

<a id="32aab3d5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210008513524-8089/BuildReport?accessString=fe6c49f86d60a960639d375d5da12671dae670ec221edbfb6fa7cefb7cbfe819).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:16 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5810106](https://github.com/DhurataJ/sp-dev-docs/commits/5810106015c4c485e292f60b5697e466158e66f4)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-af42a902)

<a id="af42a902"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210014203899-8089/BuildReport?accessString=7c8f8c76f72e5d91f9584af466cb3f6577fd2c4ec62a4ff76a5cb872d8c2c748).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:17 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0f74b33](https://github.com/DhurataJ/sp-dev-docs/commits/0f74b33022f7399ff8c43c8dd35b3758c1f38325)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-cd950db9)

<a id="cd950db9"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210014541051-8089/BuildReport?accessString=a42914347178659ab2937adfceeebf9447bae9414aa4e4070b5232cf5b69e421).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:17 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a8f440d](https://github.com/DhurataJ/sp-dev-docs/commits/a8f440dc1a0a20060a5535fd6ec3893ae739c704)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-582f8be0)

<a id="582f8be0"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210015517277-8089/BuildReport?accessString=915c8a0893a7c84eb349e82e3d58e36da10aacd5617529d9799940a1dfbf091b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:18 UTC, VesaJuvonen commented
Docs Build status updates of commit _[ab92c64](https://github.com/DhurataJ/sp-dev-docs/commits/ab92c64450c3ce106983cf8cfa52dbfa7d9b86ae)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-93810677)

<a id="93810677"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210016322355-8089/BuildReport?accessString=daf81749bd7cbb23f66f0883d0a1e10c5dc9b2e1952b507110ef0b31727560e9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:18 UTC, VesaJuvonen commented
Docs Build status updates of commit _[65ec516](https://github.com/DhurataJ/sp-dev-docs/commits/65ec51646997b4b543bc0fd9eb019575145d38aa)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-2289a964)

<a id="2289a964"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210010313265-8089/BuildReport?accessString=1b0538654db1e302751eff8770f8987e02e69b62536d8db123008520b97c72bf).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:19 UTC, VesaJuvonen commented
Docs Build status updates of commit _[3177b5e](https://github.com/DhurataJ/sp-dev-docs/commits/3177b5e867b987fea5e481c28cc91eba81e7a804)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b9678178)

<a id="b9678178"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210015152121-8089/BuildReport?accessString=cb5189492958b11b8f3b24d6e9de3f56991c44ab79b2bee818808c9677325beb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:19 UTC, VesaJuvonen commented
Docs Build status updates of commit _[6dadab6](https://github.com/DhurataJ/sp-dev-docs/commits/6dadab623438339f9968dc5895718772f3f44317)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-800b5286)

<a id="800b5286"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210013499630-8089/BuildReport?accessString=56699ee62de2e176db04fbee68627f4b92cdb0116b2e95e4ed1cf6d3fb52a2a8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:20 UTC, VesaJuvonen commented
Docs Build status updates of commit _[291b4d8](https://github.com/DhurataJ/sp-dev-docs/commits/291b4d8463c99ade2a3eda677488f89f279aced0)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f3f9e4b6)

<a id="f3f9e4b6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210015321385-8089/BuildReport?accessString=7642194ad157e9ebcb94461ee10fa3e4e126086ebdbd5aeaa0e17dd2aac34bff).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:21 UTC, VesaJuvonen commented
Docs Build status updates of commit _[3a27ff8](https://github.com/DhurataJ/sp-dev-docs/commits/3a27ff8504b72415d91178701f987f5b41fcbb72)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-9282043d)

<a id="9282043d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210016485372-8089/BuildReport?accessString=8df95256b633ab391f0c95e3ea3a98472a61cb24fa0c0d3181d6a8cc9561075e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:21 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8b9af99](https://github.com/DhurataJ/sp-dev-docs/commits/8b9af99160fa7c0d04b7b4808802f326850f5df5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-099b5976)

<a id="099b5976"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210017294232-8089/BuildReport?accessString=db7eed1d28c8126544c349484e23631948ff10af07d5a4af68c643d191572f50).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:22 UTC, VesaJuvonen commented
Docs Build status updates of commit _[d584639](https://github.com/DhurataJ/sp-dev-docs/commits/d58463912b5e31b412113b0376e9c78af1ea6366)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-658c43ea)

<a id="658c43ea"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210017469046-8089/BuildReport?accessString=089af2e9d0d378284d8eda41d8f9cf0d8875810668d76e362111bb78563ea4ba).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:22 UTC, VesaJuvonen commented
Docs Build status updates of commit _[20eef5d](https://github.com/DhurataJ/sp-dev-docs/commits/20eef5d891db85b7f2c107662b5758e40f5b9156)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a9cc0197)

<a id="a9cc0197"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210019286281-8089/BuildReport?accessString=c23ca78e8e29e1b72be713c187fa8faa0f50edd9aeccaee9f22d188d5efa6b8a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:23 UTC, VesaJuvonen commented
Docs Build status updates of commit _[35e77e1](https://github.com/DhurataJ/sp-dev-docs/commits/35e77e1eb7dce29e8d0854ce39a05ea1e052e81b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7fba9e51)

<a id="7fba9e51"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210017082083-8089/BuildReport?accessString=17ba3c065619102bfe6482cc54cfbbc4b13fd80b48627eb13bbc52b4db447fd9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:23 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5e7ecdd](https://github.com/DhurataJ/sp-dev-docs/commits/5e7ecdd3c648ea35c2c34d3c48785f3ce1e017b9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-7dc6fae8)

<a id="7dc6fae8"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210018102204-8089/BuildReport?accessString=1d9483ed7f12494fe847d523ded0654d20601e66f0b6e5a09db9ca963a10679f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:24 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5e6950a](https://github.com/DhurataJ/sp-dev-docs/commits/5e6950ae1e624927aa09861c9c14fa415fd98d38)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b7e1d54c)

<a id="b7e1d54c"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210013142740-8089/BuildReport?accessString=568656da7ab336a33c39ec07d39f56d5134bed751e0edfd971c2e01a97c2fe0e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:25 UTC, VesaJuvonen commented
Docs Build status updates of commit _[9f332dc](https://github.com/DhurataJ/sp-dev-docs/commits/9f332dca8e91a881b83381aa40fb224a03124f50)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-233559f6)

<a id="233559f6"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210016084976-8089/BuildReport?accessString=39879d06a5187f01fd9fa3bbdcd2584f2beffe7309ff83081d304f6bf604634f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:25 UTC, VesaJuvonen commented
Docs Build status updates of commit _[3ece080](https://github.com/DhurataJ/sp-dev-docs/commits/3ece08014a325da1736767067e834d61308d8b0b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-4a368057)

<a id="4a368057"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210021409611-8089/BuildReport?accessString=38ce7fa2cd2a40f7b2b509806cf2c45acb329fda367f75023e99c07863df8d5a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:26 UTC, VesaJuvonen commented
Docs Build status updates of commit _[992b25e](https://github.com/DhurataJ/sp-dev-docs/commits/992b25eb1ecaa4827ff5c84f9f13e4d6d2c8a451)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-75fe2050)

<a id="75fe2050"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210020042601-8089/BuildReport?accessString=e8759f92d811a9a8942d79a3bf0ae188250ee1158ae70f624aa723a2767d1e4c).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:26 UTC, VesaJuvonen commented
Docs Build status updates of commit _[08e5d1f](https://github.com/DhurataJ/sp-dev-docs/commits/08e5d1f4886f238399fab8e98fe99690555c1a9c)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-a2e9981d)

<a id="a2e9981d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210025458014-8089/BuildReport?accessString=033017c2c94c6936b4ae5d03162656578ef8ea2c40ddce6445a462aacba08ab9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:27 UTC, VesaJuvonen commented
Docs Build status updates of commit _[53a0ab6](https://github.com/DhurataJ/sp-dev-docs/commits/53a0ab6b63c067ef914d548b2cae26307ec68dc7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-206ec4f3)

<a id="206ec4f3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210023170361-8089/BuildReport?accessString=4e4cd9db4f904e8021c996bd6b7474e804058f6daa5f0c0e1edf36515f810644).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:28 UTC, VesaJuvonen commented
Docs Build status updates of commit _[917b03a](https://github.com/DhurataJ/sp-dev-docs/commits/917b03a3be9c980d3db719e9f8999236ef54cb94)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-c8cde5f3)

<a id="c8cde5f3"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210020536381-8089/BuildReport?accessString=f41d8364ced619d8871b74b0c5236c527d333a6c81c278eea91a0357b46fb92f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:28 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8fd7dfb](https://github.com/DhurataJ/sp-dev-docs/commits/8fd7dfbd4c9c50302dc0f5fa191bcc6d27aded6d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e9299e75)

<a id="e9299e75"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210026567141-8089/BuildReport?accessString=57b8c2de6f6c02555772e45cc704d96c28d0ef11261a1014b78a785b488eae8a).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:29 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a6f0d1b](https://github.com/DhurataJ/sp-dev-docs/commits/a6f0d1b52f6e7eddcf4b27705d1365b5b9891f36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-c1ff21c8)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-c1ff21c8)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-c1ff21c8)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-c1ff21c8)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-c1ff21c8)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-c1ff21c8)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-c1ff21c8)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-c1ff21c8)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-c1ff21c8)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-c1ff21c8)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-c1ff21c8)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-c1ff21c8)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-c1ff21c8)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-c1ff21c8)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-c1ff21c8)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-c1ff21c8)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 00:30 UTC, VesaJuvonen commented
Docs Build status updates of commit _[688b7d9](https://github.com/DhurataJ/sp-dev-docs/commits/688b7d92aa5ffbf6803e7792c6a230ddaadaa09b)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-1fb3a81d)

<a id="1fb3a81d"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210024399935-8089/BuildReport?accessString=32d7dff56d639c5e949e8be6ac1a328142f0a30c01beceb9c5131aba206830b0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:31 UTC, VesaJuvonen commented
Docs Build status updates of commit _[c059809](https://github.com/DhurataJ/sp-dev-docs/commits/c0598095df3385e5b6aab82527b8764249280c62)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d2ee5c12)

<a id="d2ee5c12"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210026216109-8089/BuildReport?accessString=a41e25170146703a1eed52e697dcff47da3f16a0b5625abac09200e6ba0182d0).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:32 UTC, VesaJuvonen commented
Docs Build status updates of commit _[ce7ebf8](https://github.com/DhurataJ/sp-dev-docs/commits/ce7ebf8fa9b1d5c6b9b8d97836671b2da3186562)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-6014f460)

<a id="6014f460"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206210027333993-8089/BuildReport?accessString=86982b488a1140e84e72c70d9d8d107d65a22207fa71febec146633ea9880dab).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-21 00:33 UTC, VesaJuvonen commented
Docs Build status updates of commit _[a6f0d1b](https://github.com/DhurataJ/sp-dev-docs/commits/a6f0d1b52f6e7eddcf4b27705d1365b5b9891f36)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-9682806d)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-9682806d)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-9682806d)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-9682806d)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-9682806d)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-9682806d)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-9682806d)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-9682806d)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-9682806d)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-9682806d)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-9682806d)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-9682806d)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-9682806d)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-9682806d)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-9682806d)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-9682806d)
[docs/general-development/how-to-implement-business-logic-and-data-validation-in-a-windows-phone [...]

2022-06-21 09:59 UTC, andrewconnell requested changes

2022-06-21 09:59 UTC, andrewconnell commented on docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md
>  ---
Line 2, Column 1: [Suggestion: description-missing - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/description-missing?branch=main)] Missing required attribute: 'description'.

2022-06-21 13:59 UTC, VesaJuvonen commented
Docs Build status updates of commit _[9def0dc](https://github.com/DhurataJ/sp-dev-docs/commits/9def0dc45284b733fec700c5c5aac6b743abff1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/migration-api-overview.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/apis/migration-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/migration-api-overview?branch=pr-en-us-8089) | [Details](#user-content-7d41cc3f9025bf2ec49e9c8580fbb3a3-1432ce92)
[docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/access-sharepoint-from-mobile-and-native-device-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/access-sharepoint-from-mobile-and-native-device-apps?branch=pr-en-us-8089) | [Details](#user-content-0842ac3c5a7d8f4a0a8b70cb62539114-1432ce92)
[docs/general-development/build-windows-phone-apps-that-access-sharepoint.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/build-windows-phone-apps-that-access-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/build-windows-phone-apps-that-access-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-8dedea273ca6023ebe6b9ce58fc44b11-1432ce92)
[docs/general-development/color-palettes-and-fonts-in-sharepoint.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/color-palettes-and-fonts-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/color-palettes-and-fonts-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-195ea688219f147aab18cf451f3723cb-1432ce92)
[docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-a-map-view-for-the-geolocation-field-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-400d5f28b492678721dcddf8b92ef39a-1432ce92)
[docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/create-hybrid-connectivity-apps-for-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/create-hybrid-connectivity-apps-for-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-075bfdf2915e57a470020177af45976f-1432ce92)
[docs/general-development/develop-sharepoint-workflows-using-visual-studio.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/develop-sharepoint-workflows-using-visual-studio.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/develop-sharepoint-workflows-using-visual-studio?branch=pr-en-us-8089) | [Details](#user-content-ff7f24818c030d73264306d82cffbcf9-1432ce92)
[docs/general-development/excel-services-blogs-forums-and-resources.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/excel-services-blogs-forums-and-resources.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/excel-services-blogs-forums-and-resources?branch=pr-en-us-8089) | [Details](#user-content-c65a9a422523a2d97227954f3c0ff13b-1432ce92)
[docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-add-a-geolocation-column-to-a-list-programmatically-in-sharepoint?branch=pr-en-us-8089) | [Details](#user-content-a5c270d11c540504fc87ae6079e4e82d-1432ce92)
[docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-configure-and-use-push-notifications-in-sharepoint-apps-for-windows?branch=pr-en-us-8089) | [Details](#user-content-8ce77a1f6c95e2c0e89e04e013963548-1432ce92)
[docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-mobile-app-in-sharepoint-that-contains-data-from-an-externa?branch=pr-en-us-8089) | [Details](#user-content-53f7314504d4b84e855bed033fb8b34e-1432ce92)
[docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-create-a-windows-phone-sharepoint-list-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-create-a-windows-phone-sharepoint-list-app?branch=pr-en-us-8089) | [Details](#user-content-e961ca5a8560de6f4b23582e519b8151-1432ce92)
[docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-list-item-queries-and-filter-data-for-windows-phone-apps?branch=pr-en-us-8089) | [Details](#user-content-5c5a16d3d52cad4bba27d8969e9e320c-1432ce92)
[docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-customize-the-user-interface-of-a-sharepoint-list-app-for-windows-ph?branch=pr-en-us-8089) | [Details](#user-content-f50c48d7ce0ff679ac97143cdb6a1ff1-1432ce92)
[docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-export-the-name-field-in-a-document-library-list-to-a-mobile-app?branch=pr-en-us-8089) | [Details](#user-content-8f95d7677d97a3fb78b669a76c8705c8-1432ce92)
[docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb2/docs/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-follow-documents-sites-and-tags-by-using-the-rest-service-in-sharepoint-2?branch=pr-en-us-8089) | [Details](#user-content-824201d5d2fe38ff425cc93d6e80954a-1432ce92)
[docs/general-de [...]

2022-06-23 09:37 UTC, andrewconnell approved these changes

2022-06-23 10:09 UTC, merged