Validation: fix multiple issues on files in docs/schema folder
SharePoint/sp-dev-docs pull request #8144
Opened 2022-06-10 17:16 UTC by LSchaufMS

## Category

- [x] Content fix
- [ ] New article

## Related issues

- no issue numbers; changes are part of the Validation cleanup efforts

## What's in this Pull Request?

This PR fixes *** changes in *** files.

2022-06-10 17:18 UTC, VesaJuvonen commented
Docs Build status updates of commit _[194987c](https://github.com/LSchaufMS/sp-dev-docs/commits/194987ca0183cc643fa2306f8357d13d51747538)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) | [Details](#user-content-917bf6ec6084624c788b64e9f09c9734-16a666cc)

<a id="917bf6ec6084624c788b64e9f09c9734-16a666cc"></a>
### [docs/schema/query-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-deploymentmanifestspview.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206101716461203-8144/BuildReport?accessString=ff5a9aac86d24bdc4831f63d68592866e8015c843c33cfbba0f4cdac1cd29650).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-10 18:42 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5966b8c](https://github.com/LSchaufMS/sp-dev-docs/commits/5966b8c3912a1a16076e1a6292f32f7d08a71175)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) | [Details](#user-content-917bf6ec6084624c788b64e9f09c9734-4fa0ca55)
[docs/schema/query-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspwebpart?branch=pr-en-us-8144) | [Details](#user-content-10fc46a26f68874e559cf5539524f9a3-4fa0ca55)
[docs/schema/query-element-in-queries-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-in-queries-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-in-queries-subscription-schema?branch=pr-en-us-8144) | [Details](#user-content-8510d13405d0f003c1eef3c658683f02-4fa0ca55)
[docs/schema/queryhint-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryhint-element-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-element-sps15xsdsearchset5?branch=pr-en-us-8144) | [Details](#user-content-1e82ad4538be1808c47a4f5080dd1aab-4fa0ca55)
[docs/schema/queryhint-simpletype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryhint-simpletype-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-simpletype-sps15xsdsearchset5?branch=pr-en-us-8144) | [Details](#user-content-43de22475825f63e122a548040f28444-4fa0ca55)
[docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear?branch=pr-en-us-8144) | [Details](#user-content-28f700868f6359923e1a159b259105ab-4fa0ca55)
[docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset?branch=pr-en-us-8144) | [Details](#user-content-050f61fa4839ccaa23b4eb318008989a-4fa0ca55)
[docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransform-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8144) | [Details](#user-content-3a32861b4fbfe68461ecd4d25c12e52a-4fa0ca55)
[docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-element-sps15xsdsearchset4?branch=pr-en-us-8144) | [Details](#user-content-3a302485bdbdb553051de4b01347ada9-4fa0ca55)
[docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-simpletype-sps15xsdsearchset4?branch=pr-en-us-8144) | [Details](#user-content-79512ba3258dce5d0683ca7a9be5b548-4fa0ca55)
[docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs?branch=pr-en-us-8144) | [Details](#user-content-651b241243462213454357511c70dbce-4fa0ca55)
[docs/schema/receiver-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/receiver-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receiver-element-event?branch=pr-en-us-8144) | [Details](#user-content-1e0f911a4bc991cb7c8f04b2debb3125-4fa0ca55)
[docs/schema/receivers-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/receivers-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receivers-element-event?branch=pr-en-us-8144) | [Details](#user-content-75b6fafc3bbf37a274d12d0001b7c23a-4fa0ca55)
[docs/schema/recurrence-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/recurrence-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/recurrence-element?branch=pr-en-us-8144) | [Details](#user-content-777d27250b587dbc3697b8ead78a75dc-4fa0ca55)
[docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-a2178729ef04358b1f7dc225008a00cf-4fa0ca55)
[docs/schema/refineranchoring-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refineranchoring-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-element-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-a904268310bb5e7d7aca368e4c23cd3f-4fa0ca55)
[docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-simpletype-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-1a85917f2bb98aa18f45b646f3f3dcd0-4fa0ca55)
[docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-complextype-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-0d9a58107e5a7b172f8d4ed1542a8338-4fa0ca55)
[docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://r [...]

2022-06-10 18:46 UTC, VesaJuvonen commented
Docs Build status updates of commit _[76b4148](https://github.com/LSchaufMS/sp-dev-docs/commits/76b4148b0d51c13d933e14d64ce7b3c9407afb1b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) | [Details](#user-content-917bf6ec6084624c788b64e9f09c9734-39b4fc5d)
[docs/schema/query-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspwebpart?branch=pr-en-us-8144) | [Details](#user-content-10fc46a26f68874e559cf5539524f9a3-39b4fc5d)
[docs/schema/query-element-in-queries-subscription-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/query-element-in-queries-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-in-queries-subscription-schema?branch=pr-en-us-8144) | [Details](#user-content-8510d13405d0f003c1eef3c658683f02-39b4fc5d)
[docs/schema/queryhint-element-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryhint-element-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-element-sps15xsdsearchset5?branch=pr-en-us-8144) | [Details](#user-content-1e82ad4538be1808c47a4f5080dd1aab-39b4fc5d)
[docs/schema/queryhint-simpletype-sps15xsdsearchset5.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryhint-simpletype-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-simpletype-sps15xsdsearchset5?branch=pr-en-us-8144) | [Details](#user-content-43de22475825f63e122a548040f28444-39b4fc5d)
[docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear?branch=pr-en-us-8144) | [Details](#user-content-28f700868f6359923e1a159b259105ab-39b4fc5d)
[docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset?branch=pr-en-us-8144) | [Details](#user-content-050f61fa4839ccaa23b4eb318008989a-39b4fc5d)
[docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransform-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8144) | [Details](#user-content-3a32861b4fbfe68461ecd4d25c12e52a-39b4fc5d)
[docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-element-sps15xsdsearchset4?branch=pr-en-us-8144) | [Details](#user-content-3a302485bdbdb553051de4b01347ada9-39b4fc5d)
[docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-simpletype-sps15xsdsearchset4?branch=pr-en-us-8144) | [Details](#user-content-79512ba3258dce5d0683ca7a9be5b548-39b4fc5d)
[docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs?branch=pr-en-us-8144) | [Details](#user-content-651b241243462213454357511c70dbce-39b4fc5d)
[docs/schema/receiver-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/receiver-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receiver-element-event?branch=pr-en-us-8144) | [Details](#user-content-1e0f911a4bc991cb7c8f04b2debb3125-39b4fc5d)
[docs/schema/receivers-element-event.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/receivers-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receivers-element-event?branch=pr-en-us-8144) | [Details](#user-content-75b6fafc3bbf37a274d12d0001b7c23a-39b4fc5d)
[docs/schema/recurrence-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/recurrence-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/recurrence-element?branch=pr-en-us-8144) | [Details](#user-content-777d27250b587dbc3697b8ead78a75dc-39b4fc5d)
[docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-a2178729ef04358b1f7dc225008a00cf-39b4fc5d)
[docs/schema/refineranchoring-element-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refineranchoring-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-element-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-a904268310bb5e7d7aca368e4c23cd3f-39b4fc5d)
[docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-simpletype-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-1a85917f2bb98aa18f45b646f3f3dcd0-39b4fc5d)
[docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-complextype-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-0d9a58107e5a7b172f8d4ed1542a8338-39b4fc5d)
[docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://r [...]

2022-06-10 22:42 UTC, RedZephyr13 commented on docs/schema/queryhint-element-sps15xsdsearchset5.md
>  |**Element type** <br/> |tns:QueryHint  <br/> |
These `<br/>` have no functionality, feel free to delete them in future PRs.

2022-06-10 22:42 UTC, RedZephyr13 commented on docs/schema/queryhint-element-sps15xsdsearchset5.md
>  |**Element type** <br/> |tns:QueryHint  <br/> |
These `<br/>` have no functionality, feel free to delete them in future PRs.

2022-06-10 23:25 UTC, LSchaufMS commented
[4:23 PM] Chong Kim (AQUENT LLC)
ATTN: Another small tweak for this repo, please don't @mention any reviewers.  Let's use our boilerplate message w/o the @mention, like below:

**Global effort to fix build validation errors**
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-23 10:06 UTC, andrewconnell requested changes

2022-06-23 10:06 UTC, andrewconnell commented on docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md
> +description: "Describes the QueryTransformParentType simpleType (SPS15XSDSearchSet4). Applies to SharePoint Server 2013."
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-28 22:27 UTC, LSchaufMS commented
Issue resolved - file updated. @andrewconnell can you please re-review and merge?

2022-06-28 22:28 UTC, VesaJuvonen commented
Docs Build status updates of commit _[6a4ded9](https://github.com/LSchaufMS/sp-dev-docs/commits/6a4ded98491e2dfdb2e2504b474f6d2789cf3bba)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) | [Details](#user-content-917bf6ec6084624c788b64e9f09c9734-e04ffce1)
[docs/schema/query-element-deploymentmanifestspwebpart.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspwebpart?branch=pr-en-us-8144) | [Details](#user-content-10fc46a26f68874e559cf5539524f9a3-e04ffce1)
[docs/schema/query-element-in-queries-subscription-schema.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-in-queries-subscription-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-in-queries-subscription-schema?branch=pr-en-us-8144) | [Details](#user-content-8510d13405d0f003c1eef3c658683f02-e04ffce1)
[docs/schema/queryhint-element-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-element-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-element-sps15xsdsearchset5?branch=pr-en-us-8144) | [Details](#user-content-1e82ad4538be1808c47a4f5080dd1aab-e04ffce1)
[docs/schema/queryhint-simpletype-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-simpletype-sps15xsdsearchset5.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-simpletype-sps15xsdsearchset5?branch=pr-en-us-8144) | [Details](#user-content-43de22475825f63e122a548040f28444-e04ffce1)
[docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear?branch=pr-en-us-8144) | [Details](#user-content-28f700868f6359923e1a159b259105ab-e04ffce1)
[docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset?branch=pr-en-us-8144) | [Details](#user-content-050f61fa4839ccaa23b4eb318008989a-e04ffce1)
[docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransform-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8144) | [Details](#user-content-3a32861b4fbfe68461ecd4d25c12e52a-e04ffce1)
[docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-element-sps15xsdsearchset4?branch=pr-en-us-8144) | [Details](#user-content-3a302485bdbdb553051de4b01347ada9-e04ffce1)
[docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-simpletype-sps15xsdsearchset4?branch=pr-en-us-8144) | [Details](#user-content-79512ba3258dce5d0683ca7a9be5b548-e04ffce1)
[docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs?branch=pr-en-us-8144) | [Details](#user-content-651b241243462213454357511c70dbce-e04ffce1)
[docs/schema/receiver-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receiver-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receiver-element-event?branch=pr-en-us-8144) | [Details](#user-content-1e0f911a4bc991cb7c8f04b2debb3125-e04ffce1)
[docs/schema/receivers-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receivers-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receivers-element-event?branch=pr-en-us-8144) | [Details](#user-content-75b6fafc3bbf37a274d12d0001b7c23a-e04ffce1)
[docs/schema/recurrence-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/recurrence-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/recurrence-element?branch=pr-en-us-8144) | [Details](#user-content-777d27250b587dbc3697b8ead78a75dc-e04ffce1)
[docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-a2178729ef04358b1f7dc225008a00cf-e04ffce1)
[docs/schema/refineranchoring-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-element-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-element-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-a904268310bb5e7d7aca368e4c23cd3f-e04ffce1)
[docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-simpletype-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-1a85917f2bb98aa18f45b646f3f3dcd0-e04ffce1)
[docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-complextype-sps15xsdsearchset2?branch=pr-en-us-8144) | [Details](#user-content-0d9a58107e5a7b172f8d4ed1542a8338-e04ffce1)
[docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) [...]

2022-06-29 10:15 UTC, andrewconnell approved these changes

2022-06-29 22:06 UTC, LSchaufMS commented
@andrewconnell Merge conflict resolved.

2022-06-29 22:07 UTC, VesaJuvonen commented
Docs Build status updates of commit _[194bc39](https://github.com/LSchaufMS/sp-dev-docs/commits/194bc39df92c3da56639d1e26c3596c72933573a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/receivers-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receivers-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receivers-element-event?branch=pr-en-us-8144) | [Details](#user-content-75b6fafc3bbf37a274d12d0001b7c23a-9db06cae)
[docs/schema/remoteendpointsdefinition-complextype-sharepoint-add-in-manifest.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/remoteendpointsdefinition-complextype-sharepoint-add-in-manifest.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/remoteendpointsdefinition-complextype-sharepoint-add-in-manifest?branch=pr-en-us-8144) | [Details](#user-content-a2f9cba5376b65bd6ae5ba361e075d27-9db06cae)
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) |
[docs/schema/query-element-deploymentmanifestspwebpart.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspwebpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspwebpart?branch=pr-en-us-8144) |
[docs/schema/query-element-in-queries-subscription-schema.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-in-queries-subscription-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-in-queries-subscription-schema?branch=pr-en-us-8144) |
[docs/schema/queryhint-element-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-element-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-element-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryhint-simpletype-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-simpletype-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-simpletype-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear?branch=pr-en-us-8144) |
[docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset?branch=pr-en-us-8144) |
[docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransform-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-element-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-simpletype-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs?branch=pr-en-us-8144) |
[docs/schema/receiver-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receiver-element-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receiver-element-event?branch=pr-en-us-8144) |
[docs/schema/recurrence-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/recurrence-element.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/recurrence-element?branch=pr-en-us-8144) |
[docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-simpletype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-complextype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/ [...]

2022-06-30 14:26 UTC, andrewconnell requested changes
Please address both issues (warnings & suggestions) in the build report: https://github.com/SharePoint/sp-dev-docs/pull/8144#issuecomment-1170542174

2022-06-30 22:19 UTC, LSchaufMS commented
Fixed the missing table headers on docs/schema/remoteendpointsdefinition-complextype-sharepoint-add-in-manifest.md

2022-06-30 22:22 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1ee2bf1](https://github.com/LSchaufMS/sp-dev-docs/commits/1ee2bf178e2d34e947c7e77f2e45f3c5532ef0e4)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/receivers-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receivers-element-event.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receivers-element-event?branch=pr-en-us-8144) | [Details](#user-content-75b6fafc3bbf37a274d12d0001b7c23a-70dab128)
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) |
[docs/schema/query-element-deploymentmanifestspwebpart.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspwebpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspwebpart?branch=pr-en-us-8144) |
[docs/schema/query-element-in-queries-subscription-schema.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-in-queries-subscription-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-in-queries-subscription-schema?branch=pr-en-us-8144) |
[docs/schema/queryhint-element-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-element-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-element-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryhint-simpletype-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-simpletype-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-simpletype-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear?branch=pr-en-us-8144) |
[docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset?branch=pr-en-us-8144) |
[docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransform-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-element-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-simpletype-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs?branch=pr-en-us-8144) |
[docs/schema/receiver-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receiver-element-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receiver-element-event?branch=pr-en-us-8144) |
[docs/schema/recurrence-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/recurrence-element.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/recurrence-element?branch=pr-en-us-8144) |
[docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-simpletype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-complextype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinertype-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinertype-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinertype-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinertype-simpletype-sps15xsdsearchset2.md](htt [...]

2022-06-30 23:05 UTC, VesaJuvonen commented
Docs Build status updates of commit _[74c14e2](https://github.com/LSchaufMS/sp-dev-docs/commits/74c14e22dcc89dc062ac4c5f7e528a96181d06f7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) |
[docs/schema/query-element-deploymentmanifestspwebpart.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspwebpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspwebpart?branch=pr-en-us-8144) |
[docs/schema/query-element-in-queries-subscription-schema.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-in-queries-subscription-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-in-queries-subscription-schema?branch=pr-en-us-8144) |
[docs/schema/queryhint-element-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-element-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-element-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryhint-simpletype-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-simpletype-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-simpletype-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear?branch=pr-en-us-8144) |
[docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset?branch=pr-en-us-8144) |
[docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransform-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-element-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-simpletype-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs?branch=pr-en-us-8144) |
[docs/schema/receiver-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receiver-element-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receiver-element-event?branch=pr-en-us-8144) |
[docs/schema/receivers-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receivers-element-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receivers-element-event?branch=pr-en-us-8144) |
[docs/schema/recurrence-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/recurrence-element.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/recurrence-element?branch=pr-en-us-8144) |
[docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-simpletype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-complextype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinertype-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinertype-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinertype-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinertype-simpletype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610 [...]

2022-06-30 23:25 UTC, LSchaufMS commented
@andrewconnell Broken link fixed. Please review.

2022-07-01 11:56 UTC, andrewconnell approved these changes

2022-07-01 11:58 UTC, VesaJuvonen commented
Docs Build status updates of commit _[7acb7e2](https://github.com/LSchaufMS/sp-dev-docs/commits/7acb7e23e40196d70322614fc9814fe1d4eb6388)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/query-element-deploymentmanifestspview.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspview?branch=pr-en-us-8144) |
[docs/schema/query-element-deploymentmanifestspwebpart.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-deploymentmanifestspwebpart.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-deploymentmanifestspwebpart?branch=pr-en-us-8144) |
[docs/schema/query-element-in-queries-subscription-schema.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/query-element-in-queries-subscription-schema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/query-element-in-queries-subscription-schema?branch=pr-en-us-8144) |
[docs/schema/queryhint-element-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-element-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-element-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryhint-simpletype-sps15xsdsearchset5.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryhint-simpletype-sps15xsdsearchset5.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryhint-simpletype-sps15xsdsearchset5?branch=pr-en-us-8144) |
[docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrulegroups-element-searchqueryconfigurationsettings-complextypesps15xsdsear?branch=pr-en-us-8144) |
[docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/queryrules-element-searchqueryconfigurationsettings-complextypesps15xsdsearchset?branch=pr-en-us-8144) |
[docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransform-element-source-complextypesps15xsdsearchset1.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransform-element-source-complextypesps15xsdsearchset1?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-element-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-element-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/querytransformparenttype-simpletype-sps15xsdsearchset4.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/querytransformparenttype-simpletype-sps15xsdsearchset4?branch=pr-en-us-8144) |
[docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/rankingmodels-element-searchrankingmodelconfigurationsettings-complextypesps15xs?branch=pr-en-us-8144) |
[docs/schema/receiver-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receiver-element-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receiver-element-event?branch=pr-en-us-8144) |
[docs/schema/receivers-element-event.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/receivers-element-event.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/receivers-element-event?branch=pr-en-us-8144) |
[docs/schema/recurrence-element.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/recurrence-element.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/recurrence-element?branch=pr-en-us-8144) |
[docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinable-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refineranchoring-simpletype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refineranchoring-simpletype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-complextype-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-complextype-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-element-managedpropertyinfo-complextypesps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinerconfiguration-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinerconfiguration-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinertype-element-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610a/docs/schema/refinertype-element-sps15xsdsearchset2.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/refinertype-element-sps15xsdsearchset2?branch=pr-en-us-8144) |
[docs/schema/refinertype-simpletype-sps15xsdsearchset2.md](https://github.com/LSchaufMS/sp-dev-docs/blob/LS0610 [...]

2022-07-01 11:59 UTC, merged