fixes
SharePoint/sp-dev-docs pull request #8152
Opened 2022-06-10 21:51 UTC by SueADarby

## Category

- [x] Content fix
- [] New article

## Related issues

No issue part of validation

## What's in this Pull Request?
 This PR fixes X issues for Y files.

2022-06-10 21:52 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8bdb90a](https://github.com/SueADarby/sp-dev-docs/commits/8bdb90a6989f2752af4bb21b288eee26621d5d56)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-0cce51c15a0bd48cdc34ac1055fece8e-9ecb7ef6)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-674d29f2d7fd522b2f474978d5e8474e-9ecb7ef6)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema?branch=pr-en-us-8152) | [Details](#user-content-1de3f7657d09cf6e91ec8c7f85a8c508-9ecb7ef6)
[docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-edcfb1a0defb67d4875e6a62721d8c36-9ecb7ef6)
[docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso?branch=pr-en-us-8152) | [Details](#user-content-e7686c39ebb994e424de6c22e721b852-9ecb7ef6)
[docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accountauthcredentials-complextype-sps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-2fab2ffd4dab93bd8e82f24daf3acfbf-9ecb7ef6)
[docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8152) | [Details](#user-content-509197303966f842b05b2c226861e496-9ecb7ef6)
[docs/schema/actionbody-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowactions?branch=pr-en-us-8152) | [Details](#user-content-eab937cb19b749d3298547143f467707-9ecb7ef6)
[docs/schema/actionbody-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowinfo?branch=pr-en-us-8152) | [Details](#user-content-fbbb3c18bc628d3106d820ed761d1c96-9ecb7ef6)

<a id="0cce51c15a0bd48cdc34ac1055fece8e-9ecb7ef6"></a>
### [docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="674d29f2d7fd522b2f474978d5e8474e-9ecb7ef6"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="1de3f7657d09cf6e91ec8c7f85a8c508-9ecb7ef6"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="edcfb1a0defb67d4875e6a62721d8c36-9ecb7ef6"></a>
### [docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e7686c39ebb994e424de6c22e721b852-9ecb7ef6"></a>
### [docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2fab2ffd4dab93bd8e82f24daf3acfbf-9ecb7ef6"></a>
### [docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="509197303966f842b05b2c226861e496-9ecb7ef6"></a>
### [docs/schema/act [...]

2022-06-10 22:49 UTC, RedZephyr13 commented on docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md
> +| element | Description |
Even though the source doesn't have this capitalized, let's correct that oversight.

2022-06-10 22:50 UTC, RedZephyr13 commented on docs/schema/accesscontrollist-element-bdcmetadata-schema.md
> + which Specifies an access control list (ACL) for the parent element.
Let's move the second half of your description to line 3, and delete line 4.

2022-06-10 23:36 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0c16075](https://github.com/SueADarby/sp-dev-docs/commits/0c16075028fc5cfbf02fc71525116bb5a614cbee)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-0cce51c15a0bd48cdc34ac1055fece8e-fb6c9cf5)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-674d29f2d7fd522b2f474978d5e8474e-fb6c9cf5)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema?branch=pr-en-us-8152) | [Details](#user-content-1de3f7657d09cf6e91ec8c7f85a8c508-fb6c9cf5)
[docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-edcfb1a0defb67d4875e6a62721d8c36-fb6c9cf5)
[docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso?branch=pr-en-us-8152) | [Details](#user-content-e7686c39ebb994e424de6c22e721b852-fb6c9cf5)
[docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accountauthcredentials-complextype-sps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-2fab2ffd4dab93bd8e82f24daf3acfbf-fb6c9cf5)
[docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8152) | [Details](#user-content-509197303966f842b05b2c226861e496-fb6c9cf5)
[docs/schema/actionbody-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowactions?branch=pr-en-us-8152) | [Details](#user-content-eab937cb19b749d3298547143f467707-fb6c9cf5)
[docs/schema/actionbody-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowinfo?branch=pr-en-us-8152) | [Details](#user-content-fbbb3c18bc628d3106d820ed761d1c96-fb6c9cf5)

<a id="0cce51c15a0bd48cdc34ac1055fece8e-fb6c9cf5"></a>
### [docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="674d29f2d7fd522b2f474978d5e8474e-fb6c9cf5"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="1de3f7657d09cf6e91ec8c7f85a8c508-fb6c9cf5"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="edcfb1a0defb67d4875e6a62721d8c36-fb6c9cf5"></a>
### [docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e7686c39ebb994e424de6c22e721b852-fb6c9cf5"></a>
### [docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2fab2ffd4dab93bd8e82f24daf3acfbf-fb6c9cf5"></a>
### [docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="509197303966f842b05b2c226861e496-fb6c9cf5"></a>
### [docs/schema/act [...]

2022-06-10 23:38 UTC, SueADarby commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-13 14:55 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0fb3823](https://github.com/SueADarby/sp-dev-docs/commits/0fb38234b20c45611683a43805ee559fb770125b)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-0cce51c15a0bd48cdc34ac1055fece8e-390d70fb)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-674d29f2d7fd522b2f474978d5e8474e-390d70fb)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema?branch=pr-en-us-8152) | [Details](#user-content-1de3f7657d09cf6e91ec8c7f85a8c508-390d70fb)
[docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-edcfb1a0defb67d4875e6a62721d8c36-390d70fb)
[docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso?branch=pr-en-us-8152) | [Details](#user-content-e7686c39ebb994e424de6c22e721b852-390d70fb)
[docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accountauthcredentials-complextype-sps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-2fab2ffd4dab93bd8e82f24daf3acfbf-390d70fb)
[docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8152) | [Details](#user-content-509197303966f842b05b2c226861e496-390d70fb)
[docs/schema/actionbody-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowactions?branch=pr-en-us-8152) | [Details](#user-content-eab937cb19b749d3298547143f467707-390d70fb)
[docs/schema/actionbody-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowinfo?branch=pr-en-us-8152) | [Details](#user-content-fbbb3c18bc628d3106d820ed761d1c96-390d70fb)

<a id="0cce51c15a0bd48cdc34ac1055fece8e-390d70fb"></a>
### [docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="674d29f2d7fd522b2f474978d5e8474e-390d70fb"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="1de3f7657d09cf6e91ec8c7f85a8c508-390d70fb"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="edcfb1a0defb67d4875e6a62721d8c36-390d70fb"></a>
### [docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e7686c39ebb994e424de6c22e721b852-390d70fb"></a>
### [docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2fab2ffd4dab93bd8e82f24daf3acfbf-390d70fb"></a>
### [docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="509197303966f842b05b2c226861e496-390d70fb"></a>
### [docs/schema/act [...]

2022-06-13 23:15 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8557e8f](https://github.com/SueADarby/sp-dev-docs/commits/8557e8f79c02a94fe8dbd105e3d1eafa9c1d019c)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-0cce51c15a0bd48cdc34ac1055fece8e-fe33eeff)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-674d29f2d7fd522b2f474978d5e8474e-fe33eeff)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema?branch=pr-en-us-8152) | [Details](#user-content-1de3f7657d09cf6e91ec8c7f85a8c508-fe33eeff)
[docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-edcfb1a0defb67d4875e6a62721d8c36-fe33eeff)
[docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso?branch=pr-en-us-8152) | [Details](#user-content-e7686c39ebb994e424de6c22e721b852-fe33eeff)
[docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accountauthcredentials-complextype-sps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-2fab2ffd4dab93bd8e82f24daf3acfbf-fe33eeff)
[docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8152) | [Details](#user-content-509197303966f842b05b2c226861e496-fe33eeff)
[docs/schema/actionbody-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowactions?branch=pr-en-us-8152) | [Details](#user-content-eab937cb19b749d3298547143f467707-fe33eeff)
[docs/schema/actionbody-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowinfo?branch=pr-en-us-8152) | [Details](#user-content-fbbb3c18bc628d3106d820ed761d1c96-fe33eeff)

<a id="0cce51c15a0bd48cdc34ac1055fece8e-fe33eeff"></a>
### [docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="674d29f2d7fd522b2f474978d5e8474e-fe33eeff"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="1de3f7657d09cf6e91ec8c7f85a8c508-fe33eeff"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="edcfb1a0defb67d4875e6a62721d8c36-fe33eeff"></a>
### [docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e7686c39ebb994e424de6c22e721b852-fe33eeff"></a>
### [docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2fab2ffd4dab93bd8e82f24daf3acfbf-fe33eeff"></a>
### [docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="509197303966f842b05b2c226861e496-fe33eeff"></a>
### [docs/schema/act [...]

2022-06-13 23:16 UTC, VesaJuvonen commented
Docs Build status updates of commit _[fbcc42c](https://github.com/SueADarby/sp-dev-docs/commits/fbcc42cc949cb0219506141665020317fa8bf2d2)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-0cce51c15a0bd48cdc34ac1055fece8e-b06142b4)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-674d29f2d7fd522b2f474978d5e8474e-b06142b4)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema?branch=pr-en-us-8152) | [Details](#user-content-1de3f7657d09cf6e91ec8c7f85a8c508-b06142b4)
[docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-edcfb1a0defb67d4875e6a62721d8c36-b06142b4)
[docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso?branch=pr-en-us-8152) | [Details](#user-content-e7686c39ebb994e424de6c22e721b852-b06142b4)
[docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accountauthcredentials-complextype-sps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-2fab2ffd4dab93bd8e82f24daf3acfbf-b06142b4)
[docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8152) | [Details](#user-content-509197303966f842b05b2c226861e496-b06142b4)
[docs/schema/actionbody-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowactions?branch=pr-en-us-8152) | [Details](#user-content-eab937cb19b749d3298547143f467707-b06142b4)
[docs/schema/actionbody-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionbody-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowinfo?branch=pr-en-us-8152) | [Details](#user-content-fbbb3c18bc628d3106d820ed761d1c96-b06142b4)

<a id="0cce51c15a0bd48cdc34ac1055fece8e-b06142b4"></a>
### [docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="674d29f2d7fd522b2f474978d5e8474e-b06142b4"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="1de3f7657d09cf6e91ec8c7f85a8c508-b06142b4"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="edcfb1a0defb67d4875e6a62721d8c36-b06142b4"></a>
### [docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e7686c39ebb994e424de6c22e721b852-b06142b4"></a>
### [docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2fab2ffd4dab93bd8e82f24daf3acfbf-b06142b4"></a>
### [docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="509197303966f842b05b2c226861e496-b06142b4"></a>
### [docs/schema/act [...]

2022-06-14 00:21 UTC, RedZephyr13 commented on docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md
> +|**Namespace** </br> |http://schemas.datacontract.org/2004/07/Microsoft.Office.Server.Search.Administration  </br> |
When you see these HTML breaks that don't do anything, feel free to delete the `<br/>`.

2022-06-14 00:30 UTC, SueADarby commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-24 08:16 UTC, andrewconnell requested changes

2022-06-24 08:16 UTC, andrewconnell commented on docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md
> +|**Namespace** </br> |http://schemas.datacontract.org/2004/07/Microsoft.Office.Server.Search.Administration  </br> |
Invalid HTML, remove the <br> tags.

2022-06-24 08:16 UTC, andrewconnell commented on docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md
> +|**Element type**  </br>  |xs:string   </br>  |
Invalid HTML, remove the <br> tags

2022-06-24 20:02 UTC, VesaJuvonen commented
Docs Build status updates of commit _[b16f219](https://github.com/SueADarby/sp-dev-docs/commits/b16f219fe17bff95c6a8f2c4e1940fffc2c174ac)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-0cce51c15a0bd48cdc34ac1055fece8e-e26790b1)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema?branch=pr-en-us-8152) | [Details](#user-content-1de3f7657d09cf6e91ec8c7f85a8c508-e26790b1)
[docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-674d29f2d7fd522b2f474978d5e8474e-e26790b1)
[docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrollist-element-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-bdcmetadata-schema?branch=pr-en-us-8152) | [Details](#user-content-edcfb1a0defb67d4875e6a62721d8c36-e26790b1)
[docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso?branch=pr-en-us-8152) | [Details](#user-content-e7686c39ebb994e424de6c22e721b852-e26790b1)
[docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/accountauthcredentials-complextype-sps15xsdsearchset2?branch=pr-en-us-8152) | [Details](#user-content-2fab2ffd4dab93bd8e82f24daf3acfbf-e26790b1)
[docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8152) | [Details](#user-content-509197303966f842b05b2c226861e496-e26790b1)
[docs/schema/actionbody-element-workflowactions.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/actionbody-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowactions?branch=pr-en-us-8152) | [Details](#user-content-eab937cb19b749d3298547143f467707-e26790b1)
[docs/schema/actionbody-element-workflowinfo.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/actionbody-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionbody-element-workflowinfo?branch=pr-en-us-8152) | [Details](#user-content-fbbb3c18bc628d3106d820ed761d1c96-e26790b1)

<a id="0cce51c15a0bd48cdc34ac1055fece8e-e26790b1"></a>
### [docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/_username-element-accountauthcredentials-complextypesps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="1de3f7657d09cf6e91ec8c7f85a8c508-e26790b1"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadataresource-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="674d29f2d7fd522b2f474978d5e8474e-e26790b1"></a>
### [docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrolentry-element-in-accesscontrollist-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="edcfb1a0defb67d4875e6a62721d8c36-e26790b1"></a>
### [docs/schema/accesscontrollist-element-bdcmetadata-schema.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrollist-element-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e7686c39ebb994e424de6c22e721b852-e26790b1"></a>
### [docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accesscontrollist-element-in-individuallysecurablemetadataobject-bdcmetadatareso.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="2fab2ffd4dab93bd8e82f24daf3acfbf-e26790b1"></a>
### [docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md](https://github.com/SueADarby/sp-dev-docs/blob/sd1/docs/schema/accountauthcredentials-complextype-sps15xsdsearchset2.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="509197303966f842b05b2c226861e496-e26790b1"></a>
### [docs/schema/actionbody-element-action-element [...]

2022-06-25 09:26 UTC, andrewconnell approved these changes

2022-06-25 09:27 UTC, merged