[BULK] Validation: SharePoint Dev Docs fixes
SharePoint/sp-dev-docs pull request #8163
Opened 2022-06-13 18:29 UTC by SueADarby

## Category

- [x] Content fix
- [] New article

## Related issues

No issue part of validation

## What's in this Pull Request?
 This PR fixes 29 issues for 17 files.

2022-06-13 18:31 UTC, VesaJuvonen commented
Docs Build status updates of commit _[18b72c0](https://github.com/SueADarby/sp-dev-docs/commits/18b72c04cdb720d56dbaa3a2909a513dc5093d07)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionparameters-element-in-action-bdcmetadata-schema?branch=pr-en-us-8163) | [Details](#user-content-3c83177c028c0312c3f48eddae727d98-1f0fa692)
[docs/schema/actionparameters-element-in-action-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionparameters-element-in-action-bdcmetadataresource-schema?branch=pr-en-us-8163) | [Details](#user-content-1a884a9dbb04cbf5e8b29113c2d1c872-1f0fa692)
[docs/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten?branch=pr-en-us-8163) | [Details](#user-content-c9e888a3d85e7de428f05a1bad93e00e-1f0fa692)
[docs/schema/actions-element-in-entity-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-entity-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-entity-bdcmetadata-schema?branch=pr-en-us-8163) | [Details](#user-content-cd80292063b975f7f6fdbbe8bfa14d0b-1f0fa692)
[docs/schema/actions-element-in-entity-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-entity-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-entity-bdcmetadataresource-schema?branch=pr-en-us-8163) | [Details](#user-content-c0845d5ad70b7058486229525c9a8dfd-1f0fa692)
[docs/schema/actions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-workflowinfo-elementaction4?branch=pr-en-us-8163) | [Details](#user-content-4f363a310797a96c6a0004ce45687ea2-1f0fa692)
[docs/schema/actions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-f5b5672d15ad3bb52d4cc4e2ae9a4acc-1f0fa692)
[docs/schema/actions-file-example-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-file-example-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-file-example-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-7a44d92fa03e3246472957d6ce632ea4-1f0fa692)
[docs/schema/actions-schema-reference-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-schema-reference-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-schema-reference-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-4acceef27ca5cb269516ac6293783eae-1f0fa692)
[docs/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8163) | [Details](#user-content-faf3e4cdba61bbde8d5960c773a87b31-1f0fa692)
[docs/schema/actionvariables-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-workflowactions?branch=pr-en-us-8163) | [Details](#user-content-f607e2fc07afa1a5674d6312f228da55-1f0fa692)
[docs/schema/actionvariables-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-a40eb0194b773177171bd5e664ce07f1-1f0fa692)
[docs/schema/activationdependencies-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-feature?branch=pr-en-us-8163) | [Details](#user-content-5295adc120efef6135a93e1eb0d2014a-1f0fa692)
[docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures?branch=pr-en-us-8163) | [Details](#user-content-e254080d8ad6d83f43cdff9f18214f6e-1f0fa692)
[docs/schema/activationdependencies-element-solution.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-solution.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-solution?branch=pr-en-us-8163) | [Details](#user-content-ab77bf1115fdaf0d15cbe88bee093fd7-1f0fa692)
[docs/schema/activationdependency-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependency-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependency-element-feature?branch=pr-en-us-8163) | [Details](#user-content-4cd80fff479defd8aaae9a93ab32df11-1f0fa692)
[docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea?branch=pr-en-us-8163) | [Details](#user-content-8384a5436251a71a782a452898ed6492-1f0fa692)

<a id="3c83177c028c0312c3f48eddae727d98-1f0fa692"></a>
### [docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id= [...]

2022-06-13 18:35 UTC, VesaJuvonen commented
Docs Build status updates of commit _[bf1ee99](https://github.com/SueADarby/sp-dev-docs/commits/bf1ee9931ee90f9df1adff5ed077c4b77951ca29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionparameters-element-in-action-bdcmetadata-schema?branch=pr-en-us-8163) | [Details](#user-content-3c83177c028c0312c3f48eddae727d98-21233e3f)
[docs/schema/actionparameters-element-in-action-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionparameters-element-in-action-bdcmetadataresource-schema?branch=pr-en-us-8163) | [Details](#user-content-1a884a9dbb04cbf5e8b29113c2d1c872-21233e3f)
[docs/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten?branch=pr-en-us-8163) | [Details](#user-content-c9e888a3d85e7de428f05a1bad93e00e-21233e3f)
[docs/schema/actions-element-in-entity-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-entity-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-entity-bdcmetadata-schema?branch=pr-en-us-8163) | [Details](#user-content-cd80292063b975f7f6fdbbe8bfa14d0b-21233e3f)
[docs/schema/actions-element-in-entity-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-entity-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-entity-bdcmetadataresource-schema?branch=pr-en-us-8163) | [Details](#user-content-c0845d5ad70b7058486229525c9a8dfd-21233e3f)
[docs/schema/actions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-workflowinfo-elementaction4?branch=pr-en-us-8163) | [Details](#user-content-4f363a310797a96c6a0004ce45687ea2-21233e3f)
[docs/schema/actions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-f5b5672d15ad3bb52d4cc4e2ae9a4acc-21233e3f)
[docs/schema/actions-file-example-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-file-example-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-file-example-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-7a44d92fa03e3246472957d6ce632ea4-21233e3f)
[docs/schema/actions-schema-reference-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-schema-reference-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-schema-reference-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-4acceef27ca5cb269516ac6293783eae-21233e3f)
[docs/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8163) | [Details](#user-content-faf3e4cdba61bbde8d5960c773a87b31-21233e3f)
[docs/schema/actionvariables-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-workflowactions?branch=pr-en-us-8163) | [Details](#user-content-f607e2fc07afa1a5674d6312f228da55-21233e3f)
[docs/schema/actionvariables-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-a40eb0194b773177171bd5e664ce07f1-21233e3f)
[docs/schema/activationdependencies-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-feature?branch=pr-en-us-8163) | [Details](#user-content-5295adc120efef6135a93e1eb0d2014a-21233e3f)
[docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures?branch=pr-en-us-8163) | [Details](#user-content-e254080d8ad6d83f43cdff9f18214f6e-21233e3f)
[docs/schema/activationdependencies-element-solution.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-solution.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-solution?branch=pr-en-us-8163) | [Details](#user-content-ab77bf1115fdaf0d15cbe88bee093fd7-21233e3f)
[docs/schema/activationdependency-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependency-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependency-element-feature?branch=pr-en-us-8163) | [Details](#user-content-4cd80fff479defd8aaae9a93ab32df11-21233e3f)
[docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea?branch=pr-en-us-8163) | [Details](#user-content-8384a5436251a71a782a452898ed6492-21233e3f)

<a id="3c83177c028c0312c3f48eddae727d98-21233e3f"></a>
### [docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id= [...]

2022-06-13 21:33 UTC, VesaJuvonen commented
Docs Build status updates of commit _[aa273e8](https://github.com/SueADarby/sp-dev-docs/commits/aa273e843b1b34babe1dcd10edcdf64ecf5cf68e)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionparameters-element-in-action-bdcmetadata-schema?branch=pr-en-us-8163) | [Details](#user-content-3c83177c028c0312c3f48eddae727d98-53d637b2)
[docs/schema/actionparameters-element-in-action-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionparameters-element-in-action-bdcmetadataresource-schema?branch=pr-en-us-8163) | [Details](#user-content-1a884a9dbb04cbf5e8b29113c2d1c872-53d637b2)
[docs/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-declarativecontextdefinition-solutionmanifestdeclarativeexten?branch=pr-en-us-8163) | [Details](#user-content-c9e888a3d85e7de428f05a1bad93e00e-53d637b2)
[docs/schema/actions-element-in-entity-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-entity-bdcmetadata-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-entity-bdcmetadata-schema?branch=pr-en-us-8163) | [Details](#user-content-cd80292063b975f7f6fdbbe8bfa14d0b-53d637b2)
[docs/schema/actions-element-in-entity-bdcmetadataresource-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-in-entity-bdcmetadataresource-schema.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-in-entity-bdcmetadataresource-schema?branch=pr-en-us-8163) | [Details](#user-content-c0845d5ad70b7058486229525c9a8dfd-53d637b2)
[docs/schema/actions-element-workflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-workflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-workflowinfo-elementaction4?branch=pr-en-us-8163) | [Details](#user-content-4f363a310797a96c6a0004ce45687ea2-53d637b2)
[docs/schema/actions-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-element-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-f5b5672d15ad3bb52d4cc4e2ae9a4acc-53d637b2)
[docs/schema/actions-file-example-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-file-example-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-file-example-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-7a44d92fa03e3246472957d6ce632ea4-53d637b2)
[docs/schema/actions-schema-reference-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actions-schema-reference-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actions-schema-reference-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-4acceef27ca5cb269516ac6293783eae-53d637b2)
[docs/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-action-elementactions-elementworkflowinfo-elementaction4?branch=pr-en-us-8163) | [Details](#user-content-faf3e4cdba61bbde8d5960c773a87b31-53d637b2)
[docs/schema/actionvariables-element-workflowactions.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-workflowactions.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-workflowactions?branch=pr-en-us-8163) | [Details](#user-content-f607e2fc07afa1a5674d6312f228da55-53d637b2)
[docs/schema/actionvariables-element-workflowinfo.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionvariables-element-workflowinfo.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/actionvariables-element-workflowinfo?branch=pr-en-us-8163) | [Details](#user-content-a40eb0194b773177171bd5e664ce07f1-53d637b2)
[docs/schema/activationdependencies-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-feature?branch=pr-en-us-8163) | [Details](#user-content-5295adc120efef6135a93e1eb0d2014a-53d637b2)
[docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures?branch=pr-en-us-8163) | [Details](#user-content-e254080d8ad6d83f43cdff9f18214f6e-53d637b2)
[docs/schema/activationdependencies-element-solution.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependencies-element-solution.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependencies-element-solution?branch=pr-en-us-8163) | [Details](#user-content-ab77bf1115fdaf0d15cbe88bee093fd7-53d637b2)
[docs/schema/activationdependency-element-feature.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependency-element-feature.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependency-element-feature?branch=pr-en-us-8163) | [Details](#user-content-4cd80fff479defd8aaae9a93ab32df11-53d637b2)
[docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea?branch=pr-en-us-8163) | [Details](#user-content-8384a5436251a71a782a452898ed6492-53d637b2)

<a id="3c83177c028c0312c3f48eddae727d98-53d637b2"></a>
### [docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/actionparameters-element-in-action-bdcmetadata-schema.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id= [...]

2022-06-14 00:30 UTC, SueADarby commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-26 09:21 UTC, andrewconnell requested changes

2022-06-26 09:21 UTC, andrewconnell commented on docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md
> +</br>
Invalid HTML - please revert this.

2022-06-26 09:21 UTC, andrewconnell commented on docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md
> +</br>
Invalid HTML - please revert this.

2022-06-26 09:21 UTC, andrewconnell commented on docs/schema/activationdependencies-element-featuredefinition-complextypeapphostwebfeatures.md
> +</br>
Invalid HTML - please revert this.

2022-06-26 09:21 UTC, andrewconnell commented on docs/schema/activationdependency-element-featureactivationdependencydefinitions-complextypea.md
> +</br>
Invalid HTML - please revert this.

2022-07-01 22:11 UTC, v-emilypr commented
#please-close

2022-07-10 18:29 UTC, closed without merging