fixing broken links
SharePoint/sp-dev-docs pull request #8169
Opened 2022-06-13 22:13 UTC by DhurataJ

## Category

- [x] Content fix
- [ ] New article

## Related issues

## What's in this Pull Request?

This PR includes only link fixes and does not change other content

- file name of broken link and path changed
- removed broken link, domain no longer exist 
- link should be unclickable
- source article deprecated
- target not found
- typo removed

2022-06-13 22:14 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0e6629f](https://github.com/DhurataJ/sp-dev-docs/commits/0e6629faa2ba1a5e2e7ee1d2d8ffc245127b760d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-358aabde)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-358aabde)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-358aabde)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-358aabde)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-358aabde)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-358aabde)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-358aabde)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-358aabde)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-358aabde)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-358aabde)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-358aabde)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-358aabde)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-358aabde)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-358aabde)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-358aabde)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-358aabde)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-358aabde)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-358aabde)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 10:34 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-20 10:34 UTC, andrewconnell commented on docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md
> +Some restrictions on how you design an add-in support multiple security zones and have a remote event receiver. For more information, see Knowledge Base article kb3135876: You can't add a provider-ho
If the KB no longer exists, don't reference it in the docs. Right now it's telling the reader to go look at something with no link. Better to just remove it.

2022-06-20 10:34 UTC, andrewconnell commented on docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md
> +You can use the experimental Desktop List View widget to display data in SharePoint lists. The widget displays data in read-only mode. Please provide ideas and comments at the Office Developer Platfo
Microsoft no longer uses UserVoice... please correct the link: https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform

2022-06-20 15:17 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8eb22f5](https://github.com/DhurataJ/sp-dev-docs/commits/8eb22f5dc06b3ca9693e43caeb5f0a073404cca3)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-d944fa5a)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-d944fa5a)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-d944fa5a)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-d944fa5a)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-d944fa5a)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-d944fa5a)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-d944fa5a)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-d944fa5a)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-d944fa5a)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-d944fa5a)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-d944fa5a)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-d944fa5a)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-d944fa5a)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-d944fa5a)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-d944fa5a)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-d944fa5a)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-d944fa5a)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-d944fa5a)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 15:32 UTC, VesaJuvonen commented
Docs Build status updates of commit _[983850f](https://github.com/DhurataJ/sp-dev-docs/commits/983850fa6ecccdd955af60b3965216ff7d7e90ad)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-b4757924)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-b4757924)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-b4757924)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-b4757924)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-b4757924)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-b4757924)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-b4757924)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-b4757924)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-b4757924)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-b4757924)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-b4757924)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-b4757924)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-b4757924)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-b4757924)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-b4757924)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-b4757924)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-b4757924)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-b4757924)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 15:48 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1d35e41](https://github.com/DhurataJ/sp-dev-docs/commits/1d35e416121453f3b5a28cd0c24bf23fc97e918f)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-7312fc58)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-7312fc58)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-7312fc58)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-7312fc58)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-7312fc58)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-7312fc58)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-7312fc58)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-7312fc58)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-7312fc58)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-7312fc58)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-7312fc58)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-7312fc58)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-7312fc58)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-7312fc58)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-7312fc58)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-7312fc58)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-7312fc58)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-7312fc58)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 19:37 UTC, andrewconnell requested changes
Resolve merge conflicts before submitting PR for merge. We can't review or accept PRs with merge conflicts.

2022-06-20 22:20 UTC, VesaJuvonen commented
Docs Build status updates of commit _[fe585f1](https://github.com/DhurataJ/sp-dev-docs/commits/fe585f1e00c05f75ad3ff4b1d3637f5c6cd4c238)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-06f2cea5)

<a id="06f2cea5"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202219092375-8169/BuildReport?accessString=c626105e9b11c3f4e0047bfeafb4fb8438e1511ed51ebbc3b90567b3b09018a3).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:22 UTC, VesaJuvonen commented
Docs Build status updates of commit _[239c5f5](https://github.com/DhurataJ/sp-dev-docs/commits/239c5f51c5417ce40980eab044165783abb176ef)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-45437bac)

<a id="45437bac"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202221592585-8169/BuildReport?accessString=edf36cefc816fc7070a10d52e5c5e6f4139dbefacfb1471657607cac71e4f9f9).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:31 UTC, VesaJuvonen commented
Docs Build status updates of commit _[32bc35b](https://github.com/DhurataJ/sp-dev-docs/commits/32bc35b8ff7ae5dd4b3e0b62b5544f161c45881d)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-8302e407)

<a id="8302e407"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202231011839-8169/BuildReport?accessString=c0fa8dc12442dcedaf1594ab59040b042e3c4f9038b6ee1bda222e9e56e98c11).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:36 UTC, VesaJuvonen commented
Docs Build status updates of commit _[84cbf18](https://github.com/DhurataJ/sp-dev-docs/commits/84cbf186847a49c8c3372dd4efaf61bf421079c7)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-84af0919)

<a id="84af0919"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202233325996-8169/BuildReport?accessString=a46d602b26109affc42f3fef3ef99e89a73a4b2f25108524cac7e3402c58dc3d).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:40 UTC, VesaJuvonen commented
Docs Build status updates of commit _[2b4d702](https://github.com/DhurataJ/sp-dev-docs/commits/2b4d702a72d637ff4605a6d426bb00cb766d57e2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-e23ed374)

<a id="e23ed374"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202235357030-8169/BuildReport?accessString=06314e532fa4b4752be0db546f5d140762009176a2535e1fc054c8ac12b78d1e).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[c6e44b4](https://github.com/DhurataJ/sp-dev-docs/commits/c6e44b42333ff439901352789236c8cca4bc1ef2)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-d4443f43)

<a id="d4443f43"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202236347305-8169/BuildReport?accessString=0d2f627a723623275229cac648bf6f36f7b6367c7054bf35a8ce386d32b38e04).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:45 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0e4a782](https://github.com/DhurataJ/sp-dev-docs/commits/0e4a782db2b56d134edc371a11d6c49984ca30a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-861bb906)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-861bb906)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-861bb906)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-861bb906)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-861bb906)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-861bb906)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-861bb906)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-861bb906)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-861bb906)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-861bb906)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-861bb906)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-861bb906)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-861bb906)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-861bb906)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-861bb906)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-861bb906)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-861bb906)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-861bb906)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 22:46 UTC, VesaJuvonen commented
Docs Build status updates of commit _[e76f2a6](https://github.com/DhurataJ/sp-dev-docs/commits/e76f2a6f6abe9cf52202e6ef78896bd8b35d72a9)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-aa7be079)

<a id="aa7be079"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202233476137-8169/BuildReport?accessString=35639a0beeeb1b55cf2eddb2310726e3582e9e34de32e0d6ffa2a58073894031).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:53 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5935b10](https://github.com/DhurataJ/sp-dev-docs/commits/5935b10b106c64f03f08e601c921856a112c03de)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-33e0988b)

<a id="33e0988b"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202235577744-8169/BuildReport?accessString=544e0749db0db93e5c46f74f1db34c9266365255e8bd0c9608056723a5b9167b).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 22:57 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8d03e32](https://github.com/DhurataJ/sp-dev-docs/commits/8d03e32d6da6692e2ce409bca86d92b53330f9a5)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-b9b216fc)

<a id="b9b216fc"></a>
###
 - **[Error: PullRequestMergeConflict]** `````Cannot sync git repo to specified state. Please make sure the pull request is mergeable.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206202236212981-8169/BuildReport?accessString=5a81860bed8fc8b033fc6e57d11c1273461c1049ca01175a4d0935ace79655fa).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-20 23:28 UTC, VesaJuvonen commented
Docs Build status updates of commit _[0e4a782](https://github.com/DhurataJ/sp-dev-docs/commits/0e4a782db2b56d134edc371a11d6c49984ca30a9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-ba865aab)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-ba865aab)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-ba865aab)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-ba865aab)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-ba865aab)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-ba865aab)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-ba865aab)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-ba865aab)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-ba865aab)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-ba865aab)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-ba865aab)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-ba865aab)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-ba865aab)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-ba865aab)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-ba865aab)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-ba865aab)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-ba865aab)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-ba865aab)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 23:34 UTC, VesaJuvonen commented
Docs Build status updates of commit _[8fd5111](https://github.com/DhurataJ/sp-dev-docs/commits/8fd5111a106a86cd5696989b6c892c47efd722ed)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-0d80e561)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-0d80e561)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-0d80e561)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-0d80e561)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-0d80e561)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-0d80e561)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-0d80e561)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-0d80e561)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-0d80e561)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-0d80e561)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-0d80e561)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-0d80e561)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-0d80e561)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-0d80e561)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-0d80e561)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-0d80e561)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-0d80e561)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-0d80e561)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 23:38 UTC, VesaJuvonen commented
Docs Build status updates of commit _[834e15d](https://github.com/DhurataJ/sp-dev-docs/commits/834e15db61327b3881c6d022acce279a64e6582a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-6a825dc9)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-6a825dc9)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-6a825dc9)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-6a825dc9)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-6a825dc9)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-6a825dc9)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-6a825dc9)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-6a825dc9)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-6a825dc9)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-6a825dc9)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-6a825dc9)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-6a825dc9)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-6a825dc9)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-6a825dc9)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-6a825dc9)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-6a825dc9)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-6a825dc9)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-6a825dc9)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 23:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[76ab421](https://github.com/DhurataJ/sp-dev-docs/commits/76ab421208041f8f68e0819a70459c6abe95a3ea)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-8f65aaf9)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-8f65aaf9)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-8f65aaf9)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-8f65aaf9)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-8f65aaf9)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-8f65aaf9)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-8f65aaf9)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-8f65aaf9)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-8f65aaf9)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-8f65aaf9)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-8f65aaf9)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-8f65aaf9)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-8f65aaf9)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-8f65aaf9)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-8f65aaf9)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-8f65aaf9)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-8f65aaf9)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-8f65aaf9)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-20 23:43 UTC, VesaJuvonen commented
Docs Build status updates of commit _[997a87a](https://github.com/DhurataJ/sp-dev-docs/commits/997a87a27c2df8fd44cdc6ef4184964263c10610)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-e1987874)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-e1987874)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-e1987874)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-e1987874)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-e1987874)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-e1987874)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-e1987874)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-e1987874)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-e1987874)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-e1987874)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-e1987874)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-e1987874)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-e1987874)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-e1987874)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-e1987874)
[docs/spfx/debug-in-vscode.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-e1987874)
[docs/spfx/enterprise-guidance.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-e1987874)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-e1987874)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/building-simple-field- [...]

2022-06-21 09:55 UTC, andrewconnell requested changes

2022-06-21 09:56 UTC, VesaJuvonen commented
Docs Build status updates of commit _[5628d0b](https://github.com/DhurataJ/sp-dev-docs/commits/5628d0b4152be5a17eaf523c4ef7f9c25a2ba628)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-9bc90d40)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-9bc90d40)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-9bc90d40)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-9bc90d40)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-9bc90d40)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-9bc90d40)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-9bc90d40)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-9bc90d40)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-9bc90d40)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-9bc90d40)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-9bc90d40)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-9bc90d40)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-9bc90d40)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-9bc90d40)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-9bc90d40)
[docs/spfx/debug-in-vscode.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-9bc90d40)
[docs/spfx/enterprise-guidance.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-9bc90d40)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-9bc90d40)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://re [...]

2022-06-21 14:03 UTC, VesaJuvonen commented
Docs Build status updates of commit _[1bce055](https://github.com/DhurataJ/sp-dev-docs/commits/1bce055141979249c4da6f9546f2d4c71c1d641a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/solution-guidance/security-apponly-azureacs.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/solution-guidance/security-apponly-azureacs.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azureacs?branch=pr-en-us-8169) | [Details](#user-content-500b76d83f9965b46bf06fd9eb52f988-296f793a)
[docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/authorization-code-oauth-flow-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-d175fa2380b73c773d066bac05367bd1-296f793a)
[docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/creating-sharepoint-add-ins-that-use-low-trust-authorization?branch=pr-en-us-8169) | [Details](#user-content-bd0b3d9079427eea6c2e1d3937b14698-296f793a)
[docs/sp-add-ins/design-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/design-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/design-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-aa149633cc61e34ea7084fbc2917df2f-296f793a)
[docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/handle-events-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/handle-events-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-e2e402e0cf8a5367a52f4c50593a6318-296f793a)
[docs/sp-add-ins/localize-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/localize-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/localize-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-3582e065cf77da440bbe7adbefc51380-296f793a)
[docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/make-batch-requests-with-the-rest-apis.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/make-batch-requests-with-the-rest-apis?branch=pr-en-us-8169) | [Details](#user-content-8d251809d0f1fc89c84130d0fc2a4b41-296f793a)
[docs/sp-add-ins/office-web-widgetsexperimental-overview.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/office-web-widgetsexperimental-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/office-web-widgetsexperimental-overview?branch=pr-en-us-8169) | [Details](#user-content-e2aeff0edc1c0587014e3d534bc47b3f-296f793a)
[docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/package-and-publish-high-trust-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-0ad7690246e0db5520e188e4b6d5c486-296f793a)
[docs/sp-add-ins/register-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/register-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/register-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-9b8b3b9f3a75245e8b64fd72526e7667-296f793a)
[docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/replace-an-expiring-client-secret-in-a-sharepoint-add-in?branch=pr-en-us-8169) | [Details](#user-content-5e8a231a510ae52375ddd7e090efaf8b-296f793a)
[docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/set-up-an-on-premises-development-environment-for-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-5f154cb8026d865c9b6f540f0c820a2b-296f793a)
[docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-an-office-365-sharepoint-site-to-authorize-provider-hosted-add-ins-on-an-on?branch=pr-en-us-8169) | [Details](#user-content-a5be93c446a44bbba8b2469862972144-296f793a)
[docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-desktop-list-view-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-655530c5f5d2c1430b43b12a616e02c4-296f793a)
[docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/sp-add-ins/use-the-experimental-people-picker-widget-in-sharepoint-add-ins?branch=pr-en-us-8169) | [Details](#user-content-45333b9ac49a33ba6403d849d7e32bea-296f793a)
[docs/spfx/debug-in-vscode.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/debug-in-vscode.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/debug-in-vscode?branch=pr-en-us-8169) | [Details](#user-content-f9f5c1edb1299221dee244002e25d399-296f793a)
[docs/spfx/enterprise-guidance.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/enterprise-guidance.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/enterprise-guidance?branch=pr-en-us-8169) | [Details](#user-content-f8dfe6a35e34bc3a17f0d845636d6a27-296f793a)
[docs/spfx/extensions/get-started/build-a-hello-world-extension.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/extensions/get-started/build-a-hello-world-extension.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/extensions/get-started/build-a-hello-world-extension?branch=pr-en-us-8169) | [Details](#user-content-6fb63072976a3c5ca9465ed17884c66f-296f793a)
[docs/spfx/extensions/get-started/building-simple-field-customizer.md](https://github.com/DhurataJ/sp-dev-docs/blob/sdd-dhj-wb4/docs/spfx/extensions/get-started/building-simple-field-customizer.md) | :warning:Warning | [View](https://re [...]

2022-06-23 09:38 UTC, andrewconnell approved these changes

2022-06-23 10:11 UTC, merged