Validation: Added Missing Alt Text
SharePoint/sp-dev-docs pull request #8174
Opened 2022-06-13 23:37 UTC by dereklh7

## Category

- [x] Content fix
- [ ] New article

## Related issues

This PR is part of the Validation cleanup efforts.

## What's in this Pull Request?

Added missing alt text, added missing description, and changed duplicate H1.

2022-06-13 23:38 UTC, VesaJuvonen commented
Docs Build status updates of commit _[cb07a77](https://github.com/dereklh7/sp-dev-docs/commits/cb07a77c712d39270286bf9492675ba240371e51)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/toolchain/implement-ci-cd-with-azure-devops?branch=pr-en-us-8174) | [Details](#user-content-81bcd17809b752ca12b1f5db5f957c47-cfec16b5)
[docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro?branch=pr-en-us-8174) | [Details](#user-content-6fa2ea48da572fec7d8c15ecdb08333f-cfec16b5)
[docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-card?branch=pr-en-us-8174) | [Details](#user-content-dff02a73e61a58202eeeaf51ce8eda1b-cfec16b5)
[docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-quick-view?branch=pr-en-us-8174) | [Details](#user-content-ce7bd3af60e4cd71861b789c56646b40-cfec16b5)
[docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/quick-view-samples?branch=pr-en-us-8174) | [Details](#user-content-e9260ca9032a44cdc7f3e9d50f50ac09-cfec16b5)

<a id="81bcd17809b752ca12b1f5db5f957c47-cfec16b5"></a>
### [docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/toolchain/implement-ci-cd-with-azure-devops.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 55, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'installing node 10' is duplicated. Within an article, alt text must be unique.`````
 - **Line 212, Column 1**: **[Warning: duplicate-alt-text - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/duplicate-alt-text?branch=main)]** `````Alt text 'installing node 10' is duplicated. Within an article, alt text must be unique.`````

<a id="6fa2ea48da572fec7d8c15ecdb08333f-cfec16b5"></a>
### [docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="dff02a73e61a58202eeeaf51ce8eda1b-cfec16b5"></a>
### [docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ce7bd3af60e4cd71861b789c56646b40-cfec16b5"></a>
### [docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e9260ca9032a44cdc7f3e9d50f50ac09-cfec16b5"></a>
### [docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````
 - **Line 102, Column 1**: **[Warning: alt-text-bad-value - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/alt-text-bad-value?branch=main)]** `````Alt text 'Vaccination' is the same as the image file name. This redundancy adds no value for users of screen readers. For accessibility, add more descriptive alt text.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206132337232210-8174/BuildReport?accessString=96952b15584dedfd5492b14d963d739392d265ff9c0bdb7c16bb105f16eb23fb).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-13 23:45 UTC, VesaJuvonen commented
Docs Build status updates of commit _[c9144e6](https://github.com/dereklh7/sp-dev-docs/commits/c9144e6fabaf431f46b461e8ee489ef841c6d5b9)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/design-intro?branch=pr-en-us-8174) | [Details](#user-content-6fa2ea48da572fec7d8c15ecdb08333f-6f3828e7)
[docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-card?branch=pr-en-us-8174) | [Details](#user-content-dff02a73e61a58202eeeaf51ce8eda1b-6f3828e7)
[docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/designing-quick-view?branch=pr-en-us-8174) | [Details](#user-content-ce7bd3af60e4cd71861b789c56646b40-6f3828e7)
[docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/spfx/viva/design/quick-view-samples?branch=pr-en-us-8174) | [Details](#user-content-e9260ca9032a44cdc7f3e9d50f50ac09-6f3828e7)

<a id="6fa2ea48da572fec7d8c15ecdb08333f-6f3828e7"></a>
### [docs/spfx/viva/design/design-intro.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/design-intro.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="dff02a73e61a58202eeeaf51ce8eda1b-6f3828e7"></a>
### [docs/spfx/viva/design/designing-card.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-card.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="ce7bd3af60e4cd71861b789c56646b40-6f3828e7"></a>
### [docs/spfx/viva/design/designing-quick-view.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/designing-quick-view.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

<a id="e9260ca9032a44cdc7f3e9d50f50ac09-6f3828e7"></a>
### [docs/spfx/viva/design/quick-view-samples.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/spfx/viva/design/quick-view-samples.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206132344066406-8174/BuildReport?accessString=9523c7e58fb255c77963c072b2ebcafa1fbf57774622e222eaf1ec9ef41070d2).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-14 00:09 UTC, RedZephyr13 commented on docs/spfx/viva/design/designing-card.md
> +:::image type="content" source="../../../images/viva-design/img_card_truncation.jpg" alt-text="Diagram that shows the submit time of... and Time off options, with the Time off option being the recomm
Does it make sense to have multiple periods for alt-text.  I think one would suffice.

2022-06-14 00:11 UTC, RedZephyr13 commented on docs/spfx/viva/design/designing-card.md
> +:::image type="content" source="../../../images/viva-design/img_card_image.jpg" alt-text="Showing the medium and large icons showing how an image appears for the medium card layout versus how it appe
Should we start this one off with, "Diagram/Screenshot that shows the medium and large icons showing..."

Using "showing" twice in a sentence sounds awkward.

2022-06-14 00:12 UTC, RedZephyr13 commented on docs/spfx/viva/design/designing-card.md
> +:::image type="content" source="../../../images/viva-design/img_card_collections.jpg" alt-text="Screenshot showing various example cards, including cards for Shifts, Tasks, COVID-19, and Tutorials.":
Let's take out the dash between Covid and 19, since alt-text might say the word "dash."

2022-06-14 00:14 UTC, RedZephyr13 commented on docs/spfx/viva/design/quick-view-samples.md
> +:::image type="content" source="../../../images/viva-design/samples/inventory.png" alt-text="Screenshot of a sample inventory details card from a warehouse, showing Distribution center # 73's top sel
Maybe replace the hash with "number 73's," if that what the hash represetns in this case.

2022-06-14 14:58 UTC, dereklh7 commented
The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you’d like to see. Thank you!

2022-06-26 09:31 UTC, andrewconnell requested changes

2022-06-26 09:31 UTC, andrewconnell commented on docs/spfx/viva/design/design-intro.md
> +# Design guidance for Viva Connections cards
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-27 21:47 UTC, dereklh7 commented
@andrewconnell I have implemented requested changes. Please let me know if there are any other issues preventing approval and merge for this PR. Thanks!

2022-06-28 09:23 UTC, merged