[Bulk] Validation: Fixed issues 6/15
SharePoint/sp-dev-docs pull request #8203
Opened 2022-06-15 15:46 UTC by reemsabaw1

## Category

- [x] Content fix
- [ ] New article

## Related issues

**Global effort to fix build validation errors**

## What's in this Pull Request?

Fixes related to missing descriptions and column headers in 28 files.

2022-06-15 15:48 UTC, VesaJuvonen commented
Docs Build status updates of commit _[4197894](https://github.com/reemsabaw1/sp-dev-docs/commits/4197894ec0f6169c8c5ad1d39a161276565f4188)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/view-schema-elements-a-f.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/view-schema-elements-a-f.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-a-f?branch=pr-en-us-8203) | [Details](#user-content-a4316391131e06a8f89b78013fddb743-9e16775d)
[docs/schema/view-schema-elements-g-l.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/view-schema-elements-g-l.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-g-l?branch=pr-en-us-8203) | [Details](#user-content-4c17d6ff71ccd8b374f552b4e30b01e5-9e16775d)
[docs/schema/view-schema-elements-m-z.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/view-schema-elements-m-z.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-m-z?branch=pr-en-us-8203) | [Details](#user-content-1809ea35372689677b5b281cf4c99d1d-9e16775d)
[docs/schema/viewfooter-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewfooter-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewfooter-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-725f8f73e26bb436b8c48c0d17f7cf22-9e16775d)
[docs/schema/viewform-element-deploymentviewformslist.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewform-element-deploymentviewformslist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewform-element-deploymentviewformslist?branch=pr-en-us-8203) | [Details](#user-content-d5c6ea1e613137c867216d98ca23677f-9e16775d)
[docs/schema/viewformslist-element-deploymentviewformslist.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewformslist-element-deploymentviewformslist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewformslist-element-deploymentviewformslist?branch=pr-en-us-8203) | [Details](#user-content-db16186c8098db598190342e73250aa1-9e16775d)
[docs/schema/viewheader-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewheader-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewheader-element-deploymentmanifestspview?branch=pr-en-us-8203) | [Details](#user-content-d5f4dc9e75b10908159053a8cc0189dd-9e16775d)
[docs/schema/viewheader-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewheader-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewheader-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-3ac449b1c711a72e7cb239af57758b4b-9e16775d)
[docs/schema/views-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/views-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/views-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-7ec2720624d79f28608afef80b2251bf-9e16775d)
[docs/schema/views-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/views-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/views-element?branch=pr-en-us-8203) | [Details](#user-content-f5c2a09c2aedbc2c821f84eae9dc2ca0-9e16775d)
[docs/schema/viewstyle-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewstyle-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewstyle-element-deploymentmanifestspview?branch=pr-en-us-8203) | [Details](#user-content-5b8601bc031558233cf136ec2e8e3d84-9e16775d)
[docs/schema/viewstyle-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewstyle-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewstyle-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-331b9317f833aaf8b41540e33f30b247-9e16775d)
[docs/schema/web-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/web-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/web-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-aa44c0fafd682538a12b6a7e0109cba1-9e16775d)
[docs/schema/webpart-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpart-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-dc076beca837cc6c41b5ae3959c4d559-9e16775d)
[docs/schema/webpart-element-module.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpart-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-module?branch=pr-en-us-8203) | [Details](#user-content-b95dca21e891b21b7decd23f2070aab0-9e16775d)
[docs/schema/webpart-element-site.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpart-element-site.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-site?branch=pr-en-us-8203) | [Details](#user-content-f0bd3a020cdadd0e540a7571e5b877f7-9e16775d)
[docs/schema/webpartconnection-element-module.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpartconnection-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartconnection-element-module?branch=pr-en-us-8203) | [Details](#user-content-4c1c07baa476ffd8ec136df683ee239b-9e16775d)
[docs/schema/webpartconnection-element-site.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpartconnection-element-site.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartconnection-element-site?branch=pr-en-us-8203) | [Details](#user-content-d7fa6c1d7c195c188fea0d61256868aa-9e16775d)
[docs/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures?branch=pr-en-us-8203) | [Details](#user-content-993d1fe142dea6f4f3b7fcd7e5ecbffa-9e16775d)
[docs/schema/webparts-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webparts-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webparts-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-b3bdff22887275f5ce71f7fc456ef471-9e16775d)
[docs/schema/webparttransformer-element-module.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webparttransformer-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webparttransformer-element-module?branch=pr-en-us-8203) | [Det [...]

2022-06-15 17:12 UTC, RedZephyr13 commented on docs/schema/webtemplatedefinition-complextype-sharepoint-add-in-manifest.md
> +| Id  | [WebTemplateIdDefinition](webtemplateiddefinition-simpletype-sharepoint-add-in-manifest.md) | required | The ID of the WebTemplate that should be used when creating the add-in web. | This typ
The convertor tool added escape characters `\` in front of asterisks and underscores.  We need to remove them, so please use this for line 56:

`| Id  | [WebTemplateIdDefinition](webtemplateiddefinition-simpletype-sharepoint-add-in-manifest.md) | required | The ID of the WebTemplate that should be used when creating the add-in web. | This type is a string of the form `{hyphenated_GUID}#web_template_name`  </br></br>The hyphenated_GUID is the GUID of the add-in web Feature that contains the [WebTemplate Element (Web Template)](webtemplate-element-web-template.md) that defines the site type of the add-in web.</br></br>The web_template_name is the value of the **Name** attribute of that [WebTemplate Element (Web Template)](webtemplate-element-web-template.md).</br></br>Note that the braces "{}" and the "#" are mandatory.</br></br>The following is an example:</br>`\` |`

2022-06-16 22:26 UTC, VesaJuvonen commented
Docs Build status updates of commit _[2ee2f3b](https://github.com/reemsabaw1/sp-dev-docs/commits/2ee2f3b8989798278828933ebac6c1c8d8271afa)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/view-schema-elements-a-f.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/view-schema-elements-a-f.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-a-f?branch=pr-en-us-8203) | [Details](#user-content-a4316391131e06a8f89b78013fddb743-5bfc62fd)
[docs/schema/view-schema-elements-g-l.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/view-schema-elements-g-l.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-g-l?branch=pr-en-us-8203) | [Details](#user-content-4c17d6ff71ccd8b374f552b4e30b01e5-5bfc62fd)
[docs/schema/view-schema-elements-m-z.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/view-schema-elements-m-z.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-m-z?branch=pr-en-us-8203) | [Details](#user-content-1809ea35372689677b5b281cf4c99d1d-5bfc62fd)
[docs/schema/viewfooter-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewfooter-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewfooter-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-725f8f73e26bb436b8c48c0d17f7cf22-5bfc62fd)
[docs/schema/viewform-element-deploymentviewformslist.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewform-element-deploymentviewformslist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewform-element-deploymentviewformslist?branch=pr-en-us-8203) | [Details](#user-content-d5c6ea1e613137c867216d98ca23677f-5bfc62fd)
[docs/schema/viewformslist-element-deploymentviewformslist.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewformslist-element-deploymentviewformslist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewformslist-element-deploymentviewformslist?branch=pr-en-us-8203) | [Details](#user-content-db16186c8098db598190342e73250aa1-5bfc62fd)
[docs/schema/viewheader-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewheader-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewheader-element-deploymentmanifestspview?branch=pr-en-us-8203) | [Details](#user-content-d5f4dc9e75b10908159053a8cc0189dd-5bfc62fd)
[docs/schema/viewheader-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewheader-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewheader-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-3ac449b1c711a72e7cb239af57758b4b-5bfc62fd)
[docs/schema/views-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/views-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/views-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-7ec2720624d79f28608afef80b2251bf-5bfc62fd)
[docs/schema/views-element.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/views-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/views-element?branch=pr-en-us-8203) | [Details](#user-content-f5c2a09c2aedbc2c821f84eae9dc2ca0-5bfc62fd)
[docs/schema/viewstyle-element-deploymentmanifestspview.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewstyle-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewstyle-element-deploymentmanifestspview?branch=pr-en-us-8203) | [Details](#user-content-5b8601bc031558233cf136ec2e8e3d84-5bfc62fd)
[docs/schema/viewstyle-element-deploymentmanifestspwebpart.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/viewstyle-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewstyle-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-331b9317f833aaf8b41540e33f30b247-5bfc62fd)
[docs/schema/web-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/web-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/web-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-aa44c0fafd682538a12b6a7e0109cba1-5bfc62fd)
[docs/schema/webpart-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpart-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-dc076beca837cc6c41b5ae3959c4d559-5bfc62fd)
[docs/schema/webpart-element-module.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpart-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-module?branch=pr-en-us-8203) | [Details](#user-content-b95dca21e891b21b7decd23f2070aab0-5bfc62fd)
[docs/schema/webpart-element-site.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpart-element-site.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-site?branch=pr-en-us-8203) | [Details](#user-content-f0bd3a020cdadd0e540a7571e5b877f7-5bfc62fd)
[docs/schema/webpartconnection-element-module.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpartconnection-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartconnection-element-module?branch=pr-en-us-8203) | [Details](#user-content-4c1c07baa476ffd8ec136df683ee239b-5bfc62fd)
[docs/schema/webpartconnection-element-site.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpartconnection-element-site.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartconnection-element-site?branch=pr-en-us-8203) | [Details](#user-content-d7fa6c1d7c195c188fea0d61256868aa-5bfc62fd)
[docs/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures?branch=pr-en-us-8203) | [Details](#user-content-993d1fe142dea6f4f3b7fcd7e5ecbffa-5bfc62fd)
[docs/schema/webparts-element-deploymentmanifest.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webparts-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webparts-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-b3bdff22887275f5ce71f7fc456ef471-5bfc62fd)
[docs/schema/webparttransformer-element-module.md](https://github.com/SharePoint/sp-dev-docs/blob/main/docs/schema/webparttransformer-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webparttransformer-element-module?branch=pr-en-us-8203) | [Det [...]

2022-06-16 22:31 UTC, reemsabaw1 commented
**Global effort to fix build validation errors**

The Content & Learning team is fixing build validation errors on docs.microsoft.com for the rest of H2. This will eliminate potential accessibility, security, and usability issues. This PR includes only build validation fixes and does not change other content. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

2022-06-27 11:08 UTC, andrewconnell requested changes

2022-06-27 11:08 UTC, andrewconnell commented on docs/schema/webtemplatedefinition-complextype-sharepoint-add-in-manifest.md
> +| Id  | [WebTemplateIdDefinition](webtemplateiddefinition-simpletype-sharepoint-add-in-manifest.md) | required | The ID of the WebTemplate that should be used when creating the add-in web. | This typ
This stripped off the code example at the end of the cell. Please add that back

2022-06-27 17:42 UTC, VesaJuvonen commented
Docs Build status updates of commit _[f80f209](https://github.com/reemsabaw1/sp-dev-docs/commits/f80f209407be24e5798f2ee8ae8aeabf29ff8c29)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/schema/viewfooter-element-deploymentmanifestspwebpart.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/viewfooter-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewfooter-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-725f8f73e26bb436b8c48c0d17f7cf22-9d9839e0)
[docs/schema/viewform-element-deploymentviewformslist.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/viewform-element-deploymentviewformslist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewform-element-deploymentviewformslist?branch=pr-en-us-8203) | [Details](#user-content-d5c6ea1e613137c867216d98ca23677f-9d9839e0)
[docs/schema/viewformslist-element-deploymentviewformslist.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/viewformslist-element-deploymentviewformslist.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewformslist-element-deploymentviewformslist?branch=pr-en-us-8203) | [Details](#user-content-db16186c8098db598190342e73250aa1-9d9839e0)
[docs/schema/viewheader-element-deploymentmanifestspview.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/viewheader-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewheader-element-deploymentmanifestspview?branch=pr-en-us-8203) | [Details](#user-content-d5f4dc9e75b10908159053a8cc0189dd-9d9839e0)
[docs/schema/viewheader-element-deploymentmanifestspwebpart.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/viewheader-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewheader-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-3ac449b1c711a72e7cb239af57758b4b-9d9839e0)
[docs/schema/view-schema-elements-a-f.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/view-schema-elements-a-f.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-a-f?branch=pr-en-us-8203) | [Details](#user-content-a4316391131e06a8f89b78013fddb743-9d9839e0)
[docs/schema/view-schema-elements-g-l.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/view-schema-elements-g-l.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-g-l?branch=pr-en-us-8203) | [Details](#user-content-4c17d6ff71ccd8b374f552b4e30b01e5-9d9839e0)
[docs/schema/view-schema-elements-m-z.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/view-schema-elements-m-z.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/view-schema-elements-m-z?branch=pr-en-us-8203) | [Details](#user-content-1809ea35372689677b5b281cf4c99d1d-9d9839e0)
[docs/schema/views-element.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/views-element.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/views-element?branch=pr-en-us-8203) | [Details](#user-content-f5c2a09c2aedbc2c821f84eae9dc2ca0-9d9839e0)
[docs/schema/views-element-deploymentmanifest.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/views-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/views-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-7ec2720624d79f28608afef80b2251bf-9d9839e0)
[docs/schema/viewstyle-element-deploymentmanifestspview.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/viewstyle-element-deploymentmanifestspview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewstyle-element-deploymentmanifestspview?branch=pr-en-us-8203) | [Details](#user-content-5b8601bc031558233cf136ec2e8e3d84-9d9839e0)
[docs/schema/viewstyle-element-deploymentmanifestspwebpart.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/viewstyle-element-deploymentmanifestspwebpart.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/viewstyle-element-deploymentmanifestspwebpart?branch=pr-en-us-8203) | [Details](#user-content-331b9317f833aaf8b41540e33f30b247-9d9839e0)
[docs/schema/web-element-deploymentmanifest.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/web-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/web-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-aa44c0fafd682538a12b6a7e0109cba1-9d9839e0)
[docs/schema/webpartconnection-element-module.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webpartconnection-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartconnection-element-module?branch=pr-en-us-8203) | [Details](#user-content-4c1c07baa476ffd8ec136df683ee239b-9d9839e0)
[docs/schema/webpartconnection-element-site.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webpartconnection-element-site.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartconnection-element-site?branch=pr-en-us-8203) | [Details](#user-content-d7fa6c1d7c195c188fea0d61256868aa-9d9839e0)
[docs/schema/webpart-element-deploymentmanifest.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webpart-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-dc076beca837cc6c41b5ae3959c4d559-9d9839e0)
[docs/schema/webpart-element-module.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webpart-element-module.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-module?branch=pr-en-us-8203) | [Details](#user-content-b95dca21e891b21b7decd23f2070aab0-9d9839e0)
[docs/schema/webpart-element-site.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webpart-element-site.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpart-element-site?branch=pr-en-us-8203) | [Details](#user-content-f0bd3a020cdadd0e540a7571e5b877f7-9d9839e0)
[docs/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webpartpersonalizationscope-simpletype-apphostwebfeatures?branch=pr-en-us-8203) | [Details](#user-content-993d1fe142dea6f4f3b7fcd7e5ecbffa-9d9839e0)
[docs/schema/webparts-element-deploymentmanifest.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webparts-element-deploymentmanifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/schema/webparts-element-deploymentmanifest?branch=pr-en-us-8203) | [Details](#user-content-b3bdff22887275f5ce71f7fc456ef471-9d9839e0)
[docs/schema/webparttransformer-element-module.md](https://github.com/reemsabaw1/sp-dev-docs/blob/fix-sdd10/docs/schema/webparttransformer-element-module.md) | :warning:Warning | [View](https://review.docs [...]

2022-06-27 18:00 UTC, merged