Update sp-migration-api-and-sensitivity-labels.md
SharePoint/sp-dev-docs pull request #8219
Opened 2022-06-22 23:23 UTC by cabailey

Branding corrections

## Category

- [x ] Content fix
- [ ] New article

## What's in this Pull Request?

Branding fixes that were made in error - contact me internally for more info.  BTW your template still says "Target the 'master' branch of this repo" when it's been renamed 'main'.

2022-06-22 23:25 UTC, VesaJuvonen commented
Docs Build status updates of commit _[045229a](https://github.com/cabailey/sp-dev-docs/commits/045229ae470c9bd4e325ec048373a306bee49e1a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/cabailey/sp-dev-docs/blob/patch-1/docs/apis/sp-migration-api-and-sensitivity-labels.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/apis/sp-migration-api-and-sensitivity-labels?branch=pr-en-us-8219) | [Details](#user-content-9f08b228b5114af9db9452c0181bd916-5e5927e9)

<a id="9f08b228b5114af9db9452c0181bd916-5e5927e9"></a>
### [docs/apis/sp-migration-api-and-sensitivity-labels.md](https://github.com/cabailey/sp-dev-docs/blob/patch-1/docs/apis/sp-migration-api-and-sensitivity-labels.md)
 - **Line 2, Column 1**: **[Warning: ms-prod-and-service - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/ms-prod-and-service?branch=main)]** `````Only one of the following attributes can exist: 'ms.prod', 'ms.service'. Use ms.prod for on-premise products, or ms.service for cloud services.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202206222323554644-8219/BuildReport?accessString=58f958b7b4b8dd06e448bf223c3483f03ac7c721f34e11dcd07b6f7f9154651f).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-06-23 09:39 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-06-23 16:17 UTC, cabailey commented
#sign-off  
@andrewconnell  I've updated the date in the metadata but not authoritative to resolve the ms-prod-and-service warning - author owner should do this

2022-06-24 08:13 UTC, andrewconnell approved these changes

2022-06-24 08:34 UTC, merged