Update migrate-from-classic-workflows-to-power-automate-flows.md
SharePoint/sp-dev-docs pull request #8319
Opened 2022-07-19 20:39 UTC by JoanneHendrickson

## Category

- [X ] Content fix/update

## What's in this Pull Request?

Adding Note/alert regarding the availability of SharePoint Migration Tool support of migrating SP 2010 ootb workflows to Power Automate.

2022-07-19 20:41 UTC, VesaJuvonen commented
Docs Build status updates of commit _[64c3972](https://github.com/JoanneHendrickson/sp-dev-docs/commits/64c397249309955656991d7ff708b971805067b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-65/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows?branch=pr-en-us-8319) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202207192039552189-8319/BuildReport?accessString=4e57ad7a456396fde90b89a09c9cbc1b2f107ad7a07250c65979a896802576cb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-07-19 21:32 UTC, andrewconnell requested changes
When you submit a change to a doc, please update the `ms.date` front matter property to the format `MM/DD/YYYY` to reflect the date of the change.

2022-07-19 21:36 UTC, VesaJuvonen commented
Docs Build status updates of commit _[857401a](https://github.com/JoanneHendrickson/sp-dev-docs/commits/857401a1977924969f8a673d2d4a123f574c4e49)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-65/docs/general-development/sharepoint-search-rest-api-overview.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/general-development/sharepoint-search-rest-api-overview?branch=pr-en-us-8319) | [Details](#user-content-c36ed23e96d0ceb0ab0fe77a97ebbefb-d7db233d)
[docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-65/docs/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sharepoint/dev/business-apps/power-automate/guidance/migrate-from-classic-workflows-to-power-automate-flows?branch=pr-en-us-8319) |

<a id="c36ed23e96d0ceb0ab0fe77a97ebbefb-d7db233d"></a>
### [docs/general-development/sharepoint-search-rest-api-overview.md](https://github.com/JoanneHendrickson/sp-dev-docs/blob/patch-65/docs/general-development/sharepoint-search-rest-api-overview.md)
 - **Line 1147, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      <WhiteList xmlns:a="http://schemas.microsoft.com/2003/10/Serialization/Arrays">'`````
 - **Line 1160, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '      </WhiteList>'`````
 - **Line 1176, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: '- **WhiteList** element'`````
 - **Line 1180, Column 1**: **[Warning: sensitive-language-wl - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/sensitive-language?branch=main)]** `````Term 'whitelist' is sensitive and should not be used in content or code. Usage: 'hat's specified in the **QueryProperties** element. Then, all the properties that are listed in the whitelist are copied from the incoming query to the newly constructed query object.'`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/8c4da01d-e430-7fe7-0bea-2c4100cce9e8/202207192135266711-8319/BuildReport?accessString=44c6733f13460dd7e4e6f0f81d3a4051b440ee655fdbbb0eac78a332b4a69b45).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/8c4da01d-e430-7fe7-0bea-2c4100cce9e8?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-08-24 08:54 UTC, andrewconnell approved these changes

2022-08-24 08:54 UTC, merged