Dark Mode for Quickview in Viva Connections Mobile
SharePoint/sp-dev-docs pull request #9113
Opened 2023-07-31 17:50 UTC by sharshach

## Category

- [x] Content fix
- [x] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

> **DELETE THIS LINE BEFORE SUBMITTING** | *If this fixes (aka: closes) or references an issue, please reference it here. This helps maintaining the issue list as it will (1) link the PR to the issue & (2) automatically close the issue when this PR is merged in.*

## What's in this Pull Request?
Adds Documentation about Dark mode QuickView capability's of Viva Connections Mobile 

## Submission guidelines

> - **!!IMPORTANT!!** - All submissions must complete the baseline sections included in this template. Ignoring or deleting this template may result in closing the issue with the label **type:incomplete-submission**.
> - Follow our guidance on [How To Create Good Pull Requests](https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests).
> - Target the `main` branch of this repo.
> - When changing a page, ensure you update the `ms.date` front matter wih the current date in the format `MM/DD/YYYY`.
> - Review all build checks and address the automated errors, warnings, and suggestions.
> - *NOTE: The live site is based on the `live` branch. Site owners periodically refresh `live` branch from the `main` branch so merged PRs won't immediately appear on the live site. Please be patient to see your changes appear on the live site.*
>
> **DELETE THIS SECTION BEFORE SUBMITTING**

2023-07-31 19:16 UTC, AJIXuMuK requested changes

2023-07-31 19:16 UTC, AJIXuMuK commented on docs/spfx/viva/get-started/making-quickview-compatable-darkmode-mobile.md
> +    if(isDarkTheme) {
```typescript
return {
  subTitle: strings.SubTitle,
  title: strings.Title,
  imageUrl: isDarkTheme ? require('../assets/DarkModeImage.png') : require('../assets/LightModeImage.png')
};
```

2023-07-31 19:16 UTC, AJIXuMuK commented on docs/spfx/viva/design/designing-quick-view.md
> +We plan to introduce dark theme support in Quick View Mobile for both iOS and Android in early Q4 of CY23. The API ([context.hostContext.theme](/javascript/api/sp-adaptive-card-extension-base/ihostco
Should it be "Quick View in Viva Connections Mobile" instead of "Quick View Mobile"?

2023-07-31 19:16 UTC, AJIXuMuK commented on docs/spfx/viva/get-started/making-quickview-compatable-darkmode-mobile.md
> +description: Making your Adaptive Card QuickView compatible for both dark and light mode by using different resources for both scenarios.
Quick View instead of QuickView?

2023-08-01 14:59 UTC, AJIXuMuK commented on docs/spfx/viva/get-started/making-quickview-compatable-darkmode-mobile.md
> +    const isDarkTheme = (this.context.hostContext.theme == 'dark') ? true : false;
```suggestion
    const isDarkTheme = (this.context.hostContext.theme === 'dark') ? true : false;
```

2023-08-03 13:36 UTC, andrewconnell requested changes
In addition to the specific changes requested, please run the new & updated MD files though Acrolinx. Seems to be quite a few grammatical issues that should be addressed.

2023-08-03 13:36 UTC, andrewconnell commented on docs/spfx/viva/design/designing-quick-view.md
>  For some cards, you will use links to URLs. Depending on the location of the content, links to URLs may display content in Microsoft Teams or elsewhere and Single sign-on (SSO) behavior can differ. G
This link isn't a valid link... it's in a different repo, so you're making a relative link to a real page. Thus, remove `.md`

2023-08-03 13:36 UTC, andrewconnell commented on docs/spfx/viva/design/designing-quick-view.md
> +> Please test your existing cards using [Adaptive Card designer](https://adaptivecards.io/designer) to make sure that the icons and images used in light mode for Quick View of the existing cards are
The last line includes a reference to a tutorial... where is this? Please make this a link.

2023-08-03 13:36 UTC, andrewconnell commented on docs/spfx/viva/get-started/making-quickview-compatable-darkmode-mobile.md
> +- We will get a Quick View in mobile iOS like this:
Add line break between fenced code & bullet point.

2023-08-04 16:26 UTC, andrewconnell commented
@sharshach Please review the build checks listed above... there's still a broken link that must be fixed.

2023-08-04 16:28 UTC, andrewconnell commented
@sharshach Acrolinx is a tool made available to MSFT employees. I don't have a link handy, but it you search for your internal docs for MS Learning / MS Docs for Acrolinx, it contains a bunch of docs on it.

2023-08-07 08:50 UTC, sharshach commented
@andrewconnell resolved all Build Checks

2023-08-08 12:10 UTC, VesaJuvonen commented
Merging and running through the Acrolynx before publishing. Thanks @sharshach for the great new article and @andrewconnell  for the assistance on the doc formatting adjustments. Team work 👏✨

2023-08-08 12:10 UTC, merged