changes related to $schema refererence update related to SPFx 1.18.x
SharePoint/sp-dev-docs pull request #9401
Opened 2023-12-14 10:42 UTC by HarminderSethi

## Category

- [x] Content fix
- [ ] New article

## Related issues

- N/A

## What's in this Pull Request?
> changes related to $schema refererence update related to SPFx 1.18.x

2023-12-14 11:00 UTC, HarminderSethi commented
for the warning in the build status [docs/spfx/viva/get-started/actions/geolocation/GeolocationTutorial.md], I was not sure if it is requied to change the alt text 'Card appearance after introducing changes in the quick-view' for one image

2023-12-15 14:45 UTC, andrewconnell commented
@HarminderSethi  Yes, that must be fixed. For those who are vision impaired and use screenreaders, it's bad form to use the exact same description on two different images.

2023-12-15 14:46 UTC, andrewconnell requested changes

2023-12-15 14:46 UTC, andrewconnell commented on docs/spfx/viva/get-started/actions/geolocation/GeolocationTutorial.md
Please correct the automatic finding that two images use the same ALT text

2023-12-19 15:31 UTC, HarminderSethi commented on docs/spfx/viva/get-started/actions/geolocation/GeolocationTutorial.md
@andrewconnell I have made the required changes. please review once.

2023-12-20 14:00 UTC, andrewconnell approved these changes

2023-12-20 14:09 UTC, merged