Deleted Container Explanation
SharePoint/sp-dev-docs pull request #9551
Opened 2024-02-29 05:33 UTC by cindylay

## Category

- [x ] Content fix
- [ ] New article

## What's in this Pull Request?

1. This adds an explanation to the Deleted Container section in the Consuming Tenant Admin article.
2. Updated "deleted container collection" to "Recycle Bin"

2024-03-05 11:21 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +## TODO: Introduce two types
This doesn't look complete. Please complete this section before submitting the PR.

2024-03-05 11:22 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +You can create a Trial Container Type using the SharePoint Embedded Visual Studio Code Extension [here](https://marketplace.visualstudio.com/items?itemName=SharepointEmbedded.ms-sharepoint-embedded-v
MS Docs recommend linking the text of the target, not words like 'click this link' or 'here'.

2024-03-05 11:22 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +#TODO:
Incompelte

2024-03-05 11:23 UTC, andrewconnell commented on docs/embedded/tutorials/register-api.md
> +TODO: Explain Registration API purpose
incomplete

2024-03-05 11:23 UTC, andrewconnell commented on docs/embedded/tutorials/register-api.md
> +>>  Note this API must be called with a cert-based access token
incorrect ms node docs format

2024-03-05 11:23 UTC, andrewconnell commented on docs/embedded/tutorials/register-api.md
> +TODO: Expand on this certificate based auth
incomplete

2024-03-05 11:23 UTC, andrewconnell commented on docs/embedded/tutorials/register-api.md
> +TODO: This is NOT a Graph API, clearly state this is a SharePoint API
incomplete

2024-03-05 11:23 UTC, andrewconnell commented on docs/embedded/tutorials/register-api.md
> +>>  Note that other SharePoint Embedded Graph APIs run with the FileStorageContainer.Selected Scope on Microsoft Graph
incorrect msdocs alert format

2024-03-05 11:24 UTC, andrewconnell commented on docs/embedded/tutorials/register-api.md
> +Select Manage > Manifest from the left-hand navigation. Locate the property requiredResourceAccess and edit it so it looks like the following JSON:
markdown format issues: bold navigation items, and mark inline code as code

2024-03-05 11:24 UTC, andrewconnell commented on docs/embedded/tutorials/register-api.md
> +TODO: Explain RootSiteUrl,
incomplete

2024-03-05 11:25 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +* You must have admin credentials to a M365 developer tenant
bullets should have breaklines around them

2024-03-05 11:25 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +* You must register your application in [Microsoft Entra ID](https://learn.microsoft.com/en-us/training/modules/sharepoint-embedded-setup/5-exercise-setup-configure-sharepoint-embedded)
don't use absolute links or locales when referencing pages in learn.Microsoft.com

2024-03-05 11:25 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +![alt text](azuresubscription.png)
invalid image alt text

2024-03-05 11:25 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +![alt text](suboption.png)
invalid image alt text

2024-03-05 11:26 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +![alt text](resource-group.png)
invalid image alt text

2024-03-05 11:26 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +![alt text](c-rg.png)
invalid image alt text

2024-03-05 11:26 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +>> Note: The Region Group does NOT require your Containers to live in that specified region. Your content is not restricted to the specified region
invalid msdocs alert format

2024-03-05 11:26 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +**TODO: Need to explain Region and Resource Group in relation to SharePoint Embedded
incomplete

2024-03-05 11:26 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +<br></br>
don't use html in markdown unless aboslutely necessary (like breaklines within tables). these should be removed

2024-03-05 11:27 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +TODO: Take this out of the article and put it into the register CT article....
incomplete

2024-03-05 11:27 UTC, andrewconnell commented on docs/embedded/tutorials/register-ct.md
> +* Please Note that you will need to use a cert-based access token to make this API call.
should this be a real msdocs alert?

2024-03-05 11:29 UTC, andrewconnell requested changes
This appears to be a work in progress PR... if that's correct, please use set to a draft PR to indicate it's not ready for review. I'll do this now as that's what it seems with the numerous "todo" comments in the content.

Open PR's communicate that it's ready to be reviewed & merged. Thanks!

2024-03-06 18:26 UTC, cindylay commented
Thanks for the feedback @andrewconnell , I realize I've duplicated Container Type content here from #9562 . I've added the CTA content changes to #9562 and will implement the other Container Type feedback listed here as well.

2024-03-06 18:26 UTC, closed without merging