Container Type Content Update and Register Container Type API
SharePoint/sp-dev-docs pull request #9562
Opened 2024-03-06 00:14 UTC by cindylay

## Category

- [ x] Content fix
- [ x] New article
 

## What's in this Pull Request?
This PR contains updates to Container Type article and includes new API documentation for registering a container type. The `.yml`  file is updated to show the new article in the table of contents

Updates to:
Content updates to `containertypes.md`
Content updates to `auth.md`
TOC addition to `toc.yml`

New article addition:
`register-api-documentation.md`

2024-03-06 00:17 UTC, cindylay commented
I'd like to only merge the 4 mentioned files from the description:
`containertypes.md`
`auth.md`
`toc.yml`
`register-api-documentation.md`

Is there a way to remove the other changed files from this PR? @andrewconnell @VesaJuvonen

2024-03-06 10:26 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/auth.md
> +>>  Note that other SharePoint Embedded Graph APIs run with the FileStorageContainer.Selected Scope on Microsoft Graph
- this should use the MSDOCS alert format
- `Scope` should be lowercase
- should the scope be bold?

2024-03-06 10:41 UTC, andrewconnell requested changes
This isn't a complete submission... there are lots of "TODO" comments throughout the doc. If you're working on the content, please submit the PR as a DRAFT. Open PR's indicate it's ready for review & merge (see [this](https://github.blog/2019-02-14-introducing-draft-pull-requests/) & [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request)).

This PR seems to overlap the other one you submitted recently #9551... is that necessary anymore? 

Strongly suggest you run Acrolinx against each of the MD files you're creating to find & sometimes automatically fix many of the issues I've called out. [Learn more here](https://review.learn.microsoft.com/en-us/help/wwl/publish-content/acrolinx?branch=main). It checks the content for grammar, typos, and issues that violate MSDOCS content rules.

In addition to my comments, review all issues reported in the automated build and fix them as unless there's an exception, we can't merge them until fixed. It's reporting a lot of broken links in the content submission.

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/auth.md
> +Select Manage > Manifest from the left-hand navigation. Locate the property requiredResourceAccess and edit it so it looks like the following JSON:
markdown: 
- steps in navigation should be bold (Manage > Manifest)
- reqiredResourceAccess should be formatted as inline code

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/auth.md
> +> You must configure the `Container.Selected` scope in your App manifest
Should this be marked with a MSDOC alert, such as IMPORTANT?

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +2. [Standard Container Types](#standard-container-types)
Markdown
- numbered bullets should always be `1.`... don't use explicit numbers... let the rendering engine take care of that
- headings, paragraphs, and bullet lists should have line breast around them (there should be empty lines after lines 12 & 13)

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +To enable customers to explore the development of SharePoint Embedded applications and assess its features, we offer the ability to create a Trial Container Type. Each customer can have only one Tria
Please see earlier comment about line breaks for headings & paragraphs

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +Standard Container Types are associated with a billing profile in [Azure Portal](portal.azure.com) when they are created. The billing profile includes a n Azure Subscription ID and a Region Group. Th
Please see earlier comment about line breaks for headings & paragraphs

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +Standard Container Types are associated with a billing profile in [Azure Portal](portal.azure.com) when they are created. The billing profile includes a n Azure Subscription ID and a Region Group. Th
Invalid URL... missing https://

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +- An Azure subscription and Resource Group must be present in the [Azure Portal](portal.azure.com).
Invalid URL, missing https://

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +- An App regisration must be created in [Azure Entra]
It's "Microsoft Entra" + missing link

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +Example of an output of the Get-SPOContainerType  cmdlet
Please see earlier comment about line breaks for paragraphs

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/containertypes.md
> +To register both Trial and Standard Container Types, please refer to the following [tutorial](../app-concepts/register-api-documentation.md)
Please see earlier comment about line breaks for headings & paragraphs

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/register-api-documentation.md
> +> Only the Owning Application of the Container Type can invoke the registration API in the Consuming Tenant.
Should this be a MSDOC alert, like "NOTE"?

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/concepts/app-concepts/register-api-documentation.md
> +> NOTE that this is NOT a Graph API
Should be MSDOC NOTE format

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +<!--
Remove TODO comments from final doc submission

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +* You must have admin credentials to a M365 tenant
Please see earlier comment about line breaks for headings & paragraphs

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +(TODO: add the extra existing Sub id)
incomplete

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +Login to Azure Portal with the admin credentials of your tenant
missing period

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +![alt text](./regct-image/azuresubscription.png)
Image alt text must be unique & should be meaningful

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +>> Note: The Region Group does NOT require your Containers to live in that specified region. Your content is not restricted to the specified region
Should use MSDOCS "NOTE" alert"

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +<br></br>
Don't use HTML in markdown files... this should be removed.

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +To learn more about the role of Container Types in SharePoint Embedded please refer to the [ContainerTypes](../concepts/app-concepts/containertypes.md) and [App Archictecture](../concepts/app-concept
Please see earlier comment about line breaks for headings & paragraphs

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +Have the following information handy from [Azure Portal](portal.azure.com):
Invalid link (see earlier comment).

Please see earlier comment about line breaks for headings & paragraphs

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +TODO: Take this out of the article and put it into the register CT article....
incomplete

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +* Please Note: This API call must be done using Application-only auth.
MSDOC Alert

2024-03-06 10:41 UTC, andrewconnell commented on docs/embedded/tutorials/create-containertype.md
> +* Please Note that you will need to use a cert-based access token to make this API call.
MSDOC alert

2024-03-06 10:45 UTC, andrewconnell commented
@cindylay said:
> I'd like to only merge the 4 mentioned files from the description: `containertypes.md` `auth.md` `toc.yml` `register-api-documentation.md`

That's not possible... we can't edit (include/exclude files) what's in your PR. You need to submit the PR from a branch with only the changes you want to make. See https://github.com/SharePoint/sp-dev-docs/wiki/How-to-Create-Good-Pull-Requests

2024-03-08 23:33 UTC, andrewconnell commented
@cindylay can you review the findings in the automated build... those are pointing to broken anchor tags and the update to the TOC doesn't appear invalid - https://github.com/SharePoint/sp-dev-docs/pull/9562#issuecomment-1984856717

2024-03-11 22:34 UTC, arakeshmicrosoft approved these changes
We have customers asking for this document. I have reviewed and it provides all the neccessary information to get our customers started.

2024-03-11 22:37 UTC, tonchan-msft approved these changes

2024-03-12 10:30 UTC, andrewconnell approved these changes

2024-03-12 10:31 UTC, merged