A clean up of migration api and amr documents.
SharePoint/sp-dev-docs pull request #9644
Opened 2024-04-18 12:05 UTC by underreview

## Category

- [x] Content fix
- [x] New article

## Related issues

- fixes #issuenumber
- partially #issuenumber
- mentioned in #issuenumber

## What's in this Pull Request?

Cleaning up markdown issues, breaking long articles into shorter pieces, fixing acrolinx issues, adding T2T notices.

2024-04-18 13:59 UTC, andrewconnell requested changes
There are [numerous issues reported in the automated build findings](https://github.com/SharePoint/sp-dev-docs/pull/9644#issuecomment-2063878423) that must be addressed before this PR can be reviewed. Please address those before we can review this content.

For instance, multiple new files don't have any frontmatter defined. Look at other content within the repo for examples of what is expected. The previously mentioned findings call out some of these as well.

2024-04-19 13:47 UTC, underreview commented
Hi @andrewconnell , issues are fixed.
Thanks
Ran

2024-04-22 11:28 UTC, andrewconnell requested changes
I made a lot of edits to address markdown formatting, grammar+word choice, and fixed issues found by Acrolinx to improve readability score + conform to MSDocs guidelines. Please review my edits to ensure they are correct.

Also review the changes requested... looks like there were some personal notes left in the edits + a typo with the AES key.

2024-04-22 11:28 UTC, andrewconnell commented on docs/apis/amr-api-reference.md
> +A `EncryptionOption` object, containing the AES256CBCKey used to decrypt the output.
Is 'AES256CBCKey' correct? should this be AES-256-CBC or AES256CBC? In other places, it looks like you used AES256CBC...

2024-04-24 14:43 UTC, underreview commented on docs/apis/migration-content-package.md
> +> The requirement to use and enforce the latest snapshots on all files is coming in a future build. Until then, it will be ignored. @Huan?
this is removed.

2024-04-24 14:43 UTC, underreview commented on docs/apis/migration-manifest.md
> +Likewise, Migration API can't import items with incorrect Document Library IDs and List IDs into the target Document Library or List. Don't reuse IDs within the same site collection, to avoid Migrati
this is now removed.

2024-04-24 22:04 UTC, andrewconnell approved these changes

2024-04-24 22:04 UTC, merged